### ISSUE TITLE
Pipe not working without parameters after angular:beta16

### ISSUE THREAD

**Issue by diegoparraleal** [ocombe/ng2-translate#103]
HI, I had this on my app, and it worked

{{ 'sitemanager.mySites' | translate }}

but, after I updated to latest version, the pipe is exploding because args are null, so I had to do the following workaround

{{ 'sitemanager.mySites' | translate:{any: "thing"}   }}

**Comment by ocombe** [comment]
yup the last version only works for angular 2 beta 16, I need to update the peer dependencies

**Comment by ocombe** [comment]
I just release 2.0 to fix that problem. If you don't use beta 16, stay on v1.11.1
