### ISSUE TITLE
Loading of complete rxjs by using SystemJS needed?

### ISSUE THREAD

**Issue by vreen** [ocombe/ng2-translate#106]
When using ng2-translate like this https://github.com/ocombe/ng2-play/blob/ng2-translate/index.html#L25-L28, my app is getting pretty slow because of loading all rxjs scripts.

Is there a possibility to avoid this Overhead? I am using angular cli btw.

**Comment by ocombe** [comment]
You should definitely generate a bundle of your code when you go into production, don't let it load all the source files separately.
As for when you're developing, it shouldn't load all of RxJS, just the few parts required, right ?

**Comment by vreen** [comment]
I would guess, that only tue observable stuff would be Importe, yes.

Not sure if angular cli supports bundling in their build so far. You mean, I should use webpack in production?

**Comment by ocombe** [comment]
The cli tools will do bundling for sure, just wait until beta 17 later this week, there should be quite a few updates in this matter :-)
Systemjs has a bundling tool as well that you can use.

**Comment by vreen** [comment]
Great, I'll read more about SystemJS.
Thanks!
