### ISSUE TITLE
A bug in Angular2-bate.17 

### ISSUE THREAD

**Issue by lizhong8532** [ocombe/ng2-translate#109]
console.log print: browser_adapter.ts:73 ORIGINAL EXCEPTION: TypeError: Cannot read property 'length' of undefined

translate.pipe.ts  line 88
```
 if(args.length && args[0] !== null) {  // The args is undefined
```

**Comment by ocombe** [comment]
Oh thanks for the report, I'll look into it next week (this week is ng conf and I'll be busy)

**Comment by robsonke** [comment]
You're probably already aware of it, but in beta16 the pipe args isn't an array anymore but now separate arguments:
https://github.com/angular/angular/commit/152a117

**Comment by Paladinium** [comment]
Confirming the same issue using beta 17.

**Comment by ocombe** [comment]
This was fixed in one of the lasts releases, let me know if you still have the problem after updating.
