### ISSUE TITLE
using in project

### ISSUE THREAD

**Issue by samvloeberghs** [ocombe/ng2-translate#11]
Hi,

I'm trying to integrate this library in the starter kit provided by AngularClass:
https://github.com/AngularClass/angular2-webpack-starter.

https://github.com/AngularClass/angular2-webpack-starter/issues/208

The webpack dev server is serving from the `src` folder. The translations are defined in 
`src/assets/i18n`.

It doesn't seem to find the translation files using the provided setup:
```
export class App {
  name = 'Angular 2 Webpack Starter';
  url = 'https://twitter.com/AngularClass';
  constructor(translate: TranslateService) {

    var prefix = 'assets/i18n';
    var suffix = '.json';
    translate.useStaticFilesLoader(prefix, suffix);

    var userLang = navigator.language.split('-')[0]; // use navigator lang if available
    userLang = /(nl|fr|en)/gi.test(userLang) ? userLang : 'en';

    // optional, default is "en"
    translate.setDefaultLang('en');

    // the lang to use, if the lang isn't available, it will use the current loader to get them
    translate.use(userLang);

  }
}
```

But if I change the configuration to be `var prefix = 'src/assets/i18n';` it works.

I'm not sure this is something related to your package or perhaps to the starter kit architecture. So that's why I'll post it and reference it in both projects.

Kr
Sam V.

**Comment by ocombe** [comment]
Yes, it's related to the starter architecture, not ng2-translate.
If you want to see my integration of the lib with webpack, check my starter: https://github.com/ocombe/ng2-webpack

The problem in the case of AngularClass/angular2-webpack-starter is that the assets are not copied to your public repository/dev server.

You need to add 2 things to your webpack config:
- the contentBase pointing to your public repository: https://github.com/ocombe/ng2-webpack/blob/master/webpack.config.js#L262
- the copy webpack plugin for when you're building your files: https://github.com/ocombe/ng2-webpack/blob/master/webpack.config.js#L218

**Comment by samvloeberghs** [comment]
whoot, thx for the superspeedy reply! :+1: I'll get to it

**Comment by samvloeberghs** [comment]
works like a charm!

**Comment by ocombe** [comment]
Perfect then :-)

**Comment by samvloeberghs** [comment]
I'm adding it as an extension to the starterkit now :)

**Comment by ocombe** [comment]
\o/

Don't get too much into ng2-translate, the i18n official library by google for angular 2 looks very promising and they should do it before angular 2 release

**Comment by samvloeberghs** [comment]
Learning too much too quick today, thx for headsup

**Comment by samvloeberghs** [comment]
@ocombe ,are you still in favor of waiting for the official i18n or do you feel things have changed?

**Comment by ocombe** [comment]
Well I don't see anything moving on the i18n side, we might have to wait a few months until they release something...
As soon as I have more news I'll let you know, but if you need i18n right now you should use ng2-translate because you won't be able to use angular-i18n until at least 2 months (based on the idea that they would start working on it right now, which isn't the case).
As I'm learning new things with angular 2 I will keep ng2-translate updated and add a few new features because this lib helps me as well (I use it on my projects).
And if it appears that angular-i18n is too complex for simple use case, then ng2-translate will not be deprecated and will stay as a simple alternative.

**Comment by samvloeberghs** [comment]
:+1:
