### ISSUE TITLE
Test environnement requirements

### ISSUE THREAD

**Issue by ksontini** [ocombe/ng2-translate#113]
Hi,

I'm trying to run some tests localy. So I clone the repo and npm install, Then I run
`npm run test`

This fail with no signifiant error.

`19 error node v6.0.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error ng2-translate@ test:`tsc && karma start`
22 error Exit status 3221225501`

I'm on windows (sorry for that) and karma-cli is installed globaly.

I'm sure, I'm missing something but can't figure it out.

*_EDIT: *_ I have no problem in *nix OS.

**Comment by ocombe** [comment]
I'm using windows as well and I don't have this problem (tested on different machines), I don't know what it is but I don't think this is related to ng2 translate...

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
