### ISSUE TITLE
doesnt work with angular 2.0.0-rc.1

### ISSUE THREAD

**Issue by fctucker** [ocombe/ng2-translate#116]
is there a plan to update this so it works with the new release candidate?

**Comment by ocombe** [comment]
Yes, there's even a PR for that but I need to review it, I'll do it ASAP
when I'm back from ng conf, maybe even on the plane :-)

**Comment by fctucker** [comment]
awesome, can't wait!  thanks for the update

**Comment by Paladinium** [comment]
Same here. Thanks @ocombe for your efforts!

**Comment by fctucker** [comment]
if you're eager to get something working, you can also use this pull request: https://github.com/ocombe/ng2-translate/pull/115

**Comment by ocombe** [comment]
Updated to RC1 in v2.1
