### ISSUE TITLE
onLangChange triggered multiple times

### ISSUE THREAD

**Issue by aneesa** [ocombe/ng2-translate#118]
Hi,
After a new language has been selected, I used onLangChange to update the language. However, onLangChange is triggered multiple times from a single translate.use call. 

This translate.use is called from the provider **Localization**, and is called from a modal named **locale.ts**. onLangChange is called from one of the main screen, i.e **settings.ts**.

Below are a few excerpts from my files

##### app.ts
```javascript
@App({
  templateUrl: 'build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'languages', '.json'),
      deps: [Http]
    }),
    TranslateService,
    Localization
  ]
})
export class MyApp {...}
```

##### settings.ts
```javascript
@Page({
  templateUrl: 'build/pages/settings/settings.html',
  pipes: [TranslatePipe]
})
export class SettingsPage {
  ...
  constructor(
      public nav: NavController,
      translate: TranslateService) {
    this.nav = nav;
    this.translate = translate;

   // this is being triggered many, many times
    this.translate.onLangChange
      .subscribe((event: LangChangeEvent) => {
        this.translate.use(event.lang);
        this.setLocales();
    });
  }
...
}
```

##### (Modal) locale.ts
```javascript
@Page({
  templateUrl: 'build/pages/locale/locale.html',
  providers: [],
  pipes: [TranslatePipe]
})
export class LocalePage {
  constructor(
      public nav: NavController,
      viewCtrl: ViewController,
      localeService: Localization,
      translateService: TranslateService) {
   ...
  }

  setLocale(localeId) {
    this.localeService.setLocale(localeId, this.translateService);
  }
}
```

##### (Provider) localization.ts
```javascript
@Injectable()
export class Localization {
  setLocale(localeId, translateService) {
      // this is called just once when user picked a new language
      translateService.use(localeId);      
  };
}
```

There are some translations that are being passed to the alert/confirmation pop-ups, hence the reason why I want to use onLangChange. Can you point me to the right direction?

Thank you in advance.

**Comment by ocombe** [comment]
OnLangChange is called for each subscription, maybe you have multiple subscriptions going on? Don't forget that if you subscribe you need to unsubscribe when your component is destroyed otherwise the subscribe keeps firing...

**Comment by aneesa** [comment]
Thanks! Turns out I don't need to call translate.use again in the onLangChange function

```javascript
    this.translate.onLangChange
      .subscribe((event: LangChangeEvent) => {
        // REMOVE this line to make it work
        // this.translate.use(event.lang);
        this.setLocales();
    });
```

**Comment by IgorKurkov** [comment]
> OnLangChange is called for each subscription, maybe you have multiple subscriptions going on? Don't forget that if you subscribe you need to unsubscribe when your component is destroyed otherwise the subscribe keeps firing...

It's true, but if I use onLangChange in service, or in different services, so I can't unsubscribe from them, and all of them fired with service's count of subscriptions... I found a temp solution - check in service `if this.currentLang !== lang.lang` do some stuff, because event fired with the same language multiple times. Also about complete subscribing we can use the third parameter in subscribe(), but imo it's not work in services. Do you have some better solution, maybe @ocombe ?
