### ISSUE TITLE
Feature: translate directive

### ISSUE THREAD

**Issue by BrackCurly** [ocombe/ng2-translate#12]
I would be nice to have a translate directive like: 

``` html
<div [translate]="just.another.property"></div>
```
https://angular-translate.github.io/docs/#/api/pascalprecht.translate.directive:translate

Do you accept pull requests for that?

**Comment by ocombe** [comment]
Is there a case where the directive would be more useful than the pipe ?

If that's the case, I would love a PR for that yes.

**Comment by BrackCurly** [comment]
It's more of a personal preference. In our current 1.x App we always use the translate directive.

**Comment by ocombe** [comment]
You could use:
```html
<div [innerHTML]="just.another.property | translate"></div>
```

Is it close enough for you ?

**Comment by ocombe** [comment]
Closing this for now. Let me know if this wasn't enough for you.

**Comment by gaetancollaud** [comment]
Sorry to dig up this issue, but I find that a component could be a good thing. There is less to write and your html code is more clear.

Without component:
```html
<div>{{'just.another.property'|translate}}</div>
<div [innerHTML]="just.another.property | translate"></div>
```

With component:
```html
<div translate="just.another.property"></div>
```

I already coded a dummy implementation for my personal use : https://gist.github.com/gaetancollaud/777f519d551cc35ce60073e902e17a7e

I can make a PR if you want ? 

Possible improvements: 
* support language change
* support parameters

**Comment by ocombe** [comment]
There is a PR for a directive already here: https://github.com/ocombe/ng2-translate/pull/31
We are waiting for the next RC so that we can use the brand new sanitizer :)

**Comment by gaetancollaud** [comment]
Sorry, I didn't check the pull request lists. Good to here that.
