### ISSUE TITLE
cannot find @angular/core

### ISSUE THREAD

**Issue by VictorCoding** [ocombe/ng2-translate#125]
So it seems that since ng2-translate still uses the path for angular 2 RC, I cannot use it with the latest angular 2 build since they've changed their structure from `@angular` to `angular2`.

Solution seems to be to downgrade or maybe include both, of course none of which are good solutions.

Similar: http://stackoverflow.com/questions/37186188/angular2-jwt-d-ts-gives-cannot-find-module-angular-http-error

**Comment by ocombe** [comment]
Since RC0 they use `@angular` instead of `angular2`, and that's still the case in RC1. Where did you see them changing it again to `angular2`?!
https://www.npmjs.com/~angular

**Comment by VictorCoding** [comment]
Aah. Ok can we ignore this post, I had things backwards this morning.

**Comment by ocombe** [comment]
Okay :)
