### ISSUE TITLE
How to translate special characters like á

### ISSUE THREAD

**Issue by gastonmq** [ocombe/ng2-translate#126]
the json file is like this:

{
  "CHANGELINES": "Cambiar trámite",
 }

and show this:

Cambiar tr�te

Thanks a lot

**Comment by ocombe** [comment]
I think you have a problem of encoding on your json file, because I have accents in my translations files and no problems...

**Comment by gastonmq** [comment]
Than, I solved as follows

{
"CHANGELINES": "Cambiar tr\u00e1mite",
}

**Comment by samvloeberghs** [comment]
@gastonmq as @ocombe said it might have to do with how you save the file.
Try saving the file as utf-8 enconding
