### ISSUE TITLE
License file ?

### ISSUE THREAD

**Issue by egavard** [ocombe/ng2-translate#127]
Hi, 
There is currently no license file in the project.

Do you plan to add one ?

**Comment by ocombe** [comment]
The license in package.json is `"license": "MIT"`, since it's a common license, I don't think a license file is necessary ?

**Comment by egavard** [comment]
As license file is mandatory for any redistribution of your work, it might be useful to put a copy of it in the project root.
Furthermore, it will prevent people (like me) to ask themselves what license your are using.

**Comment by ocombe** [comment]
Ok, I'll add one then :)

**Comment by egavard** [comment]
Here you are.
I let you adapt the copyright owner name/nickname to match your want.

**Comment by mgaert** [comment]
The LICENSE file is not shiped in the tar file via npm. Can you fix that?
