### ISSUE TITLE
Incompatible with @angular/core/core.umd.js

### ISSUE THREAD

**Issue by StephenLujan** [ocombe/ng2-translate#129]
My project was using the gulp to place Angular bundles and systemjs to load them before Angular RC1. I tried to use the .umd.js files as a substitute for the bundles when RC1 released. I noticed everything seems to work fine but ng2-translate is not compatible if only the .umd.js file is used, throwing the following error:

> zone.js:101 GET http://localhost:44355/lib/@angular/core/src/facade/lang.js 404 (Not Found)

I stripped the code down to this test file, to reproduce the error.

```
import { Http, HTTP_PROVIDERS } from '@angular/http';
import {bootstrap} from '@angular/platform-browser-dynamic';
import {TranslateService, TranslateLoader, TranslateStaticLoader} from 'ng2-translate';
import {provide, Component} from '@angular/core';

@Component({
    selector: 'bug',
    providers: [],
    template: '<span>loaded template!</span>',
    directives: []
})
export class TranslateBug {
    constructor(private http: Http, _translationService: TranslateService) {}
}
bootstrap(
    TranslateBug,
    [
        HTTP_PROVIDERS,
        provide(TranslateLoader, {
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'i18n', '.json'),
            deps: [Http]
        }),
        TranslateService
    ]
);
```

**Comment by StephenLujan** [comment]
For now I've just copied that one file into place. `@angular/core/src/facade/lang.js` I haven't seen any other issues.

**Comment by ocombe** [comment]
The methods from lang are not really necessary, I could rewrite the few that I use so that it works for all users. I'll add it to the todo list, thanks for the report.

**Comment by Meligy** [comment]
Anyone kindly looking into this? I'm having the same issue as well.

Thanks heaps for the awesome free library :+1:

**Comment by Meligy** [comment]
In my case I'm using this with webpack and loading Angular from umd files. I get errors for the resolution of the path in the issue.

**Comment by Meligy** [comment]
It's in `ng2-bootstrap/components/utils/utils.class.js`
