### ISSUE TITLE
Angular RC1 EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of null

### ISSUE THREAD

**Issue by danielgolub** [ocombe/ng2-translate#130]
I have an Ionic 2 beta 7 application,
And after upgrading dependencies to Angular 2 RC1, it seems like I have the following error:
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of null

> browser_adapter.js:77 EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'isSkipSelf' of nullBrowserDomAdapter.logError 

I boot my app this way:
```
@App({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
	providers: [
		provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [Http]
    }),
    TranslateService
  ],
  pipes: [TranslatePipe]
})


```

And call to the following function from the constructor:

```
	initializeTranslateServiceConfig() {
		var userLang = navigator.language.split('-')[0]; // use navigator lang if available
		userLang = /(fr|en)/gi.test(userLang) ? userLang : 'en';

		 // this language will be used as a fallback when a translation isn't found in the current language
		this.translate.setDefaultLang('en');

		 // the lang to use, if the lang isn't available, it will use the current loader to get them
		this.translate.use(userLang);
	}

```
Unfortunately my application does not boot anymore. Does anyone have a clue on what's wrong?

Thanks!

**Comment by mikeumus** [comment]
Hey @danielgolub, see: 
- https://github.com/angular/angular/issues/8519
- https://stackoverflow.com/questions/37165992/angular-2-exception-typeerror-cannot-read-property-isskipself-of-null-brow

Hope it helps. :smile:

**Comment by danielgolub** [comment]
Well I had a pretty stupid problem, and it's not related to ng2-translate module.
I had a component with a provider 'elementRef'..
@Directive({
  selector: '[no-internet]' // Attribute selector
  providers: [ ElementRef ],
})
