### ISSUE TITLE
Handle values that are arrays (for long translation values)

### ISSUE THREAD

**Issue by Paladinium** [ocombe/ng2-translate#131]
Say you have a long translated value. You can either accept a very long string in your JSON, e.g.:

```
{
   "key": "very long and never ending string..."
}
```

which forces you to scroll. Or you can have an array as value:

```
{
   "key": [
              "line one ",
              "line two ",
              "line three"
            ]
}
```

This already works with ng2-translate. However, the resulting string is probably created by using 'toString' on the array, which joins the array entries with a comma instead of just an empty string.

Instead of "line one line two line three" you get "line one ,line two ,line three".

**Comment by ocombe** [comment]
Hello, I can see the appeal, but it's not something that I might change, it's not necessary and I don't want to make the lib too complicated.
This kind of changes will make it harder in the long term to support more interesting features.
I hope that you understand ! Thanks for the idea though :)

**Comment by Paladinium** [comment]
Sure.

**Comment by supertorpe** [comment]
An easy workaround: implement a pipe that inherits from TranslatePipe and takes into account the arrays:
```typescript
import { PipeTransform, Pipe, Injectable } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

@Injectable()
@Pipe({ name: 'translatext', pure: false })
export class TranslatextPipe extends TranslatePipe implements PipeTransform {
    transform(query: string, ...args: any[]): any {
        const result = super.transform(query, args);
        if (result instanceof Array) {
            return result.join('\n');
        } else {
            return result;
        }
    }
}
```

...then in the template:   {{ 'mykey' | translatext }}

**Comment by thoemmi** [comment]
Unfortunately, this workaround doesn't support parameters. E.g. if you have this translation:

```javascript
{
    "HOME": {
        "HELLO": [ "hello", "{{value}}" ]
    }
}
```
```html
<div>{{ 'HELLO' | translate:param }}</div>
```
then `{{value}}` won't be replaced. I guess parameters are handled only in strings, but not string arrays.
