### ISSUE TITLE
Cannot resolve all parameters for 'TranslateService'(?, ?, ?)

### ISSUE THREAD

**Issue by bmayen** [ocombe/ng2-translate#135]
Getting the following error when passing `TRANSLATE_PROVIDERS` to angular's `bootstrap`:
`Uncaught Cannot resolve all parameters for 'TranslateService'(?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TranslateService' is decorated with Injectable.`

Using angular @rc1 and building via SystemJS Builder @0.15.18.

**Comment by bmayen** [comment]
User error. Closing.

**Comment by mattvague** [comment]
Hi, what was your resolution for this?

**Comment by bmayen** [comment]
Sorry, I can't remember at this point. May 26 feels like it was a year ago :/ 

Checked project commit history, but the only commit at that time is the working version. Not sure what I was doing locally before the commit that was causing the issue. Want to post your source?
