### ISSUE TITLE
Cannot resolve all parameters for 'TranslateService'(?, ?, ?)

### ISSUE THREAD

**Issue by izzsuan** [ocombe/ng2-translate#137]
Hi,
I have a problem with ng2_translate...
i use Angular2-rc1 with grunt, browserify and angular2-universal-polyfills

in my main I have import all library but i have this error:
reflective_provider.js:182 Uncaught Cannot resolve all parameters for 'TranslateService'(?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TranslateService' is decorated with Injectable.

`///<reference path="../../node_modules/typescript/lib/lib.es6.d.ts" />

// COMMON
import 'angular2-universal-polyfills/';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { NgClass, APP_BASE_HREF, Location } from '@angular/common';
import { provide, Component, OnDestroy, OnInit } from '@angular/core';
import { ROUTER_DIRECTIVES, ROUTER_PROVIDERS } from '@angular/router';
import { RouteConfig, Router } from '@angular/router-deprecated';

import { HTTP_PROVIDERS, Http } from '@angular/http';
import {TRANSLATE_PROVIDERS, TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';
import { CookieService, ANGULAR2_COOKIE_PROVIDERS } from 'angular2-cookie/core';

import 'reflect-metadata';
import 'zone.js/dist/zone';

// VIEWS
import { HomeComponent } from './views/home';
import { ContentsComponent } from './views/contents';
import { ContentComponent } from './views/content';
import { GenresComponent } from './views/genres';
import { GenreComponent } from './views/genre';
import { MerchandisingsComponent } from './views/merchandisings';
import { PersonsComponent } from './views/persons';
import { PersonComponent } from './views/person';
import { ShowcaseComponent } from './views/showcase';
import { ShowcasesComponent } from './views/showcases';

import { LoginComponent } from './views/login';

// MODALS
import { MessageModal } from './modals/message-modal';

// SERVICES
import { EventService } from './services/event-service';
import { GlobalService } from './services/global-service';
import { Oauth2Service } from './services/oauth-service';

@Component({
	selector: 'chili-dashboard',
	viewProviders: [HTTP_PROVIDERS],
	pipes: [ TranslatePipe ],
	templateUrl: 'templates/main.html',
	directives: [ ROUTER_DIRECTIVES, NgClass, MessageModal ]
})

@RouteConfig([
	{ path: '/', component: HomeComponent, name: 'Home', useAsDefault: true },
	{ path: '/contents/...', component: ContentsComponent, name: 'Contents' },
	{ path: '/content/:idContent', component: ContentComponent, name: 'Content' },
	{ path: '/genres/...', component: GenresComponent, name: 'Genres' },
	{ path: '/genre/:idGenre', component: GenreComponent, name: 'Genre' },
    { path: '/merchandisings', component: MerchandisingsComponent, name: 'Merchandisings' },
    { path: '/persons', component: PersonsComponent, name: 'Persons' },
	{ path: '/person/:idPerson', component: PersonComponent, name: 'Person' },
    { path: '/showcases/...', component: ShowcasesComponent, name: 'Showcases' },
	{ path: '/showcase/:idShowcase', component: ShowcaseComponent, name: 'Showcase' },
	{ path: '/login', component: LoginComponent, name: 'Login' },
	{ path: '/**', redirectTo: ['Home'] }
])

export class ChiliDashboard implements OnInit, OnDestroy {

	public constructor(private _router:Router, private _location:Location, private _translate:TranslateService, private _cookieService:CookieService, public globalService:GlobalService) {
		var userLang = navigator['language'].split('-')[0];

		console.log('ChiliDashboard.constructor');

		// Configuriamo la lingua
		userLang = /(de|en|it|pl)/gi.test(userLang) ? userLang : 'en';
		_translate.setDefaultLang('en');
		_translate.use(userLang);

		this._router.subscribe((path) => this.onStateChanged(path));
	}

	ngOnInit():void {

	}

	onStateChanged(path:string):void {
		var routeName = this._router.currentInstruction.component.routeName;
		//this.globalService.changeSection(routeName.toLowerCase());
	}

	getLinkStyle(path):boolean {
		if(path === this._location.path()){
			return true;
		} else if(path.length > 0){
			return this._location.path().indexOf(path) > -1;
		}
	}

	isLogged(): boolean {
		return (this._cookieService.get('chili_authorization') !== null && typeof this._cookieService.get('chili_authorization') !== 'undefined');
	}

	logout():void {
		this._cookieService.remove('chili_authorization');
		this._router.navigate([ 'Home', '{}' ]);
	}

	ngOnDestroy():void {
	}
}

bootstrap(ChiliDashboard, [
    HTTP_PROVIDERS,
    ROUTER_PROVIDERS,
	provide(TranslateLoader, {
		useFactory: (http: Http) => new TranslateStaticLoader(http, 'dev/i18n', '.json'),
		deps: [Http]
	}),
	// use TranslateService here, and not TRANSLATE_PROVIDERS (which will define a default TranslateStaticLoader)
	TranslateService,
    provide(APP_BASE_HREF, {useValue : '/'}),
    ANGULAR2_COOKIE_PROVIDERS,
    provide(CookieService, {useClass: CookieService}),
    GlobalService,
	EventService,
    Oauth2Service
]).then(
    success => console.log('ChiliDashboard bootstrapped!'),
    error => console.log(error)
);`

where is the problem? in bootstrap? 

thanks

**Comment by ocombe** [comment]
The problem is that you need to update ng2-translate, with beta 16 or 17 they changed the parameters for pipes, which means that old version of ng2-translate won't work.
