### ISSUE TITLE
[Question] ' in json

### ISSUE THREAD

**Issue by djavrell** [ocombe/ng2-translate#138]
Hello,
I use some " ' " in my json for the translation, but i've got an error on it in my browser.
I've tried to escape it with a \ but the error is always here

this is the error message
> SyntaxError: Unexpected token ' in JSON at position

Have you an idea or a tips to resolve this error ?

**Comment by beck24** [comment]
Only use double-quotes to format your json

**Comment by djavrell** [comment]
my json is formated like this
> { "var1": "some text" }

and it's work, but the probleme is in this case 

> { "var2": "some test, i'll try something" }

**Comment by beck24** [comment]
That's working for me, I think your problem might be elsewhere

**Comment by djavrell** [comment]
that strange it's work now

sorry for the inconvenience
