### ISSUE TITLE
Unable to pass translated string as param to translate pipe?

### ISSUE THREAD

**Issue by matthewrk** [ocombe/ng2-translate#141]
In the readme example you will find this:

> TranslatePipe
> 
> You can call the TranslatePipe with some optional parameters that will be transpolated into the translation for the given key.
> 
> Example:
> 
> <p>Say {{ 'HELLO' | translate:{value: "world"} }}</p>
> With the given translation: "HELLO": "hello {{value}}".

If we assume that the key Hello will be translated, and we also assume we have English and Spanish languages, this will result in the text:

Hello World
Hola World

The second of which is incorrect, the ideal end result would be Hola Mundo. A real world example of this is for example:

"{field} Is a required field" where I need {field} to be reference for English or referencia for Spanish.

How would you achieve this? I have tried piping another translate in as the param value but this obviously passes the resulting string to the original translate which then doesn't get updated on further language changes. e.g.

`{{ 'Forms.Validation.Required' | translate : { field: 'Users.Reference' | translate } }}`

Ideally id like to pass a key in as the param value rather than a string?

**Comment by JohnVT** [comment]
+1 for this

**Comment by ocombe** [comment]
This is the same feature requested here: https://github.com/ocombe/ng2-translate/issues/147
I'll close this one as a duplicate, you can follow in the other issue :)

**Comment by matthewrk** [comment]
Not sure if I'm understanding correctly but I don't think that solves the issue? I need to pass in a variable translation to a key. E.g. "{Reference} is a required field" where the word reference is variable and requires translation, and the rest of the string also requires translation.

From the look of the linked documentation that only allows you to give the same key different namespaces.
