### ISSUE TITLE
Extending Translations: setTranslation overrides no option to merge

### ISSUE THREAD

**Issue by pfrendo** [ocombe/ng2-translate#142]
Hi. I want my translations to be added in chunks (not once on bootstrap) and I want to use the setTranslate to add to them. Can this me changed to support such a thing? As I think that it is very beneficial.

**Example**
on Bootstrap ......

translate.setTranslation('en', {
    "HELLO": "hello {{value}}"
});

**on Login I want to add the following translations as they are added afterwards** 

translate.setTranslation('en', {
    "LoginSuccess": "welcome back {{value}}"
});

**I would like that the translation has the following**
{
    "HELLO": "hello {{value}}",
    "LoginSuccess": "welcome back {{value}}"
}

**It currently has**
{
    "LoginSuccess": "welcome back {{value}}"
}

as it is always **overrides** with the **latter**

**Comment by ocombe** [comment]
That would be an interesting feature for sure. It's not possible right now, but I'd love a PR with this.

**Comment by pfrendo** [comment]
I'll open a PR for this soon no worries :) !

**Comment by ocombe** [comment]
This has been implemented, closing the issue
