### ISSUE TITLE
How to test translation using Angular 2 Typescript 

### ISSUE THREAD

**Issue by venkataramkishore** [ocombe/ng2-translate#144]
I have implemented ng2-translate with latest npm "ng2-translate": "^2.1.0"
I have setup of angular2-seed project, implemented ng2-translate in it for my application. 
Now when i try to test translation. it gives error.

It would also be nice if you also have translation test cases.

Following is my sample test component.

``` js
import {
  describe,
  expect,
  it,
  inject,
  async,
  beforeEachProviders
} from '@angular/core/testing';
import { Component } from '@angular/core';
import { provide } from '@angular/core';
import { TestComponentBuilder } from '@angular/compiler/testing';
import { ROUTER_PROVIDERS } from '@angular/router';
import { AppComponent } from './app.component';
import { HTTP_PROVIDERS, XHRBackend, Http } from '@angular/http';
import { MockBackend } from '@angular/http/testing';
import { TranslateService, TranslateLoader, TranslateStaticLoader, TranslatePipe } from 'ng2-translate/ng2-translate';
import { getDOM } from '@angular/platform-browser/src/dom/dom_adapter';

export function main() {
  describe('App component example', () => {
    let tcb: TestComponentBuilder;
    //setup
    beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);
    //specs
    it('should render `Hello World!`', async(inject([TestComponentBuilder],
      (_tcb: TestComponentBuilder) => {
        tcb = _tcb;
        tcb.createAsync(TestComponent).then(fixture => {

          fixture.debugElement.componentInstance.isPanelActive = true;
          fixture.detectChanges(); //trigger change detection

          let element = fixture.debugElement.children[0].nativeElement;

          //Check for headings
          expect(getDOM().querySelector(element, '.headingXL').innerText).toEqual('Some text to test);
          expect(getDOM().querySelector(element, '.headingS').innerText).toEqual('Some text to test');
        })
          .catch(e => fail(e));
      })));
  });
  describe('App Component Tests', () => {
    //setup
    beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);

    it('shows see title and header',
      inject([TestComponentBuilder],
        (tcb: TestComponentBuilder) => {
          return tcb
            .createAsync(AppComponent)
            .then((fixture: any) => {
              //Enable the component first.
              fixture.debugElement.componentInstance.isPanelActive = true;
              fixture.detectChanges(); //trigger change detection
              let element = fixture.debugElement.children[0].nativeElement;

              //Check for headings
              expect(getDOM().querySelector(element, '.headingXL').textContent).toEqual('seed text');
              expect(getDOM().querySelector(element, '.headingS').innerText).toEqual('seed text);
            });
        }
      ));// End of it
  });//End of description
}//End of main

@Component({
  selector: 'test-app-cmp',
  directives: [AppComponent],
  providers: [TranslateService],
  pipes:[TranslatePipe],
  template: '<test-app></test-app>'
})
class TestComponent {
  constructor(translate: TranslateService) {
    var userLang = 'nl';   
    translate.setDefaultLang('nl');
    translate.use(userLang);
  }
}
```

ERROR Message::

```
  App Component Tests
    × shows see title and header
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    Failed: EXCEPTION: Error in :0:0
    ORIGINAL EXCEPTION: No provider for TranslateService!
    ERROR CONTEXT:
    [object Object]
    _rethrowWithContext
    create
    create
    _create
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:323:34
    onInvoke
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:322:43
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:216:50
    D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:571:61
    invokeTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:356:43
    onInvokeTask
    invokeTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:355:55
    runTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:256:58
    drainMicroTaskQueue@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js
:474:43
    F@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:12
217
    H@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:11
846
    when@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4
:15520
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:
16632
    _drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js
:4:3250
    drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:
4:1667
```

**Comment by ocombe** [comment]
Hello, the error message is pretty much self explanatory: you need to instantiate "TranslateService" with provide like you did with "TranslateLoader"

**Comment by venkataramkishore** [comment]
Hi 
I did as follows but still the same. Any thing else i am missing.

beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateService, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);

**Comment by ocombe** [comment]
You're providing a translate loader to the translate service, those are not the same things.

Try with:
```ts
beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      TranslateService,
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);
```

**Comment by venkataramkishore** [comment]
Hi I have modified as you suggested. Gud news is error is resolved.
But Bad news is not able to see expected tranlsation. I have modified as below my test case
import {
  describe,
  expect,
  it,
  inject,
  async,
  beforeEachProviders
} from '@angular/core/testing';
import { Component } from '@angular/core';
import { provide } from '@angular/core';
import { TestComponentBuilder } from '@angular/compiler/testing';
import { ROUTER_PROVIDERS } from '@angular/router';
import { AppComponent } from './app.component';
import { HTTP_PROVIDERS, XHRBackend, Http } from '@angular/http';
import { MockBackend } from '@angular/http/testing';
import { TranslateService, TranslateLoader, TranslateStaticLoader, TranslatePipe } from 'ng2-translate/ng2-translate';
import { getDOM } from '@angular/platform-browser/src/dom/dom_adapter';
import { ProductService } from '../product/shared/product.service';
export function main() {

  describe('App component example', () => {
    let tcb: TestComponentBuilder;

    //setup
    beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      TranslateService,
      ProductService,
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);

    //specs
    it('should render `Hello World!`', async(inject([TestComponentBuilder],
      (_tcb: TestComponentBuilder) => {
        tcb = _tcb;
        tcb.createAsync(TestComponent).then(fixture => {

          fixture.debugElement.componentInstance.isPanelActive = true;
          fixture.detectChanges(); //trigger change detection

          let element = fixture.debugElement.children[0].nativeElement;

          //Check for headings
              expect(getDOM().querySelector(element, '.headingXL').textContent).toEqual('some text in nl');
              expect(getDOM().querySelector(element, '.headingS').innerText).toEqual('some text in nl');
            });
        })
          .catch(e => fail(e));
      })));

  });

  describe('App Component Tests', () => {

    //setup
    beforeEachProviders(() => [
      TestComponentBuilder,
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      provide(TranslateLoader, {
        useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
        deps: [Http]
      }),
      TranslateService,
      ProductService,
      provide(XHRBackend, { useClass: MockBackend }),
      TestComponent
    ]);
    it('shows see title and header',
      inject([TestComponentBuilder],
        (tcb: TestComponentBuilder) => {
          return tcb
            .createAsync(TestComponent)
            .then((fixture: any) => {
              //Enable the component first.
              fixture.debugElement.componentInstance.isPanelActive = true;
              fixture.detectChanges(); //trigger change detection
              let element = fixture.debugElement.children[0].nativeElement;
              
              //Check for headings
              expect(getDOM().querySelector(element, '.headingXL').textContent).toEqual('some text in nl');
              expect(getDOM().querySelector(element, '.headingS').innerText).toEqual('some text in nl');
            });
        }
      ));// End of it
  });//End of description
}//End of main

@Component({
  selector: 'test-app-cmp',
  directives: [AppComponent],
  template: '<test-app></test-app>'
})
class TestComponent {
  constructor(translate: TranslateService) {   
        var userLang = 'nl'; //navigator.language.split('-')[0]; // use navigator lang if available
        translate.setDefaultLang('nl');        translate.use(userLang);
    }
}

Following is test case failure:
 App component example
    × should render `Hello World!`
      PhantomJS 2.1.1 (Windows 7 0.0.0)
    Expected '' to equal 'some text in nl'.
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:323:34
    onInvoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/async-test.js:76:50
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:322:43
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:216:50
    D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:571:61
    invokeTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:356:43
    runTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:256:58
    drainMicroTaskQueue@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:474:43
    F@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:12217
    H@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:11846
    when@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:15520
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:16632
    _drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:3250
    drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:1667
    Expected '' to equal 'some text in nl'.
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:323:34
    onInvoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/async-test.js:76:50
    invoke@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:322:43
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:216:50
    D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:571:61
    invokeTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:356:43
    runTask@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:256:58
    drainMicroTaskQueue@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/zone.js/dist/zone.js:474:43
    F@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:12217
    H@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:11846
    when@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:15520
    run@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:16632
    _drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:3250
    drain@D:/testingworkspace/oveasy-propositie-app-rc1/node_modules/systemjs/dist/system-polyfills.js:4:1667

**Comment by ocombe** [comment]
Take a look at the tests of this lib to know how to make your tests work: https://github.com/ocombe/ng2-translate/blob/master/tests/translate.service.spec.ts

If you want to test translations with the static translate loader you will have to mock the backend http call

**Comment by venkataramkishore** [comment]
What is the recommended way to implement translations. 
Do you have plan to adapt XLIFF for translations ? 
Angular 2 has support for XLIFF not yet release i guess. Which one to choose?

I am still working on your link to implement test case though.

**Comment by ocombe** [comment]
I don't think I'm gonna implement XLIFF, but if the angular team decides to document his i18n code and they include something like that, I might use their implementation.

**Comment by venkataramkishore** [comment]
Hi I have tried to see test case give in url, but it is beta version code i guess, can the test case be updated to rc1? I was wondering to load currentLoader property than useStaticloader() method.

**Comment by venkataramkishore** [comment]
i wrote test case but it worked with static loader but, I want to fetch the text from the ui and validate with translation. I am confused with lot of examples online. Is that possible for you to share some example with seed project.?

**Comment by happyvig** [comment]
Error that I received, while testing the translation :

_Error: No provider for TranslateService! (TranslatePipe -> TranslateService)_ 
About should log ngOnInit FAILED
        
_Error: No provider for TranslateService! (TranslatePipe -> TranslateService)_ 
in D:/user/angular2-project/config/spec-bundle.js (line 15467)

**Comment by ocombe** [comment]
Well it means that you have to provide the service @happyvig  :)

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
