### ISSUE TITLE
[Question] How to include html tags in your translation strings

### ISSUE THREAD

**Issue by ahayn465** [ocombe/ng2-translate#145]
I am loving the ng2-translate package, but I cannot seem to figure out how to include tags like <span> for formatting and <a> for including inline links. The only way I can make it work is by chunking out a sentence into a number of sections surrounding the tags. I have searched high and low for an example and would love some clarification on implementation.

Cheers :)

**Comment by koodikindral** [comment]
Same question :)

**Comment by ahayn465** [comment]
@knalli referred me to[ this documentation](https://angular-translate.github.io/docs/#/guide/05_using-translate-directive) for escaping html in translate strings which seems to indicate that it cannot be done without opening the app up to XSS attacks. 

Is there no way to easily include html tags in translate strings? The following simply creates an empty paragraph tag.

` "withSpan" : "Here is some text <span>with a span</span> for formatting" `
` <p translate="withSpan"></p>` // creates empty p tag

` {{ "withSpan" | translate }} ` // outputs markup as plain text

**Comment by Bouzmine** [comment]
Try using this
```js
<p [innerHtml]="{{ 'withSpan' | translate }}"></p>
```

**Comment by phiphou** [comment]
If we do 

`<p [innerHtml]="{{ 'withSpan' | translate }}"></p>`

we get an error:

`Parser Error: Got interpolation ({{}}) where expression was expected at column 0 in [{{ 'withSpan' | translate }}]`

Change to 

`<p [innerHTML]="'withSpan' | translate"></p>`

make it works ;)

**Comment by ocombe** [comment]
yes, if you're using [ ] to define a property, then don't use {{ }}

**Comment by Habeeb-mohamed** [comment]
@phiphou This binding not working in IE 11 :(

**Comment by El-Tee-E** [comment]
We have the same issue as @ocombe -  the innerhtml does not work in IE11:

shows a translated text but with the html as text, not rendered html. Also for some reason it shows the text twice. 

Ex.
```

"title": "Hello from this <strong>world</strong>"

{{'title' | translate}}

```
Result in IE 11: 

`Hello from this <strong>world</strong>Hello from this <strong>world</strong>
`

Expected result (and result in other - not crappy - browsers): 

Hello from this **world**

We are experiencing this bug in our ng4.1 project.
Worse part is that stats show IE 11 is 2nd most used browser by our users.

Will this issue be addressed  (or is there a workaround)?

**Comment by telmaco** [comment]
It would be much better looking and easier to have just the ‘i18n’ inside the html template on ionic as:
`<div i18n>Description of this page</div>`

than to have a horrible looking capslock tag as this thing:
`<div>{{DESCRIPTION_OF_THIS_PAGE | translate}}</div>`

Someone from the heavens bring the same angular solution to ionic pleaseee.
I don’t want to have to use ngx-translate ...the ‘i18n’ tag is so much easier to maintain

**Comment by EOussama** [comment]
> If we do
> 
> `<p [innerHtml]="{{ 'withSpan' | translate }}"></p>`
> 
> we get an error:
> 
> `Parser Error: Got interpolation ({{}}) where expression was expected at column 0 in [{{ 'withSpan' | translate }}]`
> 
> Change to
> 
> `<p [innerHTML]="'withSpan' | translate"></p>`
> 
> make it works ;)

But that discards any styling you had on it.

**Comment by andzejsw** [comment]
None of above answers is correct, cause doesn't work with translate params!!!

**Comment by deviancu** [comment]
@andzejsw this works for me using translate params

translate.json:
```json
"password": {
    "title": "Password for [<strong>{{username}}</strong>]"
}
```

component.html:
```html
<h2 [innerHTML]="'password.title' | translate: {username: account.login}"></h2>
```

**Comment by masonmark** [comment]
The answer by @deviancu worked for me, and it worked on Microsoft Internet Explorer 11 (version 11.535.18362.0).

Also, both the translation ID and translation parameters may be properties of the component/controller instead of being strings hardcoded in the template, e.g.:

```HTML
<span
  *ngIf="shouldShowFoo"
  [innerHTML]="fooTranslationId | translate: fooTranslationParameters"
  [class]="fooClassAttributeValue"
></span>
```

**Comment by nawaz-pasha** [comment]
I have a use case one level up of what is discussed here. I need to have a click event for a part of the translated text.

translate.json:
```
{
    "title": "Welcome aboard! <a (click)="callSomeMethod()">Click here</a> for more info"
}
```

component.html

```
<h2 [innerHTML]="'title' | translate"></h2>
```

component.ts

```
callSomeMethod() {
    // do something
}
```

**Comment by N4G1B4T0R** [comment]
> I have a use case one level up of what is discussed here. I need to have a click event for a part of the translated text.
> 
> translate.json:
> 
> ```
> {
>     "title": "Welcome aboard! <span (click)="callSomeMethod()">Click here</span> for more info"
> }
> ```
> 
> component.html
> 
> ```
> <h2 [innerHTML]="'title' | translate"></h2>
> ```
> 
> component.ts
> 
> ```
> callSomeMethod() {
>     // do something
> }
> ```

I figure out this issue like this:
here we got a translation and I added a class
`{
    "title": "Welcome aboard! <span class="some-name" (click)="callSomeMethod()">Click here</span> for more info"
}`

then in html I added a function 
`
<h2 click="callSomeMethod($event)" [innerHTML]="'title' | translate"></h2>
`
And in the component you can check a class via event

`
callSomeMethod(e) {
    if (e.target.classList.contains('some-name')) {
    // do something
    }
}
`

I guess, it will help you to solve your issue.

**Comment by skb0110** [comment]
> I have a use case one level up of what is discussed here. I need to have a click event for a part of the translated text.
> 
> translate.json:
> 
> ```
> {
>     "title": "Welcome aboard! <span (click)="callSomeMethod()">Click here</span> for more info"
> }
> ```
> 
> component.html
> 
> ```
> <h2 [innerHTML]="'title' | translate"></h2>
> ```
> 
> component.ts
> 
> ```
> callSomeMethod() {
>     // do something
> }
> ```

@nawaz-pasha , How did you solve this problem, Could you please help me on this. I am trying to implement the same thing.
Thanks.

**Comment by nawaz-pasha** [comment]
@skb0110 try the approach described by @N4G1B4T0R . It works perfectly.

**Comment by skb0110** [comment]
@nawaz-pasha and @N4G1B4T0R , the above given solution does not work for me, even I have the same structure and same case. The event is not triggering from the **click** method.
Could you please suggest. Thank in advance.

**Comment by xingruoxicic** [comment]
Translation file:
```json
{
      "id": "Test <a target=_blank href=https://www.loom.com>link</a>"
}
```
Angular component template:
```html
<p [innerHtml]="'id' | translate"></p>
```
Tested & works

**Comment by textheader** [comment]
https://hypertexter.space/questions/angular-bindings-expression-involving-html-elements
