### ISSUE TITLE
Update for RC.2

### ISSUE THREAD

**Issue by briananderson1222** [ocombe/ng2-translate#148]
The Angular team has released RC2 today! Can this library get updated for the latest version?

**Comment by ocombe** [comment]
I will do that tonight, in the mean time it works with rc2, it just prints a warning about unmet peer dependencies :)

**Comment by doxiaodong** [comment]
@ocombe , It can not change to 'en' until the 'en.json' is already loaded in RC2.  I work around it by double calling `translate.use('en')`. Please Fix it,  thx!

**Comment by spock123** [comment]
I had no issues using RC2... Of course there is a dependencies warning, but my language json files are loaded just fine.

**Comment by doxiaodong** [comment]
Mysite is [https://darlin.me](https://darlin.me),
I use as follow:
https://github.com/doxiaodong/darlin-angular2/blob/develop/src/main.browser.ts#L27
https://github.com/doxiaodong/darlin-angular2/blob/develop/src/app/footer/footer.component.ts#L64

**Comment by ocombe** [comment]
There was a bug when changing the lang that wouldn't update the translations of the translate pipe because the key didn't change. It was catch by the unit tests when I updated to RC2. Let me release a new version and you'll tell me if it fixes your problem.

**Comment by ocombe** [comment]
Awesome :)
