### ISSUE TITLE
[Question] Using static loader without HTTP

### ISSUE THREAD

**Issue by doudbanks** [ocombe/ng2-translate#156]
Hi @ocombe ,

I would like to use a static loader without using http is it possible ? I'm working in an application where I can't use it ...

Thanks.

**Comment by ocombe** [comment]
Yes, the latest version has removed the http dependency. As long as you don't use the current static loader and that you define your own (without http) then you should be ok !

**Comment by doudbanks** [comment]
Thanks but I can't use the last version cause i'm using angular 2 RC1 :). How can I define my own without http ?

Do you speak french ?

**Comment by ocombe** [comment]
Oui je parle français.
Le problème est que dans les versions précédentes $http était une dépendance du TranslateService (même si il ne servait à rien), donc il n'est pas possible d'utiliser une vieille version sans $http... A moins de remplacer $http par une classe inerte dans le bootstrap peut être.

Il faudrait configurer le bootstrap de ton application comme ça:

```ts
bootstrap(AppComponent, [
    HTTP_PROVIDERS,
    provide(TranslateLoader, {
        useFactory: () => new CustomLoader('assets/i18n', '.json')
    }),
    provide(TranslateService, {
        useFactory: (loader: TranslateLoader, http: FakeHttp) => new TranslateService(http, loader),
        deps: [TranslateLoader, FakeHttp]
    })
]);
```

Et à toi de définir une classe CustomLoader et une classe FakeHttp.

**Comment by doudbanks** [comment]
Super merci beaucoup je vais essayer de me débrouiller avec ça.

**Comment by doudbanks** [comment]
Salut @ocombe ,

Je regarde la version 2.2 et je vois toujours l'utilisation d'http. J'ai toujours cette erreur dans mon code:

Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js as "ng2-translate/ng2-translate" from http://localhost:4200/app/guichet-app.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js as "ng2-translate/ng2-translate" from http://localhost:4200/app/guichet-app.component.js

Je pensais

**Comment by doudbanks** [comment]
Salut Olivier,

Alors j'ai pris la dernière version du module. Selon toi, est-ce que je peux écrire un customLoader tout simple sans utiliser http pour aller chercher mes traductions ? Je ne sais pas trop comment m'y prendre sans utiliser HTTP (c'est une contrainte technique du projet sur lequel je travaille).

Merci beaucoup.

**Comment by ocombe** [comment]
Oui c'est tout à fait possible.
Tu peux d'ailleurs fournir les traductions manuellement et ignorer totalement le loader (mais bon le découplage des responsabilités c'est mieux)

**Comment by doudbanks** [comment]
D'accord,
 Je ne suis plus obligé de redéfinir tout ça ?

bootstrap(AppComponent, [
    provide(TranslateLoader, {
        useFactory: () => new CustomLoader('assets/i18n', '.json')
    }),
    provide(TranslateService, {
        useFactory: (loader: TranslateLoader, http: FakeHttp) => new TranslateService(http, loader),
        deps: [TranslateLoader, FakeHttp]
    })
]);

J'ai du mal a comprendre la marche a suivre car lorsque dans mon composant principal je déclare le TranslateService j'ai immédiatement des erreurs XHR pourtant je n'ai pas précisé que je voulais utiliser HTTP.

C,est dû au constructeur ?

export declare class TranslateStaticLoader implements TranslateLoader {
    private http;
    private prefix;
    private suffix;
    constructor(http: Http, prefix?: string, suffix?: string);
    /**
     * Gets the translations from the server
     * @param lang
     * @returns {any}
     */
    getTranslation(lang: string): Observable<any>;
}

**Comment by ocombe** [comment]
Si tu n'importes pas la classe qui nécessite http ça ne devrait pas poser de problèmes.
Quelles sont les erreurs xhr dont tu parles? Est ce qu'elles mentionnent vraiment $http ?

**Comment by doudbanks** [comment]
Alors j'importe ng2-translate/ng2-translate, jusque la tout va bien, et dès que je déclare mon TranslateService dans mes providers j'ai cette erreur 



`

GET http://localhost:4200/node_modules/ng2-translate/ng2-translate.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM9453:1fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1734leadingCommentAndMetaRegEx @ system.src.js:2759load.metadata.deps @ system.src.js:3333loader @ system.src.js:3600loader @ system.src.js:3985loader @ system.src.js:4448hookConstructor.meta @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js
	    at XMLHttpRequest.desc.set.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js as "ng2-translate/ng2-translate" from http://localhost:4200/app/guichet-app.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js
	    at XMLHttpRequest.desc.set.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/ng2-translate/ng2-translate.js as "ng2-translate/ng2-translate" from http://localhost:4200/app/guichet-app.component.js

`

**Comment by ocombe** [comment]
le message indique qu'il essaye de charger "http://localhost:4200/node_modules/ng2-translate/ng2-translate.js" mais n'y arrive pas, tu es sur du chemin? je doute que ton dossier node_modules soit en accès direct ?

**Comment by doudbanks** [comment]
Super j'ai corrigé tout ça je n'avais configuré correctement mon system-config et angular-cli-build. Je te remercie.

**Comment by ocombe** [comment]
Pas de problème :)

**Comment by doudbanks** [comment]
Donc maintenant je dois créer un custom loader ?

**Comment by ocombe** [comment]
Oui. Voici un exemple de loader custom que j'ai fait qui fonctionne server side sans $http:

```
import {TranslateLoader} from "ng2-translate/ng2-translate";
import {Observable} from "rxjs/Observable";
var fs = require('fs');

export class TranslateUniversalLoader implements TranslateLoader {
    constructor(private prefix: string = 'i18n', private suffix: string = '.json') {}

    /**
     * Gets the translations from the server
     * @param lang
     * @returns {any}
     */
    public getTranslation(lang: string): Observable<any> {
        return Observable.create(observer => {
            observer.next(JSON.parse(fs.readFileSync(`${this.prefix}/${lang}${this.suffix}`, 'utf8')));
            observer.complete();
        });
    }
}

```

Il se bootstrap comme ça:
```
{
    provide: TranslateLoader,
    useFactory: () => new TranslateUniversalLoader('assets/i18n', '.json')
}
```

**Comment by doudbanks** [comment]
Ok super merci beaucoup, le soucis c'est que côté client je ne peux pas communiquer avec le filesystem.

**Comment by ocombe** [comment]
Je sais bien, c'était juste un exemple de custom loader, à toi de voir comment tu vas charger tes données

**Comment by doudbanks** [comment]
Désolé, ça te paraît faisable ?

**Comment by ocombe** [comment]
De quoi ?

**Comment by doudbanks** [comment]
Charger mes fichiers sans passer côté server

**Comment by ocombe** [comment]
Je ne connais pas tes contraintes ni ton projet, donc je n'en ai aucune idée.
Si tu n'as pas accès à $http j'imagine que tu n'as pas xhr non plus, donc ça exclue de récupérer les assets, ce qui veut dire mettre les traductions dans une constante en dur, et les charger directement.

**Comment by doudbanks** [comment]
Arf' d'accord. J'étais tombé sur cet exemple sur un site:

`initializeTranslateServiceConfig() {
    var prefix = 'assets/i18n/';
    var suffix = '.json';
    this.translate.useStaticFilesLoader(prefix, suffix);
 
    var userLang = navigator.language.split('-')[0];
    userLang = /(de|en|hr)/gi.test(userLang) ? userLang : 'en';
 
    this.translate.setDefaultLang('en');
 
    this.translate.use(userLang);
  }`

Je suppose que le staticFilesLoader utilise http ?

**Comment by ocombe** [comment]
oui

**Comment by doudbanks** [comment]
Ok thanks.
