### ISSUE TITLE
zone.js throws 'Converting circular structure to JSON'

### ISSUE THREAD

**Issue by compitDanielos** [ocombe/ng2-translate#158]
Hi, I'm getting this error

```
zone.js:260
Uncaught TypeError: Converting circular structure to JSON

```

Any ideas what should I check first? 

Thanks.

**Comment by ocombe** [comment]
This is usually an error with JSON.stringify, which I don't use anymore, are you using an old version ?

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.

**Comment by ericgrover** [comment]
I am using v 8.0.0 and am getting the Converting circular structure to JSON error when I run the app using HTTPS.  If I run it as HTTP it works fine, but I get the error when I enable SSL.

**Comment by ericgrover** [comment]
I get the error when it is requesting the https://localhost:44395/assets/i18n/en.json file.
