### ISSUE TITLE
Allow default translation without using MissingTranslationHandler

### ISSUE THREAD

**Issue by webprofusion-chrisc** [ocombe/ng2-translate#160]
When a translation is missing it would be ideal if we could pass in a default fallback string to use if no translation is found (in current or default language). 

Suggested syntax:

``` html
{{'example.translation.key' | translate:{default:'Example Text'} }}
```

A specific use case for this is a dropdown list where the first few items (such as  item value=0 , text= [Unknown] are translated), but the other items are driven by an external data source and may or may not have a translation.

**Comment by ross-nordstrom** [comment]
I use this pattern a lot in the Angular 1 project I'm porting to Angular 2. It's really useful for gracefully defaulting values (e.g. if you want to support specific translations, but fallback to a general string)

```js
// field = 'name',  collection = 'animals'

let generalFieldTitle = new TranslatePipe()
  .transform(`fields.${field}`);
//=> 'Name'

let specificFieldTitle = new TranslatePipe()
  .transform(`${collection}.fields.${field}`, {default: generalFieldTitle});
//=> 'Animal Name', but it would be 'Name' if collection was 'foobars'
```

with translations like
```js
en = {
  fields: {
    name: 'Name'
  },
  animals: {
    // This may or may not exist
    name: 'Animal Name'
  }
}
```

**Comment by ocombe** [comment]
Wouldn't `{{('example.translation.key' | translate) || 'Example Text' }}` work ?

**Comment by webprofusion-chrisc** [comment]
That would be good! However if the translation key is not yet present in the default translation file that outputs as _example.translation.key_

**Comment by Jensiator** [comment]
Often you have an error response from the server. Typical Error{Code:111,Message:'yikes'}
In that case: ` {{ ('example.translation.key' | translate) || 'Example Text' }}`  doesn't work, becasue you might want to fallback to the server Message if the Code is not translated. I solved it by: 
html:
 `{{getTrans(theError)}}`
component method: 
 ```
 public getTrans(error) {
        let key = 'errors.' + error.ErrorCode;
        let translated = this.trans.instant(key);
        if (translated == key) {
            return error.Message;
        } else {
            return translated;
        }
    }
```
