### ISSUE TITLE
ng2-translate not found

### ISSUE THREAD

**Issue by estradamarkie** [ocombe/ng2-translate#167]
I've added ng2-translate to my system.config.js that comes with standard angular2 installation. ng2-translate is not being loaded.

`var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'ng2-translate':              'node_modules/ng2-translate',
    'rxjs':                       'node_modules/rxjs'
  };`

**Comment by estradamarkie** [comment]
Tried lots of things to try to fix  this thing and its either giving me 404 or annotation of undefined error.

**Comment by ocombe** [comment]
What is your systemjs config? Did you update it accordingly for ng2
translate (as explained in the readme)

Le lun. 11 juil. 2016 14:00, estradamarkie <notifications@github.com> a
écrit :

**Comment by estradamarkie** [comment]
Yeah I've updated my systemconfig.js, I'm using the standard system.config.js from angular installation guide I've added 'ng2-translate' : 'node_modules/ng2-translate' in the map section.

**Comment by ocombe** [comment]
and what is the request that gives you a 404 trying to load? do you have that url ?

**Comment by estradamarkie** [comment]
Yeah I'm getting http://localhost:3000/node_modules/ng2-translate/ng2-translate 404 (Not Found)

**Comment by ocombe** [comment]
Hmm I don't know then, I'm not using systemjs anymore, but it looks like a config problem, not a problem with the librairy.

**Comment by estradamarkie** [comment]
So everyone who is using systemjs will have the same problem? Well even the step "systemjs" in your readme doesn't work and that systemconfig was pretty straightforward.

**Comment by ocombe** [comment]
yes probably, if you find the right setup update this issue and I'll update the readme, otherwise it will have to wait until I can check the example repo and update it to the latest RC and version of systemjs

**Comment by mpavel** [comment]
I encountered the same issue today. I'm using the systemjs.config.js file from angular.io website. 

I had to do the following in this file:

```
var map = {
    ...
    'ng2-translate':              'node_modules/ng2-translate'
  };

  var packages = {
    ...
    'ng2-translate':              { defaultExtension: 'js' },
  };

// further down in the same file, they are being used like this
...
  var config = {
    map: map,
    packages: packages
  };
  System.config(config);
...
```

**Comment by estradamarkie** [comment]
@mpavel 
Hi, Yeah that's similar to my systemconf but still giving me an error.

**Comment by razvanmitre** [comment]
Isn't ng2-translate in the dist/vendor folder?

**Comment by Giola94** [comment]
faced to same issue? any idea how to fix it?

**Comment by Giola94** [comment]
put 'ng2-translate': 'node_modules/ng2-translate/bundles' in system.config.js in the map and 'ng2-translate' : { defaultExtension: 'js' } in packages

[working example of system.config.js](http://stackoverflow.com/a/39971916/3801087)

**Comment by 3du4** [comment]
worked for me as @Giola94 explained.

**Comment by jeebb** [comment]
I have to map **'ng2-translate': 'npm:ng2-translate/bundles/ng2-translate.umd.js'** for it to work.

**Comment by ocombe** [comment]
I'll add a note about systemjs in the readme

**Comment by AnnekathrinL** [comment]
hi. 

i have the same error. i adjusted everything you have recommended here . 
i have tried to set the mapping to 
- node_modules/ng2-translate
- node_modules/ng2-translate/bundles
- node_modules/ng2-translate/bundles/ng2-translate.umd.js
none of them worked.

i still get a 404 "Cannot GET /ng2-translate". I wonder, why angular is looking for it in the root-directory and not in the node_modules. 

do i need to adjust my package.json ? or anything else? 

any help would be appreciated.

**Comment by SamVerschueren** [comment]
@AnnekathrinL 

1. Care to share your config file?
2. Are you using the latest version of `ng2-translate`?
3. How are you importing `ng2-translate` in your source files?

**Comment by ocombe** [comment]
Have you defined the correct base tag in your index file ? `<base href="/">`

**Comment by AnnekathrinL** [comment]
hello. 
base href is set correctly.
i am using the latest version 

my config looks like this
`(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',
      'ng2-translate': 'npm:ng2-translate/bundles',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs':                       'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      },
      'ng2-translate':{
        defaultExtension: 'js'
      }
    }
  });
})(this);`

in my package.json i have added the following to the dependencies:
`"ng2-translate": "^4.2.0",`

my app.module.ts looks like that (in parts):
`import {TranslateModule}  from 'ng2-translate';
...
@NgModule({
  imports: [
    TranslateModule.forRoot(),
    ...`

and in my app.component.ts it looks like:
`import {TranslateService} from 'ng2-translate';`

**Comment by roddydairion** [comment]
Do you mind sharing how you fixed it please? I'm facing the same issue and can't figure out what I'm doing wrong.

Thank you.

**Comment by SamVerschueren** [comment]
@roddydairion Share your SystemJS config so we can have a look.

**Comment by AnnekathrinL** [comment]
@roddydairion it is pretty embarrassing to say that i simply included the wrong systemjs in my index.html as i was working on a test-project. :)

**Comment by roddydairion** [comment]
@SamVerschueren 

`(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'underscore':                 'node_modules/underscore/underscore.js',
    'ng2-translate':              'node_modules/ng2-translate/bundles'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-translate':              { defaultExtension: 'js' }
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  };
  System.config(config);
})(this);`

I've followed exactly the instruction but it fails no matter what I do.

**Comment by SamVerschueren** [comment]
Not sure if it changes anything, but try using `paths` and point to the `js` file instead of to the `bundles` directory.

Maybe changing your `ng2-translate` entry in `map` to `node_modules/ng2-translate/bundles/ng2-translate.umd.js` might be enough. Otherwise, try using this config.

```js
(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };
  var paths = {
    'underscore':                 'node_modules/underscore/underscore.js',
    'ng2-translate':              'node_modules/ng2-translate/bundles/ng2-translate.umd.js'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-translate':              { defaultExtension: 'js' }
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages,
    paths: paths
  };
  System.config(config);
})(this);
```

**Comment by roddydairion** [comment]
@SamVerschueren 
You my friend are a gem. Thank you very much.

**Comment by SamVerschueren** [comment]
@roddydairion Glad it worked :).
