### ISSUE TITLE
Load multiple translation files for one language

### ISSUE THREAD

**Issue by mrkosima** [ocombe/ng2-translate#169]
Hi!
Me application has run-time loaded modules.
Every such module has own localization file.
And the requirement is to load these translations only when module loads.

Unfortunately, it's impossible to extend `TranslateService` or `TranslateLoader` for this purpose, cause it has strong couple for `"one-file-per-lang"` logic. 

Loading translations and put values manually via `set(key: string, value: string, lang: string = this.currentLang).` could help. 

But I'd like to have some method, like `addPatch(path: string)` in translationService, that will load additional files.

What do you think about such feature?

Or there are different ways to resolve my needs?

**Comment by rglaspey** [comment]
I agree this would be useful. We have different scenario where we want to generate some translations and manually create some others. I guess we could write something to generate a final file based of our mutliple files... Any one have any existing solutions already?

**Comment by Inoverse** [comment]
Yep, would be nice. Like the PartialLoader in angular-translate.

**Comment by ocombe** [comment]
This will be possible once https://github.com/ocombe/ng2-translate/pull/161 has been merged (later today)
