### ISSUE TITLE
[ionic2] EXCEPTION: No provider for Http! (MyApp -> TranslateService -> Http)

### ISSUE THREAD

**Issue by lordgreg** [ocombe/ng2-translate#17]
Hi,

I'm having similar issue like someone else had with its Project. Mine was Ionic2 (2.0.0-alpha.49), ng2-translate (1.3.0) and angular2 (2.0.0-beta.0- yes, beta0 since ionic2 relies on it.

```
EXCEPTION: No provider for Http! (MyApp -> TranslateService -> Http)BrowserDomAdapter.logError @ browser_adapter.js:76BrowserDomAdapter.logGroup @ browser_adapter.js:86ExceptionHandler.call @ exception_handler.js:56(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430collection_1.StringMapWrapper.merge.onError @ ng_zone.js:325run @ zone-microtask.js:123(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$$internal$$tryCatch @ zone-microtask.js:1493lib$es6$promise$$internal$$invokeCallback @ zone-microtask.js:1505lib$es6$promise$$internal$$publish @ zone-microtask.js:1476(anonymous function) @ zone-microtask.js:225microtask @ ng_zone.js:383run @ zone-microtask.js:120(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$asap$$flush @ zone-microtask.js:1287
browser_adapter.js:76 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:76ExceptionHandler.call @ exception_handler.js:58(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430collection_1.StringMapWrapper.merge.onError @ ng_zone.js:325run @ zone-microtask.js:123(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$$internal$$tryCatch @ zone-microtask.js:1493lib$es6$promise$$internal$$invokeCallback @ zone-microtask.js:1505lib$es6$promise$$internal$$publish @ zone-microtask.js:1476(anonymous function) @ zone-microtask.js:225microtask @ ng_zone.js:383run @ zone-microtask.js:120(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$asap$$flush @ zone-microtask.js:1287
```

And another exception:

```
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (exceptions.js:15)
    at NoProviderError.AbstractProviderError [as constructor] (exceptions.js:38)
    at new NoProviderError (exceptions.js:74)
    at Injector._throwOrNull (injector.js:851)
    at Injector._getByKeyDefault (injector.js:902)
    at Injector._getByKey (injector.js:842)
    at Injector._getByDependency (injector.js:828)
    at Injector._instantiate (injector.js:720)
    at Injector._instantiateProvider (injector.js:711)
    at Injector._new (injector.js:700)BrowserDomAdapter.logError @ browser_adapter.js:76ExceptionHandler.call @ exception_handler.js:59(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430collection_1.StringMapWrapper.merge.onError @ ng_zone.js:325run @ zone-microtask.js:123(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$$internal$$tryCatch @ zone-microtask.js:1493lib$es6$promise$$internal$$invokeCallback @ zone-microtask.js:1505lib$es6$promise$$internal$$publish @ zone-microtask.js:1476(anonymous function) @ zone-microtask.js:225microtask @ ng_zone.js:383run @ zone-microtask.js:120(anonymous function) @ ng_zone.js:343zoneBoundFn @ zone-microtask.js:93lib$es6$promise$asap$$flush @ zone-microtask.js:1287
```

I've injected ng2-translate as this:
```
import {HTTP_PROVIDERS} from 'angular2/http';
import {TranslateService} from 'ng2-translate/ng2-translate';
import {
  App,
  IonicApp,
  Platform,
  Config,
  NavController,
  NavParams
} from 'ionic/ionic';
import {News} from './pages/News/News';

@App({
  templateUrl: 'build/app.html',
  config: {},
  providers: [HTTP_PROVIDERS, TranslateService]

})

export class MyApp {
  constructor(
    platform: Platform,
    app: IonicApp,
    translate: TranslateService
  ) {
  ...
```

Help me out (if possible) :+1:

**Comment by ocombe** [comment]
Hmm could you make me a minimal plunkr with the problem please?

**Comment by lordgreg** [comment]
Hi @ocombe,

sadly, plunker doesn't have the support for alpha/beta version of ionic2. That's why I've created a simple project for you [here](https://github.com/lordgreg/ionic2-ngtranslate). To install:

1. git clone
2. npm install -g ionic@beta gulp
3. npm install
4. ionic serve

**Comment by ocombe** [comment]
Thanks a lot for your repository, this bug has been fixed in the latest version (1.3.1), you shouldn't have a problem like this anymore.
The main issue with ionic 2 is that you cannot use `bootstrap` to instantiate `HTTP_PROVIDERS`, but I used the injector and now it's all right !

**Comment by ocombe** [comment]
Hmm as a matter of fact I will revert this change. Using the injector to get HTTP_PROVIDERS is not the right solution.
The problems comes from the fact that ng2 translate uses beta 1 and ionic2 is still stuck at beta 0.
If you change the package.json version for ng2 translate to 1.2.4 (last version on beta0) then it will work.
By using a different version of angular 2, webpack will load 2 different instances of Angular 2, and the one that ng2 translate gets is not the same, which means that the app is not bootstrapped for ng2 translate and the injector is different.

The solution for you is to use ng-translate 1.2.4 until ionic 2 moves to angular 2 beta 1.

**Comment by lordgreg** [comment]
Firstly, thank you that you took your time and look up in this issue. As you said 1.3.1 was working. However, I thought it has something to do with angular2 versions. Thank you for replying this; hopefully, we'll get new version of Ionic2 out soon with the beta1 dependency of Angular2.

Best regards! :+1:

**Comment by ocombe** [comment]
You can use 1.3.1 but I think that you might run into trouble (and loading 2 versions of angular will double your file size!).
If you don't need the new features, you can stay on 1.2.4 until then.
By the way, there is a Translate service bundled into ionic 2.

**Comment by lordgreg** [comment]
Translate service will be taken out of Ionic2 (discussed with Mike Hartington from Ionic team yesterday). And, as far as I can tell... your ng2-translate is on its way to get the success of Pascal Precht's Translate for Angular1. Will move to 1.2.4 as per your advice :8ball:

**Comment by ocombe** [comment]
Hmm I know what I could do, I could change the dependency for ng2-translate from `"angular2": "~2.0.0-beta.1"` to `"angular2": "~2.0.0-beta.0"`, this way it would use the beta.0 for you (as defined in your package.json), and beta.1 for others. There was no breaking change in beta.1 for me.

**Comment by ocombe** [comment]
Ok you can try version 1.3.2, it should work for you !

**Comment by lordgreg** [comment]
@ocombe thank you. it works. :+1: 

You're doing awesome job, keep up the good work! :)

**Comment by ocombe** [comment]
I changed it to peerDependencies in 1.4.0, it should still work for you :)

**Comment by mebibou** [comment]
@lordgreg this is not directly related to this problem, but I'm not sure if I should log a bug for this and maybe you already have the solution: I also use ng2-translate in my ionic2 app, and since then the file `translate.parser.ts` gets picked up by ionic and appears under `build/js` in Chrome debbuger, and basically it makes debugging impossible because somehow every breakpoint that I try to set on `app.bundle.js` gives me a breakpoint at the end of the `translate.parser.ts` file, and I can't figure out why

**Comment by ocombe** [comment]
This looks like a problem of sourcemaps to me.

**Comment by lordgreg** [comment]
@mebibou why setting breakpoints in webpack created bundle? Enable sourcemaps and make breakpoints in original files. See the ticket [here](https://github.com/driftyco/ionic-cli/issues/744)

**Comment by mebibou** [comment]
@lordgreg oh thanks never saw this one :)

**Comment by Giegling** [comment]
I have same problem just like you @mebibou and that ticket didn't help me @lordgreg . Do you guys have any solution? Here's an [example](https://i.imgur.com/w2cMkpf.png). Thanks
