### ISSUE TITLE
Updating to angular RC4

### ISSUE THREAD

**Issue by doudbanks** [ocombe/ng2-translate#171]
I just updated to Angular RC4 and when I'm trying to run my app with angular-cli I have ti error : 

Unhandled Promise rejection: Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]

Do you guys could know where is it coming from ?

Thanks a lot.

**Comment by fuitattila** [comment]
+1

**Comment by seandsky** [comment]
from which version?

**Comment by seandsky** [comment]
from which version? I think your can ref [fuel-ui-cli-quickstart](https://github.com/FuelInteractive/fuel-ui-cli-quickstart)

**Comment by maciejzasada** [comment]
+1
Generated a blank project using angular-cli, got the same error after integrating ng2-translate.

**Comment by maciejzasada** [comment]
Ok, for me it was something else. I only added bundles/ng2-translate to vendor. When I added the whole ng2-translate package, everything is working fine. Ignore my comment above then. No issue with a fresh project created using angular-cli and Angular 2 RC4.

**Comment by geoHeil** [comment]
I get npm ERR! peerinvalid Peer ng2-translate@2.2.2 wants @angular/core@^2.0.0-rc.3

**Comment by ocombe** [comment]
are you using an old npm version? < 3.x
because the peer dependencies ain't handled well before 3.x

**Comment by geoHeil** [comment]
Indeed I am using 2.15.8. but I thought that npm3 was still in beta.

**Comment by ocombe** [comment]
it's been at least 6 months since it's been stable :)
