### ISSUE TITLE
IE specific: Translate Pipe not working in Angular 2 RC4

### ISSUE THREAD

**Issue by debopamchanda** [ocombe/ng2-translate#174]
I am trying to use ng2-translate to show userName in different languages.

My LoginComponent looks like the one below:

```
import { Component } from '@angular/core';
import {TranslateService, TranslatePipe} from 'ng2-translate/ng2-translate';

@Component({
    selector: 'login-app',
    templateUrl: './app/components/html/login.component.html',
    pipes: [TranslatePipe]
})

export class LoginComponent {
    userName: string;

    constructor(private _translate: TranslateService) {

        this.initializeTranslateServiceConfig();
    }

    initializeTranslateServiceConfig() {
        var userLang = navigator.language || navigator.userLanguage;
        this._translate.use(userLang);
    }
}
```
My template login.component.html has a label which displays the userName

    <label for="userName">{{"User Name" | translate}}</label>
I have different .json files to support the translations.

Now I am changing the language settings of Chrome, Firefox and IE11. It works perfectly for Chrome and Firefox but not for IE11. :(

Can anybody please tell me what could be the problem and the possible solution?

Thanks,

Debopam

**Comment by ocombe** [comment]
Hello, I am not sure to understand what doesn't work: is this detecting the navigator current language ?

In which case if you want a true cross browsers detection function, you could use this:

```ts
// get the current UserLang
        var userLang = CookiesService.get('hmx-lang');
        if(!userLang) {
            if(typeof navigator['languages'] !== 'undefined' && navigator['languages'].length > 0) {
                userLang = navigator['languages'][0].indexOf('-') !== -1 || navigator['languages'].length < 2 ? navigator['languages'][0] : navigator['languages'][1];
            } else {
                userLang = navigator['language'] || navigator['browserLanguage'];
            }

            userLang = userLang && userLang.length ? userLang.split('-')[0] : ''; // use navigator lang if available
            userLang = /(fr|en)/gi.test(userLang) ? userLang : 'en';
}
```

I should probably add this to the translate service as a helper.
If that's not the problem, then let me know.
