### ISSUE TITLE
Can I use javascript logic in json files?

### ISSUE THREAD

**Issue by ddctd143** [ocombe/ng2-translate#176]
I have problem.

At example, I have this line in my json locale file. In angular1 it worked, but ng2-translate just prints this line as it is.
```
{                                
"floors": "{{ (floor !== null) ? ((floor > 0) ? floor : (floor === 0) ? \"semi-basement\" : \"basement\") : \"-\" }}/{{ (floors_total !== null) ? ((floors_total > 0) ? floors_total : (floors_total === 0) ? \"semi-basement\" : \"basement\") : \"-\" }}",
}
```

But if I use simple value output in json, like this: `"floors": "hello {{ floor }}",`
It works. So question is, is ng2-translate supporting logic that I described in first example, or no ?

If no, what I need to change so there would be support for that ?

Thanks.

**Comment by ocombe** [comment]
Hello !

No you cannot do that, it only supports variables (like you said), but it doesn't execute code. In Angular 1 there was a parser available that you could use (and that angular-translate used) for transpolations (that's the technical name when you use `{{ }}`), but there is nothing like that in Angular 2 *yet*.
They are talking about adding this, but for now I had to write my own parser and it's much simpler.

**Comment by ddctd143** [comment]
@ocombe 
Thanks for fast reply.
Thats bad, will need to implement temporary workaround.

What about pluralisation? I assume that it ins't implemented too ? :(

total-count: '{total, plural, one{дизайн} few{дизайна} many{дизайнов} other{дизайнов}}'

**Comment by ocombe** [comment]
no, it isn't available :)
