### ISSUE TITLE
Can't get available languages

### ISSUE THREAD

**Issue by cortopy** [ocombe/ng2-translate#177]
I'm trying to get available languages,  but the service returns undefined. I don't see a `setLangs()` method, so just wondering how they should be set.

``` javascript
constructor(public translate: TranslateService) {
    // use navigator lang if available
    var userLang = navigator.language.split("-")[0];
    userLang = /(es|en)/gi.test(userLang) ? userLang : "en";

    // this language will be used as a fallback when a translation isn't found in the current language
    translate.setDefaultLang("en");

    // the lang to use, if the lang isn't available, it will use the current loader to get them
    translate.use(userLang);

    var avLang = translate.getLangs();
    console.log("available languages: ", avLang);
  }
```

**Comment by h3xed** [comment]
getLangs method return currently loaded languages. I think that 'en' language isn't correctly loaded. Look up to browser network for xhr request with language json.

Few days ago i made pull request with setter and getter with available languages list:
https://github.com/ocombe/ng2-translate/pull/173

**Comment by cortopy** [comment]
I've investigated a bit further and I've found what it was. Basically, the ng2-translate service is not available until quite late in the component's lifecycle. I've tried logging with all the [hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) and to my surprise the translate service is not available until ngAfterContentChecked. At that moment I get a lot of logging (I guess because Angular 2 does double checking in dev mode).

So I'm using ngAfterViewInit, but that means the view will have to be rendered twice in every init!

I'm using the translate service as a singleton, and I suppose that's the reason why it's not available earlier on. Is there not a more performant way of having the translation service as a global singleton?

**Comment by cortopy** [comment]
GOT IT! The solution is an observer pattern. I'm now subscribing to onLangChange and that gives me the time to have my flow within onNgInit.

I was wondering if info about available languages, default, etc. could be made an observable too

**Comment by ocombe** [comment]
Well anything could be an observable, but you'd have to convince me for the necessity of this :)

**Comment by ocombe** [comment]
@cortopy you can observe the `defaultLangChange` event now as well.

**Comment by stevehealy** [comment]
For what it's worth, I had the same problem until I added "private"...

```
constructor(private translate: TranslateService) {
...
}
```

**Comment by HunteRoi** [comment]
> Well anything could be an observable, but you'd have to convince me for the necessity of this :)

What kind of answer is that? Especially when you have data that have to be loaded, everything _should be_ an observable! 
Getting the list of available langs as an observable would really serve this library.

**Comment by stephenasamoah** [comment]
> > Well anything could be an observable, but you'd have to convince me for the necessity of this :)
> 
> What kind of answer is that? Especially when you have data that have to be loaded, everything _should be_ an observable! Getting the list of available langs as an observable would really serve this library.

This is true. I've been trying to create a dropdown of available languages in my `assets/i18n` directory and haven't found how to do this yet. I have `en`, `it`, `ro` and it `getLangs()` only shows `en` in the log.
