### ISSUE TITLE
URL translations in the new angular 2 router (@angular/router 3.0.0-beta.2)

### ISSUE THREAD

**Issue by razvanmitre** [ocombe/ng2-translate#178]
Hello, 

Does anyone know if is possible to have the URLs translated somehow? I've read the question here https://github.com/ocombe/ng2-translate/issues/40, but in the new router, the routes are defined in a constant, and I don't think that this method works.

**Comment by jedmundo** [comment]
Hey,

Was also curious to know a possible solution for this.

**Comment by ocombe** [comment]
Hello, there is a new method that lets you update the router urls in the router rc1, you could use that to update the urls once the translations have been loaded.

**Comment by istiti** [comment]
@ocombe  what is this new method, can you do plnkr to demonstrate please

**Comment by ocombe** [comment]
I'm not sure, I haven't used it, but I think I saw someone talk about it on an issue on github (on angular/angular)

**Comment by istiti** [comment]
hm

**Comment by ocombe** [comment]
Hey guys, you can try https://github.com/Greentube/localize-router that was just released by @meeroslav :)

**Comment by fulls1z3** [comment]
Also check [@nglibs/i18n-router](https://github.com/nglibs/i18n-router), supports lazy routes as well.

**Comment by istiti** [comment]
@Ocombe merge it with official one

Cc @meeroslav
