### ISSUE TITLE
Feature: "instant" translateService method, e.g. synch translations

### ISSUE THREAD

**Issue by massimo-pacher-tw** [ocombe/ng2-translate#18]
Hi, I've just started using the library but I'm trying to use dynamic values (i.e. belonging to the component ).
I've checked the angular-translate library and I've seen it's possible pass in the filter a scope reference, but I don't want to pollute my component logic. 
So I created an helper method which takes in the key and the values object, but the translationService, at the moment, it always returns an Observer, which means you have to use the async pipe in the template.

``` 
{{ utils.getLocalisedString("MONETARY.NO_SENT_TITLE", { value: mycomponentValue}) }}
```
I've looked into angular-translate and I've refactored the code in 10 minutes for a basic "instant" method, which returns synchronously the interpolated string (in my app, I've made sure the language is always preloaded, so the sync approach fits my case).

How would you deal with this scenario?

Thanks,
M.

**Comment by ocombe** [comment]
That's what the "translate" pipe is for:
`{{ utils.getLocalisedString("MONETARY.NO_SENT_TITLE", { value: mycomponentValue}) }}` becomes `{{ "MONETARY.NO_SENT_TITLE" | translate:{ value: mycomponentValue}) }}`.

**Comment by massimo-pacher-tw** [comment]
Mmh, I had some problem with the syntax I guess, cause I've tried to pass in the reference but it didn't work! I got it working finally, thanks and sorry for the issue!

**Comment by ocombe** [comment]
no problem :)

**Comment by massimo-pacher-tw** [comment]
BTW, I think I've stupidly follow the syntax example with the quotes for the literal!Not sure if it's worth adding a line. 
Thanks again, M.

**Comment by ocombe** [comment]
Good point, I updated the readme to be more explicit
