### ISSUE TITLE
currentLang is undefined if it is called in app.ts

### ISSUE THREAD

**Issue by vong-xiv** [ocombe/ng2-translate#181]
here is a short version of my app.ts

```
@Component({
    template: '<ion-nav [root]="rootPage"></ion-nav>',
})
export class MyApp {
    rootPage: any = SubscrptPage;
    constructor(platform: Platform, private translator: TranslateService) {
        this.initTranslateService(translator);
        platform.ready().then(() => {
            StatusBar.styleDefault();
        });
        console.log(translator.currentLang); // undefined (expect 'en')
    }
    initTranslateService(translator: TranslateService) {
        translator.setDefaultLang('en');
        translator.use('en');
    }
}

ionicBootstrap(
    MyApp,
    [
        {
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'i18n/', '.json'),
            deps: [Http]
        },
        TranslateService
    ]
);
```

I should get 'en' when the `console.log(translator.currentLang); ` is called. But, I get UNDEFINED.
Interestingly, I get the correct value (i.e. 'en') from translator.currentLang in other pages.

My app environment:
+ Angular 2.0.0-rc.3
+ ionic 2.0.0-beta.10
+ Typescript 1.8.10
+ ng2-translate 2.2.2

**Comment by ocombe** [comment]
True, it should be set earlier when it is undefined

**Comment by Aljumaily** [comment]
Can I please know what the fix in this case? How can guarantee that ALL pages will work equivalently? I have the same problem and the weird part is that the same logic works on some pages and other pages encountered that `undefined` value.
