### ISSUE TITLE
problem with ng2-translate when I use XHRBackend

### ISSUE THREAD

**Issue by egornoveo** [ocombe/ng2-translate#183]
Hi everybody.
I have a problem when I use 
{ provide: XHRBackend, useClass: InMemoryBackendService } in my bootstrap
(with import { InMemoryBackendService, SEED_DATA} from 'angular2-in-memory-web-api')
and ng2-translate I get exception on "translate.use(userLang);"
"ORIGINAL EXCEPTION: Response with status: 404 Not Found for URL: null"
Whithout { provide: XHRBackend, useClass: InMemoryBackendService } everything works fine.
Can anybody explain how I can manage to it?
I have angular 2 RC4.
Thanks in advance

**Comment by ocombe** [comment]
If you use XHRBackend then you need to listen to connections and answer with the translations when asked for. You can take a look at the tests for the service: https://github.com/ocombe/ng2-translate/blob/master/tests/translate.service.spec.ts
