### ISSUE TITLE
Some characters are not displaying, ą, ę 

### ISSUE THREAD

**Issue by kbugala** [ocombe/ng2-translate#188]
Has anyone had similar issue with UTF8 encoding? The JSON file is UTF8 encoded and it seems OK, but on the angular app using ng2-translate some characters are missing , i.e. Polish language: ą,ę 

I'm using v. 1.1 please advise if upgrading will fix the problem

**Comment by ocombe** [comment]
it's not a problem with the library, there's probably an encoding problem somewhere, either on the server serving the files, or maybe the js code decoding them ?

**Comment by michalstepien** [comment]
I have no problem with polish characters.

**Comment by ocombe** [comment]
I'm closing this, if you can get a reproducible setup with the error, I'll reopen.
