### ISSUE TITLE
2.3.0: es6-shim typings not found

### ISSUE THREAD

**Issue by spock123** [ocombe/ng2-translate#189]
Sorry to bother,
- just installed the 2.3.0 version (with ngModule support, yeah!)..

When typechecking my application (webpack), I get the following issues about missing es6-shim typings:

`/Users/lrj/projects/iticket-angular2/node_modules/ng2-translate/src/translate.parser.d.ts:1:1 
    Cannot find type definition file for 'es6-shim'.
[default] /Users/lrj/projects/iticket-angular2/node_modules/ng2-translate/src/translate.service.d.ts:1:1 
    Cannot find type definition file for 'es6-shim'.`

I'm using core.js so I shouldn't have to use es6-shim also ( I tried, got conflicts obviously).

Anyone tried and have ideas how to resolve this?
Thanks

**Comment by ocombe** [comment]
yes, I'm working on it, I have the same problem, it should be resolved shortly, it's happening because I upgrade to TS 2.0 and it seem to output the reference to types in my .d.ts generated files (which was not the case before).
Working on it, I'll release a new version shortly

**Comment by spock123** [comment]
Hey man, no worries and no hurries, I just over-eager lmao.

I'm also using TS2.0, it's a blast!

Cheers

**Comment by ocombe** [comment]
ok 2.3.1 released, I reverted to typescript 1.8.10 until I can find the source of the issue :)
