### ISSUE TITLE
Upgrading to ng2-translate to use angular rc-5 causes breaking changes

### ISSUE THREAD

**Issue by Jacob-McKay** [ocombe/ng2-translate#190]
I have experienced peer dependency issues like:

npm ERR! peerinvalid The package @angular/core@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.4 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.4 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.4 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.4 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.4 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/router@3.0.0-beta.2 wants @angular/core@^2.0.0-rc.4
npm ERR! peerinvalid Peer ng2-translate@2.3.1 wants @angular/core@^2.0.0-rc.5

Sorry if the issue is just me, but it appears having your module upgrade to rc5 should've resulted in a 3.0.0 semver change, not a 2.x.x change

**Comment by ocombe** [comment]
Well it seems that you don't have angular 2 rc5 dependencies installed, which means that this version's peer dependencies are not satisfied.
I've only updated the minor version because the code in itself still works with rc4, I didn't want to release a new major version just yet as I have some big changes planed and I will release a new major soon.

Did you get this problem because you use the version number with a ^ at the beginning ?

**Comment by Jacob-McKay** [comment]
Yeah I'm depending on this: 
`    "ng2-translate": "^2.2.2",
`

And you're right I haven't upgraded to angular 2 rc5.

I'm trying to find the version of ng2-translate that depends on rc4 by looking on this repo now...

**Comment by ocombe** [comment]
The last version is 2.2.2 :)
Also you're probably using npm 2.x, because in 3.x the peer dependencies wouldn't cause an error, just a warning

**Comment by Jacob-McKay** [comment]
Correct again sir!  I'm on npm 2 because that was what came with node 4 LTS (I don't like to live on the bleeding edge all the time :P )

Peer dependencies are garbage so I'm considering updating to npm 3.  Thank you, looks like there is a resolution to my issue, I wouldn't fight ya if you closed this.

**Comment by ocombe** [comment]
ok :)
