### ISSUE TITLE
Issue with implementing for Ionic2 - es6 - Unexpected token (19:22) while parsing file

### ISSUE THREAD

**Issue by HamzaLJ** [ocombe/ng2-translate#191]
I receive `Unexpected token (19:22) while parsing file` which is basically this line: `useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),` 

After some debugging I realized that the issue raise because it's not a JavaScript es6 syntax and that's TypeScript. However, my app is built on the top of Ionic2 and JavaScript ES6.

Can you please share the way on how to implement that in JavaScript ES6 instead of TypeScript?

My code:

          @Component({
              template: '<ion-nav swipeBackEnabled="true" [root]="rootPage"></ion-nav>',
            config: {}, 
            providers: [
             {
               provide: TranslateLoader,
               useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
               deps: [Http]
             },
             TranslateService
           ],
           pipes: [TranslatePipe]
          })

**Comment by ocombe** [comment]
Did you find the correct ES6 syntax? You could post it here for future reference please ?

**Comment by HamzaLJ** [comment]
Sure,
I just changed this line:

 useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json')

to this:

 useFactory: (http) => new TranslateStaticLoader(http, 'assets/i18n', '.json')
