### ISSUE TITLE
Name error in translate.service.d.ts

### ISSUE THREAD

**Issue by xkill-9** [ocombe/ng2-translate#193]
TypeScript is finding an error on line 162 in the declaration of getBrowserLang()

`error TS2304: Cannot find name 'undefined'.
`

Apparently declaring undefined is not permitted on typescript version 1.8.10:
https://github.com/Microsoft/TypeScript/pull/5420

EDIT: I'm using ng2-translate@2.4.0 btw.

**Comment by ocombe** [comment]
Ah yes, it's a feature of typescript 2.0, but I thought that it would transpile to something generic... I'll change that, thanks for the report :)

**Comment by ddctd143** [comment]
I have same problem, should I upgrade to typescript 2.x or downgrade ng2-translate ?

**Comment by ocombe** [comment]
I just released a new version with a fix for this
