### ISSUE TITLE
Initialization with browser language

### ISSUE THREAD

**Issue by Viciouss** [ocombe/ng2-translate#194]
Hi,

In the initialization of my module I have to use `TranslateService.use("some_language")` to make it work. Just using `TranslateService.setDefaultLang("some_language")` is not enough. I would expect that the browser language is used if I don't add the call to `TranslateService.use` and if the browser language can't be determined it would then fall back to the default. Is it intended that I have to do the call explicitly?

If this is the case, I'd like to propose a change for the behaviour so it looks like this:

- use the browser language at initialization of the ng2-translate module
- if someone calls the `TranslateService.use` method then override the previously set language
- use the default in case there's nothing set or if the language can't be found

What do you think?

Cheers
Martin

**Comment by ocombe** [comment]
I don't like to make assumptions about how the users want it to work.
I added a helper to get the browser language in the last version, you can use this at init if you want to get the user lang, but I'd rather let this opt-in.
