### ISSUE TITLE
ng-translate wants Angular2 rc.5 but I use rc.4

### ISSUE THREAD

**Issue by nottinhill** [ocombe/ng2-translate#195]
ng2-translate@2.4.1 requires a peer of @angular/core@^2.0.0-rc.5

Which version would I need in order for ng2-translate to require angular rc-4 ?

**Comment by ocombe** [comment]
Version 2.2.2

Le lun. 15 août 2016 00:14, Stephan Kristyn <notifications@github.com> a
écrit :

**Comment by thegreenpizza** [comment]
@nottinhill I would recommend you follow the upgrade path to RC5. The changes are significant and the Angular team has stated that the RC5 API is very close to the final Angular 2 API.

**Comment by swiftyone** [comment]
Unfortunately some other frameworks still require RC4, in my case Ionic.
Hope to upgrade soon...

**Comment by hyde69x** [comment]
i guess u have a caret sign before the ng translate version in your package.json:
`"ng2-translate": "**^**2.2.2",`
 Remove the caret and reinstall the module

**Comment by gtzinos** [comment]
@ocombe  2.2.2 version return this error..

├── UNMET PEER DEPENDENCY @angular/common@^2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/compiler@^2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/http@^2.0.0-rc.3
└── ng2-translate@2.2.2 

npm WARN ng2-translate@2.2.2 requires a peer of @angular/common@^2.0.0-rc.3 but none was installed.
npm WARN ng2-translate@2.2.2 requires a peer of @angular/compiler@^2.0.0-rc.3 but none was installed.
npm WARN ng2-translate@2.2.2 requires a peer of @angular/core@^2.0.0-rc.3 but none was installed.
npm WARN ng2-translate@2.2.2 requires a peer of @angular/http@^2.0.0-rc.3 but none was installed.

**Comment by ocombe** [comment]
You should upgrade npm at the version 3, npm 2 does handle peer dependencies well...

**Comment by gtzinos** [comment]
My npm version is 3.10.5

**Comment by ocombe** [comment]
Did you install these dependencies ? @angular/common, @angular/compiler, @angular/core & @angular/http ?
Also I reduced the dependencies in 2.3

**Comment by gtzinos** [comment]
Yes my friend. but nothing..
