### ISSUE TITLE
Can't make it work with Ionic2 !

### ISSUE THREAD

**Issue by HamzaLJ** [ocombe/ng2-translate#196]
I've done the implementation as per the documentation onto my ionic2 app, but here is what I receive:

> Uncaught TypeError: core_1.NgModule is not a function

For the records, I am running the app under Ionic2 Beta 10, Angular R.C.3

**Comment by ocombe** [comment]
The current version only works with angular 2 RC5, that's why it doesn't work for you !
The last working version with RC3 should be 2.2.2 or 2.2.1

**Comment by HamzaLJ** [comment]
How can I install the version 2.2.2?

**Comment by ocombe** [comment]
With npm install ng2-translate@2.2.2

Le lun. 15 août 2016 20:31, Michael Larock <notifications@github.com> a
écrit :

**Comment by ocombe** [comment]
I just added an example folder with an ionic 2 example, hope this helps !
