### ISSUE TITLE
Please define another method for Instant string retrieval

### ISSUE THREAD

**Issue by lordgreg** [ocombe/ng2-translate#20]
angular-translate had such a good method which you could use in JS (not in templates) without getting a Promise back.

$translate.instant('key') would then return you your value of key in lang file.

where as current translate (from ng2-translate) always returns observable. There are few parts in my code, where I would just want to call translate.instant(key) without making a long .subscribe(data =>... part.

Could that kind of function be also implemented in ng2-translate?

Thank you for your work!

:+1:

**Comment by ocombe** [comment]
Yes, I can code that, but you have to be aware that if your translations haven't been loaded then "instant" would return the key (or undefined).

**Comment by lordgreg** [comment]
I am aware of that... that's why I'm trying to load my translation config part in @App constructor, and the translate.instant would I the call in @Page controllers/constructor/functions.

But... wouldn't something like this be enough to make this work?

```
  getInstant(key) {
    return this.translate.get(key).subscribe(data => {return data});
  }
```

**Comment by mebibou** [comment]
:+1: for this, I'm using ng2-translate in an Ionic app and often I need to get a translation for some services that expect to have a string and not an observable.

**Comment by mebibou** [comment]
FYI, I created my own class to do this:
````
import {Injectable} from 'angular2/core';
import {Parser, TranslateService} from 'ng2-translate/ng2-translate';

@Injectable()
export class TranslationService {
  private parser: Parser = new Parser();

  constructor(public translateService: TranslateService) {}

  public get(key: string|Array<string>, interpolateParams?: Object): string {
    if (!key) {
      throw new Error('Parameter "key" required');
    }

    var getParsedResult = (translations: any, key: any) => {
      var res: string;

      if (key instanceof Array) {
        let result: any = {};
        for (var k of key) {
            result[k] = getParsedResult(translations, k);
        }
        return result;
      }

      if (translations) {
        res = this.parser.interpolate(translations[key], interpolateParams);
      }

      if (typeof res === 'undefined' && this.translateService.defaultLang && this.translateService.defaultLang !== this.translateService.currentLang) {
        let translations: any = this.parser.flattenObject(this.translateService.translations[this.translateService.defaultLang]);
        res = this.parser.interpolate(translations[key], interpolateParams);
      }

      if (!res && this.translateService.missingTranslationHandler) {
        this.translateService.missingTranslationHandler.handle(key);
      }

      return res || key;
    };

    let translations: any;

    if (this.translateService.translations[this.translateService.currentLang]) {
      translations = this.parser.flattenObject(this.translateService.translations[this.translateService.currentLang]);
    }

    return getParsedResult(translations, key);
  }
}
````

**Comment by ocombe** [comment]
Nice thanks!

**Comment by ocombe** [comment]
This has been added in 1.8.0 !

**Comment by mebibou** [comment]
awesome thanks
