### ISSUE TITLE
Translate pipe not working in lazy-loaded module

### ISSUE THREAD

**Issue by MaelstromCdn** [ocombe/ng2-translate#202]
I'm using ng2-translate for language handling in an Angular 2 RC5 app I'm creating. The app has two feature modules, one lazy loaded and one eager loaded. TranslateModule is made available through a shared module. The problem is that the translate pipe works fine in the eager-loaded module but not the lazy-loaded one. To verify it has to do with the loading method I converted both to eager-loading and everything worked fine.

A plunk that demonstrates the issue can be found here: [Plunker](http://plnkr.co/edit/81Jsmy?p=preview).

The initial page is the eager-loaded one, hence why the strings look fine. Click Login and it will go to the lazy-loaded one where all strings are upper-case, i.e. not translated.

Thanks,
Jason

**Comment by MaelstromCdn** [comment]
Problem solved, info can be found on StackOverflow here: [StackOverflow post](http://stackoverflow.com/questions/38987013/ng2-translate-not-working-in-lazy-loaded-module).

Thanks,
Jason

**Comment by ocombe** [comment]
Thanks for providing the answer :)
