### ISSUE TITLE
ionic and ng2-translate

### ISSUE THREAD

**Issue by guysan** [ocombe/ng2-translate#204]
an error occurred when trying to implement ng2-translate with ionic2 - reason missmuch of angular version.

the error:
TypeScript error: C:/code/.../node_modules/ng2-translate/ng2-translate.d.ts(1,10): Error TS2305: Module "C:/code/../node_modules/@angular/core/index"
has no exported member 'ModuleWithProviders'

please provice in your md file how to get an older version of you module 

tnx

**Comment by ocombe** [comment]
Ionic 2 is still on angular 2 RC4, and ng2-translate requires RC5 (with the new ng modules).
You should fix the version of ng2-translate to 2.2.2 until you can upgrade angular

**Comment by yuriwally** [comment]
Perfect right! :dancers:

**Comment by ocombe** [comment]
I'll add a note to the readme tomorrow :)

**Comment by ocombe** [comment]
I just added an example folder with an ionic 2 example, hope this helps !
