### ISSUE TITLE
`TranslateModule.forRoot` should not be put in `SharedModule`

### ISSUE THREAD

**Issue by SamVerschueren** [ocombe/ng2-translate#209]
**I'm submitting a ...**

```
[ ] bug report
[ ] support request
[ ] feature request
[x] documentation improvement
```

**Current behavior**

Create a `SharedModule` that loads the translations with `TranslateModule.forRoot`.

``` ts
@NgModule({
    imports: [
        CommonModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'app/i18n', '.json'),
            deps: [Http]
        })
    ],
    exports: [
        CommonModule,
        TranslateModule
    ]
})
export class SharedModule {

    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule
        };
    }
}
```

Load this `SharedModule` inside a lazy loaded feature module and try to translate a value inside that feature module. You will notice that the keys are not being translated.

Now why is this the case? A lazy loaded feature module creates a child injector instance in which it bootstraps all the services again. We aren't at root-level anymore and shouldn't be calling `TranslateModule.forRoot`. This should only happen at the root (hence the name :)). More info in this topic could be found in the [documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#adding-services-with-_forroot_).

From the docs:

> Do not specify providers for modules that might be imported by a lazy loaded module.

**Expected/desired behavior**

The `TranslatePipe` should translate keys into values in lazy loaded feature modules.

**Solution?**

The `SharedModule` should not call `TranslateModule.forRoot` because this should happen at the `AppModule` level (at the root).
##### app.module.ts

``` ts
@NgModule({
    imports: [
        BrowserModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'app/common/i18n', '.json'),
            deps: [Http]
        }),
        SharedModule.forRoot()
    ],
    declarations: [
        AppComponent
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```
##### shared.module.ts

``` ts
@NgModule({
    imports: [
        CommonModule,
        TranslateModule
    ],
    exports: [
        CommonModule,
        TranslateModule
    ]
})
export class SharedModule {

    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule
        };
    }
}
```

**Please tell us about your environment:**
- **ng2-translate version:** 2.4.1
- **Angular version:** 2.0.0-rc.5
- **Browser:** all
- **Language:** probably all

**Comment by ocombe** [comment]
I think the simplest way to fix that would be to define translations as static, so that any translate service would have access to them. The problem is that it would prevent some use cases with specific translations just for one view, but is it really necessary now that you can merge translations instead of replacing all of them ?

What do you think ?

**Comment by SamVerschueren** [comment]
I think the best way (and the Angular 2 way) is to just change the `ng2-translate` documentation and make sure people initialize (`TranslateModule.forRoot`) the module in the `AppModule`. It doesn't really makes sense to call `TranslateModule.forRoot` in every feature module, which aren't root modules.

So making them static would (probably) work, but I believe that isn't the preferred way of working with modules.

**Comment by ocombe** [comment]
True :)
I'll update the docs then

**Comment by thorsten** [comment]
Any note when you'll update the docs? My app is running, but my tests are not due to "The pipe 'translate' could not be found"

**Comment by bjornharvold** [comment]
Thanks for this! #helpful

**Comment by exedor** [comment]
I suspect this will be a common theme for module authors. Several have mentioned the "angular2 way" of doing things, but I don't see any complete suggestions of that and I just went through the this exercise with the ng2-bootstrap author(s). Initially their suggestion was to update their documentation to let everyone know they had to worry about knowing when to calll .forRoot() again but only on their lazy loaded modules since angular2 doesn't seem to give them the same singleton services, but that's poor design.

The *right* way to do this is to implement the .forChild method in the provided module and there determine if you have your service setup and instantiated and if not, reinitialize. Then app authors can do everything the angular2 way of calling .forRoot() in the app module and calling .forChild in the feature modules regardless of whether or not they are lazy loaded and it will "just work."

**Comment by neolanders** [comment]
Since I didn't found any plunker working with ngx-translate librairy and I also add some difficulties to manage to make it work with LoadChildren,
I've setup a way that work pretty well for me:

_I've created two SharedModules, (one for lazyLoading and one for the other part of my application)_

**SharedLazyModule for lazy loading content:**

```
@NgModule({
  imports: [
    HttpModule,
    CommonModule,
    TranslateModule.**forChild**({}),
  ],
  exports: [
    CommonModule,
    TranslateModule
  ]
})
export class SharedLazyModule {}
```


**SahredModule for App**

```
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: Http) {
   return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
    imports: [
      HttpModule,
      CommonModule,
      TranslateModule.**forRoot**({
           provide: TranslateLoader,
           useFactory: HttpLoaderFactory,
           deps: [Http],
         })
    ],
    exports: [
      CommonModule,
      TranslateModule
    ]
})
export class SharedModule {
    
     constructor(private translate: TranslateService) {
                  
        translate.addLangs(["en", "fr"]);
        translate.setDefaultLang('en');

        let browserLang = translate.getBrowserLang();
        translate.use(browserLang.match(/en|fr/) ? browserLang : 'en');
    }
}
```

See Plunker:
https://plnkr.co/LVmIuI1Xw9vFn0IuC2jW

**Comment by bobrosoft** [comment]
I was getting "Error: No provider for t" during AoT compilation and found out that was happening because I had
```
constructor(
   translate: TranslateService
  ) {
```
in my component, but in the same time pipes were working. I replaced direct injection of `TranslateService` with
```
constructor(
    protected injector: Injector
  ) {
```
and 
```
ngOnInit() {
    this.injector.get(TranslateService).get(...
```
in ngOnInit. Now it's working. I hope that will help to somebody. Still not sure why AoT build not working properly when you injecting directly, I think related to when `TranslateService` created/provided.

**Comment by morozenkomv** [comment]
Hi, here is my solution for shared translate module
`@NgModule({
    imports: [
        CommonModule,
        MatMenuModule,
        MatIconModule,
        TranslateModule
    ],
    declarations: [LanguageSwitcherComponent],
    exports: [
        LanguageSwitcherComponent,
        TranslateModule
    ]
})
export class LanguagesModule {
    static forRoot(): ModuleWithProviders {
        return {            
            ngModule: LanguagesModule,
            providers: [
                TranslateModule.forRoot({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    };

    static forChild(): ModuleWithProviders {
        return {
            ngModule: LanguagesModule,
            providers: [
                LanguagesService,
                TranslateModule.forChild({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    }
}`

**Comment by morozenkomv** [comment]
> @NgModule({
    imports: [
        CommonModule,
        MatMenuModule,
        MatIconModule,
        TranslateModule
    ],
    declarations: [LanguageSwitcherComponent],
    exports: [
        LanguageSwitcherComponent,
        TranslateModule
    ]
})
export class LanguagesModule {
    static forRoot(): ModuleWithProviders {
        return {            
            ngModule: LanguagesModule,
            providers: [
                TranslateModule.forRoot({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    };

    static forChild(): ModuleWithProviders {
        return {
            ngModule: LanguagesModule,
            providers: [
                LanguagesService,
                TranslateModule.forChild({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    }
}

**Comment by morozenkomv** [comment]
Here is my solution
`@NgModule({
    imports: [
        CommonModule,
        MatMenuModule,
        MatIconModule,
        TranslateModule
    ],
    declarations: [LanguageSwitcherComponent],
    exports: [
        LanguageSwitcherComponent,
        TranslateModule
    ]
})
export class LanguagesModule {
    static forRoot(): ModuleWithProviders {
        return {            
            ngModule: LanguagesModule,
            providers: [
                TranslateModule.forRoot({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    };

    static forChild(): ModuleWithProviders {
        return {
            ngModule: LanguagesModule,
            providers: [
                LanguagesService,
                TranslateModule.forChild({ loader: { provide: TranslateLoader, useClass: LanguageLoader } }).providers
            ]
        };
    }
}`

**Comment by pvkrijesh** [comment]
Hey,SamVerschueren
 The example is good but here the translation are coming from .app/common/i18n but in my case I have mutliple translation files based on the modules such as  app/common/i18n/home and app/common/i18n/feature . In this case how this will help me  ?

**Comment by ibnYusrat** [comment]
> **I'm submitting a ...**
> 
> ```
> [ ] bug report
> [ ] support request
> [ ] feature request
> [x] documentation improvement
> ```
> 
> **Current behavior**
> 
> Create a `SharedModule` that loads the translations with `TranslateModule.forRoot`.
> 
> ```ts
> @NgModule({
>     imports: [
>         CommonModule,
>         TranslateModule.forRoot({
>             provide: TranslateLoader,
>             useFactory: (http: Http) => new TranslateStaticLoader(http, 'app/i18n', '.json'),
>             deps: [Http]
>         })
>     ],
>     exports: [
>         CommonModule,
>         TranslateModule
>     ]
> })
> export class SharedModule {
> 
>     static forRoot(): ModuleWithProviders {
>         return {
>             ngModule: SharedModule
>         };
>     }
> }
> ```
> 
> Load this `SharedModule` inside a lazy loaded feature module and try to translate a value inside that feature module. You will notice that the keys are not being translated.
> 
> Now why is this the case? A lazy loaded feature module creates a child injector instance in which it bootstraps all the services again. We aren't at root-level anymore and shouldn't be calling `TranslateModule.forRoot`. This should only happen at the root (hence the name :)). More info in this topic could be found in the [documentation](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#adding-services-with-_forroot_).
> 
> From the docs:
> 
> > Do not specify providers for modules that might be imported by a lazy loaded module.
> 
> **Expected/desired behavior**
> 
> The `TranslatePipe` should translate keys into values in lazy loaded feature modules.
> 
> **Solution?**
> 
> The `SharedModule` should not call `TranslateModule.forRoot` because this should happen at the `AppModule` level (at the root).
> ##### app.module.ts
> 
> ```ts
> @NgModule({
>     imports: [
>         BrowserModule,
>         TranslateModule.forRoot({
>             provide: TranslateLoader,
>             useFactory: (http: Http) => new TranslateStaticLoader(http, 'app/common/i18n', '.json'),
>             deps: [Http]
>         }),
>         SharedModule.forRoot()
>     ],
>     declarations: [
>         AppComponent
>     ],
>     bootstrap: [AppComponent]
> })
> export class AppModule { }
> ```
> 
> ##### shared.module.ts
> 
> ```ts
> @NgModule({
>     imports: [
>         CommonModule,
>         TranslateModule
>     ],
>     exports: [
>         CommonModule,
>         TranslateModule
>     ]
> })
> export class SharedModule {
> 
>     static forRoot(): ModuleWithProviders {
>         return {
>             ngModule: SharedModule
>         };
>     }
> }
> ```
> 
> **Please tell us about your environment:**
> 
>     * **ng2-translate version:** 2.4.1
> 
>     * **Angular version:** 2.0.0-rc.5
> 
>     * **Browser:** all
> 
>     * **Language:** probably all

This solved such a big problem for me that had me banging my head against the wall for about 3 or 4 days.
