### ISSUE TITLE
SystemJS cant find ng2-translate when using the Angular 2 quickstart setup

### ISSUE THREAD

**Issue by fr3dm4n** [ocombe/ng2-translate#21]
Hey,
at first I like to say that I appreciate your affords. Until now I haven't found anything about i18n in Angular 2, even though they promised it as a feature. So: Thx!

I got a project, which uses pretty much the same setup, as in the Angular 2 quickstart tutorial.
I followed your install instructions, but SystemJS is not looking at the node_modules folder.
I expect to load ng2-translate from `/node_modules/ng2-translate/ng2-translate.js` but the browser is requesting `/ng2-translate/ng2-translate.js`

I made a repository, which reproduces the error https://github.com/fr3dm4n/ng2Quickstart-beta.0/tree/ng-translate

It may be my fault,but you could help other ng2-SystemJs rookies as well  ;)

**Comment by ocombe** [comment]
Hello,

you will probably have to add a map to your systemjs config in index.html, like this: https://github.com/ocombe/ng2-play/blob/ng2-translate/index.html#L26

**Comment by fr3dm4n** [comment]
Wow, U R fast!
I tried here: https://github.com/fr3dm4n/ng2Quickstart-beta.0/commit/d2ecc22721106d93d440771756c96e21f2e14694

But the result is the same, it didnt help

**Comment by fr3dm4n** [comment]
UH, i mixed it up.
I put the map at the wrong location and I had to add angular 2 to the map.
https://github.com/fr3dm4n/ng2Quickstart-beta.0/commit/92e1fdf6e6a4126d151875ca3ae85a9568904c20

Thx for your help. One last Question: Why do i need a map now an before angular was found without one?

**Comment by ocombe** [comment]
Because you include angular as a bundle file in index.html, and not angular2-translate (there is no bundle for the moment).
Any external lib that you will use without including the script tag in index.html will require a map as well (for example if you decide to include lodash).

**Comment by fr3dm4n** [comment]
Ah, I see! So probably its worth to take a look at the SystemJS bundler...

again: Thx, have a nice day

**Comment by ocombe** [comment]
No problem !
I would recommend using webpack with Angular 2, it's much better than just systemjs (but more complex, systemjs is better for beginners).
You can use my starter for example: https://github.com/ocombe/ng2-webpack

**Comment by clevegomes** [comment]
Dear ocombe
SystenJS is loading ng2-translate and rxjs files . But if i want to concat all files into one js files for production .How can i do that ? I tried gulp to concat all the files but it does not work . Can you  help me with this ? sorry i am new to system js and rxjs.

**Comment by ocombe** [comment]
You need to use the systemjs builder: https://github.com/systemjs/builder
