### ISSUE TITLE
TranslateStaticLoader prefix

### ISSUE THREAD

**Issue by AlexKhymenko** [ocombe/ng2-translate#210]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Cant add  file following pattern 'prefix/customName-suffix;
Only possible prefix/suffix-cuctomName;

**Expected/desired behavior**
Should add possibility to add files that have name a file current following pattern 'prefix/customName-suffix;

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Let user decide how to name files

**Please tell us about your environment:**
- **ng2-translate version:** 2.4.2
- **Angular version:** 2.0.0-rc.X
- **Browser:** [all ] 
- **Language:** [all]

**Comment by DethAriel** [comment]
Let me clarify that a bit. Right now, you can specify both a prefix and a suffix, which will result in the following URI:
```typescript
`${this.prefix}/${lang}${this.suffix}`
```

Are you requesting something like this
```typescript
`${this.prefix}${lang}${this.suffix}`
```
to be possible? Notice, that there's no `/` after prefix.

I think we can even make it a non-breaking change if we check for trailing slash in the given `prefix`.

**Comment by DethAriel** [comment]
For those of you following this in an email, I removed the "non-breaking" piece from my previous comment

**Comment by AlexKhymenko** [comment]
The problem was that you cant specify name like i18n/locale-en.json.
You can only specify i18n/en-locale.json
It's not a problem for me just want to know why restrict choosing name?

**Comment by ocombe** [comment]
That's true, but you can write your own loader based on the current loader, it's hard to satisfy everyone :)
I'm closing this for now, if you really need this in the core, then submit a PR with the change, thanks !
