### ISSUE TITLE
Issues with version 2.4.2

### ISSUE THREAD

**Issue by bsakweson** [ocombe/ng2-translate#212]
`[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request`

I am submitting this to inform you about a potential issue I am facing after your upgrade to version 2.4.2. I believe that upgrade made it dependent on @angula/core^2.0.0-rc.5 and @angula/http^2.0.0-rc.5 

If one decides to use angular version 2.0.0-rc one gets this warning 
`npm WARN ng2-translate@2.4.2 requires a peer of @angular/core@^2.0.0-rc.5 but none was installed. npm WARN ng2-translate@2.4.2 requires a peer of @angular/http@^2.0.0-rc.5 but none was installed.` 

I do undertand that is just a warning but it turns out that angular version 2.0.0-rc.5 is still very unstable and throws all kinds of errors. we are advised against using it until those bugs are fixed. When I try to use ng2-translate with angular version 2.0.0-rc.4. I get this error 

 `TypeScript error: /Users/bsakweson/dev/work/server/kaphamobile/node_modules/ng2-translate/ng2-translate.d.ts(1,10): Error TS2305: Module '"/Users/bsakweson/dev/work/server/kaphamobile/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.`

**Comment by ocombe** [comment]
Hello, as explained in the FAQ, the last compatible version with RC4 is 2.2.2
