### ISSUE TITLE
InMemoryBackendService not compatible?

### ISSUE THREAD

**Issue by dtiru** [ocombe/ng2-translate#213]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Following the official documentation and Loading/starting the InMemoryBackendService for testing and mock purposes breaks the translation module.

providers: [
    { provide: XHRBackend, useClass: InMemoryBackendService }, // in-mem server
    { provide: SEED_DATA, useClass: InMemoryDataService },     // in-mem server data
  ]

**Expected/desired behavior**
That the InMemoryBackendService can be ran simultanious with the ng2-translate module

**Reproduction of the problem**
I have added the InMemoryBackendService and there it starts breaking, i have also attached the project with the small changes to package, systemjs, module and the mock data.
[angular2-translate-inmemdbservice.zip](https://github.com/ocombe/ng2-translate/files/438872/angular2-translate-inmemdbservice.zip)

**What is the expected behavior?**
That the translations should work and load

**Please tell us about your environment:**
- **ng2-translate version:** 2.4.2
- **Angular version:** 2.0.0-rc.5
- **Browser:** all  
- **Language:**TypeScript 2.0

**Comment by ocombe** [comment]
I have never used the InMemoryBackendService, maybe @wardbell could help on this ?

**Comment by dtiru** [comment]
Just a clarifying note, its the file loading that is the problem, when entering the translations manually, there is not problem.

translate.setTranslation('en', {
      "WELCOME" : "Welcome",
      "MYPAGES" : "my pages",
      "BOO": "Boo"
    });

**Comment by ocombe** [comment]
Yes because the TranslateStaticLoader uses $http to load translations.
You could mock it, but it would not really fix the problem

**Comment by Mattes83** [comment]
Can you please elaborate a bit? I also need to get it working. 
Has anyone found a workaround?

**Comment by dtiru** [comment]
Mattes83, i have not had time pursuing this as I didn't find a solution and could continue working on other parts of our application and we now are moving to mock services that are not in the app. It would however be very nice to be able to do both internal and external requests.

**Comment by codemental** [comment]
Hi,

I have stumbled upon the same problem and have fixed it by writing my own **TranslateLoader** like this:
```typescript
export class TranslateLoaderMock implements TranslateLoader {

  constructor(private http: Http, private basePath: string) {
  }

  getTranslation(lang: string): Observable<any> {
    const languagePath: string = this.basePath + "/" + lang + ".json";
    return this.http.get(languagePath)
      .map(response => response.json().data[0]);//don't forget, it's an array
  }
}
```

and then using it in my **app.module.ts**
```typescript
imports: [HttpModule,
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateLoaderMock(http, '../i18n'),
      deps: [Http]
    }),
    //HTTP mock for the backend, MUST BE DECLARED AFTER the HttpModule
    InMemoryWebApiModule.forRoot(InMemoryBackendMock, { delay: 100 }),
```

**Note**: I have also tried _"assets/i18n"_ as **basePath** but that didn't work. I don't know why exactly.

In case you were wondering how the **InMemoryBackendMock** looks like:
```typescript
export class InMemoryBackendMock implements InMemoryDbService {
  createDb() {

    let ro = [{
      "HEADER": {
        "ADMIN": "Admin",
        "LOGOUT": "Logout"
      }
    }];

    return {ro};
  }
}
```

**ro** is the language code which I use in the **TranslateLoaderMock**

**Comment by codemental** [comment]
One thing to note here though. You don't need to create a mock for your translations. You can just set **passThruUnknownUrl: true** like this:
```typescript
InMemoryWebApiModule.forRoot(InMemoryBackendMock, {delay: 100, passThruUnknownUrl: true})
```

And the requests to get the translations will be allowed to go the the actual server.

**Comment by rbcouture-csiflex** [comment]
I'm having a similar problem with MockBackend.

I have created a shared module for ng2-translate and a fake backend provider as a global component (mockbe.ts).

As soon as I add the shared module to another module, all the http requests made by the service of this module are being sent directly over http (thus resulting in 404 error) instead of being captured by my fakebackendprovider.

I don't understand why I'm having this issue. MockBackend should intercepts all the http requests. The http requests ng2-translate make are intercepted but relayed to XHR since I haven't implemented anything to handle those (which is good), but the other modules aren't intercepted

I'm also fairly new to Angular so it might be something I have overlooked in my configuration.

**Comment by ocombe** [comment]
I think that you have to provide the mockbackend instead of http, you can do that in the config of the module

**Comment by rbcouture-csiflex** [comment]
thanks, I've just found a way to make it work. I have to add mockbackend as provider to my submodule. Might not be the best way but it works fine with ng2-translate, so it will do the job until the backend is developped

**Comment by ocombe** [comment]
Ok nice !
Can you post the solution here for other people who have the same problem ?

**Comment by rbcouture-csiflex** [comment]
I'm working with the angular2 dashboard provided by akveo (ng2-admin)

so the project structure goes like this

-src/
--|-app/
-----|-(std app files here)
-----|-mockbackend.ts
-----|-shared.module.ts
-----|-pages/
---------|-(page module, component...)
---------|-myfirstpage/
----------------|-(myfirstpage module, component...)

shared.ts file contains the ng-2translate module. I import the shared module in myfirstpage module (and everyother module that needs translation service)

mockbackend.ts is a fake backend provider taken from this example:
[http://jasonwatmore.com/post/2016/09/29/angular-2-user-registration-and-login-example-tutorial](url)

So all the http requests from any module are handled by this file.

Now in each page module, I have to import the SharedModule and provide the MockBackend like this:
`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgaModule } from '../../theme/nga.module';

import { Login } from './login.component';
import { routing } from './login.routing';

import { SharedModule } from '../../shared/shared.module';

/////// Mock Http API ///////
import { fakeBackendProvider } from '../../mockbe';
import { MockBackend, MockConnection } from '@angular/http/testing';
import { BaseRequestOptions } from '@angular/http';
////////////////////////////

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    NgaModule,
    routing,
    SharedModule
  ],
  declarations: [
    Login
  ],
  providers: [
    /////// MockBackend //////
    fakeBackendProvider,
    MockBackend,
    BaseRequestOptions
    ////////////////////
  ]
})
export default class LoginModule { }`

**Comment by ocombe** [comment]
Cool thanks :)

**Comment by gunturi** [comment]
alternatively you can do below in you fakeBackend.ts file.. 
if (connection.request.url.indexOf('assets')>-1){
              connection.mockRespond(new Response(
                        new ResponseOptions({ status: 200 })
                    ));

            }
