### ISSUE TITLE
HTML classes support

### ISSUE THREAD

**Issue by KevinBulme** [ocombe/ng2-translate#215]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**

When I hade some HTML tags the tags are added in she string. For example if my translation string is `"This is <b>bold</b>"` the output in my HTML page would be exactly the same and not "this is <b>bold</b>".

**Expected/desired behavior**

I wondered if it was possible to add some HTML classes support. For example by adding a param in the translation function.

Thanks,

**Comment by ocombe** [comment]
You can already do that with innerHTML:

```html
<div [innerHTML]="{{ 'SOME_KEY' | translate }}"></div>
```

with:
```json
{
  "SOME_KEY": "This is <b>bold</b>"
}
```

**Comment by KevinBulme** [comment]
Thanks a lot and sorry !
