### ISSUE TITLE
Component-level `MissingTranslationHandler` does not work

### ISSUE THREAD

**Issue by DethAriel** [ocombe/ng2-translate#222]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
If you provide a custom `MissingTranslationHandler` at the component-level, then this component does not use it as expected.

**Expected/desired behavior**
The component-level `MissingTranslationHandler` provider must be honored.

**Reproduction of the problem**
Consider this code:

`src/app.component.ts`:

``` typescript
@Injectable()
export class MyMissingTranslationHandler implements MissingTranslationHandler {
  public handle(key: string) {
    return `custom missing translation for ${key}`;
  }
}

@Component({
  selector: 'my-app',
  template: `{{ 'MISSING_TRANSLATION' | translate }}`,
  providers: [{
    provide: MissingTranslationHandler,
    useClass: MyMissingTranslationHandler,
  }],
})
export class AppComponent {
  constructor(private translate: TranslateService) {
    translate.setDefaultLang('en');
    translate.use('en');
  }
}
```

`src/app.module.ts`

``` typescript
import {HttpModule} from "@angular/http";
import {BrowserModule} from "@angular/platform-browser";
import {NgModule} from "@angular/core";
import {TranslateModule} from "ng2-translate/ng2-translate";
import {AppComponent} from "./app.component";

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot()
    ],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```

Well, the `MyMissingTranslationHandler` is not the one that's used for the component in question, as seen in this [plunker](http://plnkr.co/edit/gtJkud1wDhq8VVjsMh6r?p=preview).

**Please tell us about your environment:**
- **ng2-translate version:** 2.4.3
- **Angular version:** 2.0.0-rc.6
- **Browser:** all
- **Language:** TypeScript 1.8.10

**Comment by ocombe** [comment]
if you do that, then you'll have to provide it to the TranslateService in the component as well. The way dependency injection works in Angular is that it asks for a dependency in the constructor, but once it's initialized you cannot get a new dependency. Even if you use the injector, you'd have to get this specific component injector in order to get this dependency.

So this is not something that I can do in the lib, it's up to you to provide a new instance of the service if you need it, but I personnally don't think that it's a good idea because the translations/lang state won't be shared with the rest of the application and it becomes a mess to handle.

**Comment by joewoodhouse** [comment]
The documentation does specifically say you can provide a MissingTranslationHandler at the component level. So are the documents incorrect?

**Comment by matteobortolazzo** [comment]
I know this question is old but I can be useful for others.

```typescript
constructor(
    private translateService: TranslateService,
    missingTranslationHandler: MyMissingTranslationHandler 
  ) {
    this.translateService.missingTranslationHandler = missingTranslationHandler;
}
```

This work on Component level.
