### ISSUE TITLE
404 (http://localhost:3000/traceur) after new systemjs configuration in rc.6

### ISSUE THREAD

**Issue by anshumansworld** [ocombe/ng2-translate#225]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
TranslateModule is not working

**Expected/desired behavior**
It should work

**Reproduction of the problem**
I suppose it's still not according to new declaration in `systemjs.config.js` because I am getting:

```
Error loading http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js/src/facade/lang as "@angular/core/src/facade/lang" from http://localhost:3000/node_modules/ng2-translate/src/translate.pipe.js
```

I have included `core` in `systemjs` as : `'@angular/core': 'npm:@angular/core/bundles/core.umd.js',`

Also tried by updating declaration of `core` in `map` like: 
```
'@angular/core': 'npm:@angular/core',
```
 and by adding in `packages` as:
```
'@angular/core': {
                main: './bundles/core.umd.js',
                defaultExtension: 'js'
            }
```
but then I got this: `Error loading http://localhost:3000/node_modules/@angular/core/src/facade/lang.js as "@angular/core/src/facade/lang" from http://localhost:3000/node_modules/ng2-translate/src/translate.pipe.js`

**What is the expected behavior?**
Transaltion should work according to new configuration of [systemjs](https://angular.io/docs/ts/latest/quickstart.html#!#add-config-files)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ng2-translate version:** 2.4.3

* **Angular version:** 2.0.0-rc.6

**Comment by ocombe** [comment]
I don't understand how it can still call facade on 2.4.3 because there is absolutely no reference to this in any source file now (you can search via github).
Are you sure that you correctly npm installed it ?

**Comment by anshumansworld** [comment]
Okay, let me try by cleaning it again.

**Comment by anshumansworld** [comment]
I still don't understand what was the problem, I have cleaned node_mdules earlier as well but this time it's working fine. I was struggling from Friday :( anyway thanks for your time!!

**Comment by ocombe** [comment]
No problem, glad you could fix this !

**Comment by aruns05** [comment]
@anshumansworld : I am also facing this issue. Can you please advise how you fixed it

**Comment by anshumansworld** [comment]
@aruns05 I deleted node_modules and run "npm install". You may try this.
