### ISSUE TITLE
Translate database values

### ISSUE THREAD

**Issue by Sn3b** [ocombe/ng2-translate#226]
I have a list of countries coming from the database, to be shown in a dropdown for when users enter their address.

Using ng2-translate, is there a way to translate them?

I'd like to be able to do something like the following:

    <select formControlName="country">
      <option *ngFor="let country of codesService.countries$ | async" value="{{country.code}}">{{ 'CODES.COUNTRIES.{country.code}' | translate }}</option>
    </select>

With translations in a json file like:

    "CODES": {
        "COUNTRIES": {
          "AF": "Afghanistan",
          "AX": "Aland Islands",
          "AL": "Albania",
          "DZ": "Algeria",
          "AS": "American Samoa",
          ...
        }
      }

But of course it doesn't work :(

Or should I have the translations in the database too and use `currentLang` to retrieve the entries in the desired language?

**Comment by ocombe** [comment]
it will be difficult with the pipe, but you can do it programmatically with the service in your component

**Comment by Sn3b** [comment]
Not sure how...

What would be your approach for such values coming from the database?

**Comment by ocombe** [comment]
You can do something like:
```ts
codesService.countries$.subscribe(country => {
     let codes = translate.instant('CODES.COUNTRIES')
     this.country = codes[country];
});
```

I'm using instant here, but you can use get as well if you're not sure that the translations have been loaded

**Comment by DethAriel** [comment]
I have my components do this:

```html
<select>
  <option *ngFor="let country of countries" value="{{country.code}}">
    {{ 'CODES.COUNTRIES.' + country.code | translate }}
  </option>
</select>
```
and it works like a charm

**Comment by Sn3b** [comment]
Thanks @DethAriel, like a charm indeed :)
