### ISSUE TITLE
Angular2 RC6: Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by woppa684** [ocombe/ng2-translate#228]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Using Angular2 RC6 I get the following error:

``` 
zone.min.js:1 Error: (SystemJS) Cannot read property 'forRoot' of undefined(…)
```
See plnkr below.

**Expected/desired behavior**
A working TranslateModule

**Reproduction of the problem**
Minimal reproduction:
http://plnkr.co/edit/BIqZZTdTBuGIBAQwPbx8?p=preview

**What is the expected behavior?**
It shouldn't give the error above

**Please tell us about your environment:**
Plnkr.co

* **ng2-translate version:** x.x.x
https://unpkg.com/ng2-translate/bundles/ng2-translate.js

* **Angular version:** 2.0.0-rc.6

**Comment by DethAriel** [comment]
Here's the [fixed plunker](http://plnkr.co/edit/UpzAONbg8tvoj3PuwkBD?p=preview).

I only changed one line in `config.js`:
```js
System.config({
  // ...
  map: {
    'ng2-translate': 'npm:ng2-translate',
    // previously it was:
    // 'ng2-translate/ng2-translate': 'npm:ng2-translate/bundles/ng2-translate.js',
  },
  // ...
});
```

**Comment by woppa684** [comment]
Yeah, figured it had to be something like that... But what is the bundle meant for then?

**Comment by DethAriel** [comment]
Dunno, @ocombe do you mind to chime in on that?

**Comment by ocombe** [comment]
Weeeell, I don't know, I've never used the bundle :D
I'm using webpack so I've never had to use it, if systemjs works without it now I might as well remove it

**Comment by woppa684** [comment]
Ok! That"s clear then... Thanks!
