### ISSUE TITLE
Missing Translation Handler

### ISSUE THREAD

**Issue by DanielSchuech** [ocombe/ng2-translate#23]
A MissingTranslationHandler can be set up in angular-translate while the config phase.

I would like to have something similar in ng2-translate. As I ve seen your code I would think that this would be no problem to be added. If you would accept that feature I could provide a PR.

Example Use Case:
The requested Key isnt available in the translation. In the dev mode of your application it would call a http get to a specific route. On the serverside you can add the not existing key to your translation file. So you can just use new keys and add the translations later without missing a key.

**Comment by ocombe** [comment]
That's a good idea! If you can do a PR, go for it :)

**Comment by ocombe** [comment]
Closing the issue since this has been merged.
