### ISSUE TITLE
Treat empty string as valid translations (at least conditionally)

### ISSUE THREAD

**Issue by DethAriel** [ocombe/ng2-translate#231]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
If translation yields empty string, the translation is considered missing.

**Expected/desired behavior**
Empty strings, should either be considered valid translations **always**, or with a conditional switch, like
```typescript
translateService.tolerateEmptyStrings();
```

**Reproduction of the problem**
See [this plunker](http://plnkr.co/edit/J9RscKq79uOqkx3UkPs5?p=preview)

**What is the motivation / use case for changing the behavior?**
Use case is pretty much described in #223 . When localizing links, this is essential. 

** Comments **
One could add a space there:
```json
{
  "SOME_KEY": " "
}
```
but this is error-prone as such kinda redundant whitespace can be lost when localization team does its job.

**Please tell us about your environment:**

* **ng2-translate version:** 2.4.3

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** all
 
* **Language:** all

**Comment by ocombe** [comment]
You're right, empty string shouldn't be an error ! Sorry about that, I think it's a regression

**Comment by ngehlert** [comment]
would you be willing to accept a PR that adds the suggested conditional switch?
I'd rather have empty values displayed with something like "[MISSING]: KEY" then just empty strings. At least this is the way I'm used to it with the old angular-gettext
