### ISSUE TITLE
Switching the language at runtime in service call in ng2-translate

### ISSUE THREAD

**Issue by RUPEDAHI** [ocombe/ng2-translate#234]
I have implemented ng2-translate in my ionic2 application. Our requirement is to get language code from server and change application language accordingly i.e setting language dynamically.

So i have written call in login page component constructor to get language code and in call back i am setting application language using self.translateService.use(response);

In login page component template url i.e in html page i am doing translation using pipe as follow

{{ 'KEY_LOGIN_LOGIN' | translate }}

This code is working fine. Application is change to language get in server response. however when i refresh page in browser Getting error in html file as follow
Expression has changed after it was checked. Previous value: '22'. Current value: '7'

In IOS as well this error causing trouble.

should not get error and because of this error whole change detection fail

I tried few workaround give in following link
http://www.allenhashkey.com/web-development/angular2/angular-2-expression-changed-after-it-has-been-checked-exception/

enableProdMode(); is working fine. but i feel it should work in dev mode as well
other work around is to have separated component to call server api and because this component is not having any translation it will not give  this issue.

is there any other way to resolve this error or load ionic view after service call get completed.

**Reproduction of the problem**
try to call api to get language code and then set language in ng2-translate
e.g.
this.Settings.getServerLocale()
        .timeout(1000, new Error('timeout exceeded'))
        .subscribe(
        response => {
            self.translateService.use(response);
        },
        error => {
        });

**Please tell us about your environment:**
- **ng2-translate version:** 2.2.2
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ocombe** [comment]
This problem happens when your binding change after the lifecycle hook "AfterViewInit".
Can you get the locale without an xhr request ? For example the server could set a cookie when you ask for index.html, and you read this cookie before bootstrap, which mean that you can set the language immediately. This would fix your problem

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
