### ISSUE TITLE
npm3 install ng2-translate@2.4.4 gives me a version without @Pipe

### ISSUE THREAD

**Issue by Waitak** [ocombe/ng2-translate#238]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

The version of ng2-translate installed when I use npm3 install has this for the TranslatePipe definition:

```
import { PipeTransform, EventEmitter, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { TranslateService, LangChangeEvent, TranslationChangeEvent } from './translate.service';
export declare class TranslatePipe implements PipeTransform, OnDestroy {
    private translate;
    private _ref;
...
```

Hence, there is no 'translate' pipe defined.

**Expected/desired behavior**

The version in this repository has this for TranslatePipe

```
import {PipeTransform, Pipe, Injectable, EventEmitter, OnDestroy, ChangeDetectorRef} from '@angular/core';
import {TranslateService, LangChangeEvent, TranslationChangeEvent} from './translate.service';

@Injectable()
@Pipe({
    name: 'translate',
    pure: false // required to update the value when the promise is resolved
})
export class TranslatePipe implements PipeTransform, OnDestroy {
    value: string = '';
    lastKey: string;
    lastParams: any[];
```

Why are there two versions of the same release, and what is the preferred way to get the correct one?

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

The pipe is not found without the \@Pipe definition

**Please tell us about your environment:**

Running Ubuntu 16.04 

* **ng2-translate version:** 2.4.4

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by ocombe** [comment]
You're trying to load the definition file (that ends with `.d.ts`).
This is just the typings, not the actual code, and it **will never work**, you're supposed to load the `.js` file, and typescript will read the type definitions from the `.d.ts`.

When you import from `ng2-translate/ng2-translate`, typescript will read the imports all by itself, you should never import from another path than that.

**Comment by Waitak** [comment]
That's exactly what I'm doing, and the pipe is not defined.

```
import { Component, Input, OnInit } from '@angular/core';
import { TranslateService, TranslatePipe } from 'ng2-translate/ng2-translate';

@Component({
    selector: 'home',
    template: `
<h2>{{'HOME.TITLE' | translate}}</h2>
`
})
export class HomeComponent {
    constructor(private translate: TranslateService) {
    }
}
```

Console:

```
The pipe 'translate' could not be found ("
<h2>[ERROR ->]{{'HOME.TITLE' | translate}}</h2>
"): HomeComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
The pipe 'translate' could not be found ("
<h2>[ERROR ->]{{'HOME.TITLE' | translate}}</h2>
"): HomeComponent@1:4
The pipe 'translate' could not be found ("
<h2>[ERROR ->]{{'HOME.TITLE' | translate}}</h2>
"): HomeComponent@1:4 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
The pipe 'translate' could not be found ("
<h2>[ERROR ->]{{'HOME.TITLE' | translate}}</h2>
"): HomeComponent@1:4

```

**Comment by ocombe** [comment]
Ah this has nothing to do with that :)
It's a problem with the module that imports it.

What's your module definition ?

**Comment by Waitak** [comment]
Module definition:

```
import { UIRouterModule } from "ui-router-ng2";
import { SharedModule } from "../shared.module";
import { HOME_STATES } from "./home.states";

/** The Home NgModule. */
@UIRouterModule({
  imports: [SharedModule],
  states: HOME_STATES
})
export class HomeModule { }
```

(Would you like to move this discussion to my second (hopefully better) question, or leave it here?)

**Comment by ocombe** [comment]
We can keep it here, what is in SharedModule ?

**Comment by Waitak** [comment]
```
import {NgModule} from "@angular/core";
import {HttpModule} from "@angular/http";
import {CommonModule} from "@angular/common";

/** MyCommon Module: Re-exports BrowserModule and HttpModule */
@NgModule({
  exports: [CommonModule, HttpModule],
})
export class SharedModule { }
```

(Par parenthèse, le français marcherait egalement bien comme langue commune...)

**Comment by ocombe** [comment]
Wait, are you importing the TranslateModule anywhere in your application ?!

**Comment by Waitak** [comment]
Yes, in app.module.ts:

```
@UIRouterModule({
    imports: [
        BrowserModule,
        HomeModule,
        TranslateModule.forRoot()
    ],
...
```

**Comment by Waitak** [comment]
NB: I am unable to pass a `pipes` parameter to the Component. I mentioned that in the second question I posted. Has that changed with recent RC versions of Angular2?

**Comment by ocombe** [comment]
Oui, pipes et directives a été enlevé des meta data des components, il faut utiliser les modules maintenant.

Bref, pour être sûr que ça marche bien, importe le translate module uniquement dans ton shared module, et exporte le.

```
import {NgModule} from "@angular/core";
import {HttpModule} from "@angular/http";
import {CommonModule} from "@angular/common";
import {TranslateModule} from "ng2-translate/ng2-translate";

/** MyCommon Module: Re-exports BrowserModule and HttpModule */
@NgModule({
  imports: [TranslateModule.forRoot()],
  exports: [CommonModule, HttpModule, TranslateModule],
})
export class SharedModule { }
```

**Comment by Waitak** [comment]
Ça y est! Merci bien pour les responses rapides et claires.
