### ISSUE TITLE
Interpolation requires a space inbetween curly braces - ie } }}

### ISSUE THREAD

**Issue by nevster** [ocombe/ng2-translate#240]
**I'm submitting a ...**
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
You need to put a space inbetween the ending braces - if you don't you get an error

This works:
{{'mykey' | translate:{someParam: 'aaa'} }}

This doesn't:
{{'mykey' | translate:{someParam: 'aaa'}}}

**Expected/desired behavior**
The second case should work

**Reproduction of the problem**

**What is the expected behavior?**
It should work without adding the extra space

**What is the motivation / use case for changing the behavior?**
Reduction of errors

**Please tell us about your environment:**

* **ng2-translate version:** 2.2.2

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by ocombe** [comment]
wow, if that is true then it's a bug in Angular, not ng2-translate :)

**Comment by nevster** [comment]
Yeah - a definite possibility.

**Comment by ocombe** [comment]
Ok I confirm the bug... could you submit this on angular/angular ? Because this is definitively not something that I can fix here
