### ISSUE TITLE
Loading translation from variable

### ISSUE THREAD

**Issue by egornoveo** [ocombe/ng2-translate#244]
Hi everybody.
Could someone help me please

Is it possible to load json object with translation from variable, not from file.json?

**Comment by ocombe** [comment]
yes, you can use `setTranslation`:

```ts
translate.setTranslation('en', {
    "HELLO": "hello {{value}}"
});
```

**Comment by egornoveo** [comment]
Thank you, Olivier!

**Comment by slinto** [comment]
Hi,
I have one problem, I load some translates from .json file throught TranslateStaticLoader.
But I can use setTranslation for some content too, but setTranslation dont work for me..

I use ionic2-rc-2

Is this bug or? :) 
Thanks.

**Comment by juanchavezlive** [comment]
Hello @ocombe... Is there any performance cons if we use the method 'setTranslation' instead of the normal load ?
