### ISSUE TITLE
unknown function bootstrap, incorrect order

### ISSUE THREAD

**Issue by MartinMuzatko** [ocombe/ng2-translate#25]
Hello there!

I just started out to develop with Angular2.
Currently I'm extending an existing project to implement ng2-translate and I just can't get it to work.

First of all, the method `bootstrap` does not exist. It doesn't get imported from any of your calls either. So.. I have no idea about it. More information on that would be appreciated,

Second - How can you use TranslateService before you import it? Thats not going to work AFAIK.

Any help to resolve this issue is very much appreciated.

```
import {Component, OnInit, Injectable} from 'angular2/core';
import {RouteConfig, Router, ROUTER_DIRECTIVES} from 'angular2/router';
import {FORM_PROVIDERS} from 'angular2/common';
import {HTTP_PROVIDERS} from 'angular2/http';
import {TranslateService, TranslatePipe} from 'ng2-translate/ng2-translate';

```

**Comment by ocombe** [comment]
Hello,

`bootstrap` is the native angular2 function that you have to call to start your application. I will update the readme to add the import for that (it's: `import {bootstrap} from 'angular2/platform/browser';`).

And then, what do you mean by "How can you use TranslateService before you import it" ?

**Comment by ocombe** [comment]
Ah yes I see what you mean, I updated the readme which was outdated anyway (wrong imports since beta 1).
The doc should be more clear for you now :)

**Comment by MartinMuzatko** [comment]
Thank you for the quick reply! Yes, I looked into the introduction and looked for it to find if I missed something in the imports.

Thank you!
