### ISSUE TITLE
I updated to Angular 2.0.1 and nothing seems to be broken

### ISSUE THREAD

**Issue by fbaldo31** [ocombe/ng2-translate#251]
**I'm submitting an information (not an issue)

**Current behavior**
I updated to Angular 2.0.1 and nothing seems to be broken

**What is the expected behavior?**
Update package.json ? do you want i test something ?

* **ng2-translate version:**2.5.0

* **Angular version:** 2.0.1
 
* **Browser:** Chrome
 
* **Language:**TypeScript 2.0.3

**Comment by ocombe** [comment]
Why do you want to change anything ? The peer dependencies are correct:
```
"peerDependencies": {
    "@angular/core": "~2.0.0",
    "@angular/http": "~2.0.0"
}
```

**Comment by MadDeveloper** [comment]
I updated to angular to 2.0.1 and nothing was broken indeed, but update ng2-translate to 3.0.0 has broken the systemjs loader.

**Comment by SamVerschueren** [comment]
I had the same issue here but if you point to the bundle in SystemJS, make sure you use the correct key.

```
paths: {
    'ng2-translate/ng2-translate': 'node_modules/ng2-translate/bundles/ng2-translate.js'
}
```

It's important you use `ng2-translate/ng2-translate`.

Another option is to just use `ng2-translate` but to make sure you import from `ng2-translate` instead.

```js
import { TranslateService } from 'ng2-translate`;
```

Does that work?

**Comment by GoranBlazevic** [comment]
I have the same problem, SystemJS reports an error "Unexpected token <" when loading module on require("ng2-translate/ng2-translate") inside compiled .js file.

**Comment by MadDeveloper** [comment]
Ok both solutions work thank you SamVerschueren, I put the alternative for people who did like this:

In your jspm config file:

`paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },`

`map: {
    'ng2-translate': 'npm:ng2-translate/bundles/ng2-translate.js'
  }`

and in your sources files:

`import { TranslateService } from 'ng2-translate'`

**Comment by ocombe** [comment]
Thanks, I need to update the docs

**Comment by ocombe** [comment]
Done: next time you can check out [the plunkr](http://plnkr.co/edit/btpW3l0jr5beJVjohy1Q?p=preview) which I'll keep updated
