### ISSUE TITLE
ng2-translate for stable version of angular2 without rc

### ISSUE THREAD

**Issue by suhastjs** [ocombe/ng2-translate#257]
**Current behavior**
i use following version of angular
 "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",

for this version, i get below error.
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.5
+-- UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.5
+-- angular-translate@2.12.1
`-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.20

**Expected/desired behavior**
Can you please tell me if the package is supported for latest version of angular?

**Please tell us about your environment:**
i use npm with webpack. 

* **ng2-translate version:** x.x.x
3.0.0

* **Angular version:** 2.0.0-rc.X
 2.0.0 with no rc's (latest version)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ocombe** [comment]
Hello, any version above 2.5.0 is compatible with angular 2.0.0 https://github.com/ocombe/ng2-translate/releases/tag/v2.5.0

The error says that you're using 2.12.1, you should update the lib
