### ISSUE TITLE
[3.0.0] Webpack example not working 

### ISSUE THREAD

**Issue by rbaumi** [ocombe/ng2-translate#258]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

> Uncaught TypeError: Cannot read property 'prototype' of undefined

**Expected/desired behavior**
to work out of the box

**Reproduction of the problem**
git clone https://github.com/ocombe/ng2-translate.git
cd ng2-translate/examples/webpack
npm install
npm start
watch console output...

**ng2-translate version:** 3.0.0

**Browser:** [all] 
don't think it's browser related

**Comment by ocombe** [comment]
What repository are you cloning ?

**Comment by julb** [comment]
Maybe due to the fact that the library isn't distributed in commonjs format ?

**Comment by ocombe** [comment]
yes I need to update the examples with the new umd format

**Comment by ocombe** [comment]
This has been updated, closing it now.
