### ISSUE TITLE
angular2-seed integration problem

### ISSUE THREAD

**Issue by sangecz** [ocombe/ng2-translate#259]
I have trouble integrating this lib with angular2-seed.

```
[x?] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
After initial tries I returned to the plunker sample and just "copy pasted" it in clean angular2-seed. Receiving this error in browser:  
`(index):47 Error: (SystemJS) require is not defined...`

How to solve this?

**Please tell us about your environment:**
- **ng2-translate version:** 3.0.0
- **Angular version:** 2.0.0
- **Browser:** [Chrome 53] 
- **Language:** TypeScript 2.0.2]

**Comment by karlhaas** [comment]
I had the same issue and was able to fix it by changing
```
import {TranslateLoader, TranslateStaticLoader, TranslateModule} from 'ng2-translate/ng2-translate';
```
to
```
import {TranslateLoader, TranslateStaticLoader, TranslateModule} from 'ng2-translate';
```

**Comment by ocombe** [comment]
Closing this old issue as @karlhaas provided the solution. Let me know if I should reopen it.
