### ISSUE TITLE
getTranslation call does not have fallback mechanism

### ISSUE THREAD

**Issue by shadow999** [ocombe/ng2-translate#26]
If call getTranslation for a language that does not have localized json file, there is no fallback mechanism to get the default language and it will throw angular 2 exception.
I also checked the fallback logic inside get by key function in source code. The fallback mechanism seems not correct as well. It assumes that the default language has been loaded which is not the case all the time. It probably should try to send a request to get it if it is not in cache.

**Comment by ocombe** [comment]
You can now use the [MissingTranslationHandler](https://github.com/ocombe/ng2-translate#missing-translation-handler) to handle these scenarii.
