### ISSUE TITLE
Bundle rename and minification

### ISSUE THREAD

**Issue by SamVerschueren** [ocombe/ng2-translate#264]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**

Bundle is named `ng2-translate.js`.

**Expected/desired behavior**

Rename the bundle to `ng2-translate.umd.js` and create a `ng2-translate.umd.min.js` to get more in line with Angular 2.

Let me know what you think.

**What is the motivation / use case for changing the behavior?**

To get more inline with Angular2

**Please tell us about your environment:**
- **ng2-translate version:** x.x.x
- **Angular version:** 2.0.0
- **Browser:** all
- **Language:** TypeScript 2.x

**Comment by ocombe** [comment]
yes, also the bundle should probably be git ignored (but not npm ignored), is there any point having it on github ?

**Comment by SamVerschueren** [comment]
> Is there any point having it on github ?

Not that I know of. It only adds extra noise to commits imo.

**Comment by ocombe** [comment]
I was thinking about it and I'm not sure how it would behave with the typings that reference ng2-translate and not ng2-translate.umd

**Comment by ocombe** [comment]
This has been fixed, closing the issue.
