### ISSUE TITLE
Loading JSON dynamic

### ISSUE THREAD

**Issue by smith64fx** [ocombe/ng2-translate#266]
Hi,
Is it possible to load the json dynamically e.g. from my backend?

Or do you support only static .json files?

I ask this because we write a CMS where the customer should be able to translate the strings straight from the backend.

Best Regards,
Michael!

**Comment by ocombe** [comment]
Hello,

the current static loader supports any route, you change the prefix/suffix to point to your backend, but it only works with get and fixed routes.

If you need something more elaborate, you should consider writing your own loader, it's really easy to do (there's a small example in the doc) and you'll be able to do anything you want.
