### ISSUE TITLE
Can't use ng2-translate with SystemJS without using transpiler

### ISSUE THREAD

**Issue by dhardtke** [ocombe/ng2-translate#267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When I try to use ng2-translate with SystemJS *without* TypeScript as transpiler (all my files exist in .js already, same for ng2-translate's files), I get: 

```
Error loading http://localhost:8080/traceur
Unable to load transpiler to transpile http://localhost:8080/node_modules/ng2-translate/ng2-translate.js
Error loading http://localhost:8080/node_modules/ng2-translate/ng2-translate.js as "ng2-translate/ng2-translate" from http://localhost:8080/app/components/structure/navbar.component.js
```

**Expected/desired behavior**
All should load properly and work fine.

**Reproduction of the problem**
http://plnkr.co/edit/rCvP6mktQcuVPcvSBFHd?p=preview
I just forked the current SystemJS example and compiled all .ts files into .js using the official TypeScript compiler. I then adjusted SystemJS' config.js.

**Please tell us about your environment:**

* **ng2-translate version:** 3.1.0

* **Angular version:** 2.0.1
 
* **Browser:** Firefox 49.0.1 (stable)
 
* **Language:** TypeScript 2.0.3

**Comment by MadDeveloper** [comment]
Have you looks [here](https://github.com/ocombe/ng2-translate/issues/251)?
This can help you

**Comment by dhardtke** [comment]
@MadDeveloper: Why did you remove your comment?

You were right, this is a duplicate of https://github.com/ocombe/ng2-translate/issues/251 and the proposed fix works.

**Comment by MadDeveloper** [comment]
I thought that after thinking it was off topic because of typescript transpiler
