### ISSUE TITLE
Unable to use under WKWebView

### ISSUE THREAD

**Issue by CoDanny** [ocombe/ng2-translate#268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**

When running it in an ionic app using the cordova-plugin-wkwebview-engine plugin which switches the rendering engine from UIWebWiew to WKWebView I get the following error:

XMLHttpRequest cannot load file:///Users/arroyo/Library/Developer/CoreSimulator/Devices/75D80D9A-1804-4F70-A65F-648A7DCDEE51/data/Containers/Bundle/Application/305DDE17-69E4-4CDA-B7AB-49C0CEED9F6B/AstroPrint.app/www/assets/i18n/config.json. Cross origin requests are only supported for HTTP.

**Expected/desired behavior**

The config.json can be read without using XMLHttpRequest.

**Reproduction of the problem**

**What is the expected behavior?**

The error does not happen.

**What is the motivation / use case for changing the behavior?**

Using WKWebView is much faster in iOS. Current my project can't migrate there because of this error.

**Please tell us about your environment:**

* **ng2-translate version:** 3.1.x

* **Angular version:** 2.0.0
 
* **Browser:** [ iOS 10 WKWebView ] 
 
* **Language:** [ TypeScript 2.0]

**Comment by CoDanny** [comment]
Would it be possible to use this plugin instead? Maybe detect if the code is running in a phonegap environment and pull from that to read the file.


https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html

**Comment by ocombe** [comment]
This is why I designed the possibility to write custom loaders.
It is not possible to take into account all use cases since angular 2 works on so many different environments.
So the solution is simple: write your own loader that loads the files as you wish :-)

**Comment by CoDanny** [comment]
My bad @ocombe. For some reason I didn't realize that it was an option. That's a great architecture and approach to solve this problem

**Comment by barocsi** [comment]
@ocombe what was your resolution?

**Comment by CoDanny** [comment]
I used[ this plugin](https://github.com/apache/cordova-plugin-file) and implemented a custom loader

```
export class CustomLoader implements TranslateLoader {
  constructor(
    private http: Http,
    private plat: Platform
  ) { }

  getTranslation(lang: string): Observable<any> {
    if (this.plat.is('cordova')) {
      let promise = new Promise((resolve, reject) => {
        File.readAsText(cordova.file.applicationDirectory, `www/assets/i18n/${lang}.json`)
          .then(
          data => resolve(JSON.parse(<string>data)),
          (err) => {
            console.error(err);
            reject(err);
          }
          );
      });

      return Observable.fromPromise(promise);
    } else {
      return this.http.get(`assets/i18n/${lang}.json`)
        .map((res: Response) => res.json());
    }
  }
}
```

**Comment by barocsi** [comment]
Very nice, thanks!

**Comment by beck24** [comment]
@CoDanny I don't suppose you have this working with ionic 3?  There's been some changes and this isn't working as-is, can't seem to get it working correctly

**Comment by CoDanny** [comment]
I actually went back to the standard setup using Ajax called as the ionic guys fixes the problem accessing local files on WKWebView

**Comment by beck24** [comment]
really? It's not working for me on the latest ionic, getting this exact error.  I ended up removing WKWebView last night just so I could move forward but I'd much rather have them both working :/

**Comment by HamzaLJ** [comment]
Same here, it does not while using WKWebView ! Please add its support !!

**Comment by SamVerschueren** [comment]
I don't think this is up to us to fix it. Open an issue in Ionic or WKWebView instead. Or try addinga CSP rule.

**Comment by CoDanny** [comment]
1) If you use the WKWebView plugin from the ionic fork, the default behavior from this software works: https://github.com/driftyco/cordova-plugin-wkwebview-engine
2) @SamVerschueren is right, you can create a custom loader using this plugin to read the files: https://github.com/apache/cordova-plugin-file

**Comment by beck24** [comment]
ok thanks, I wasn't aware there was an ionic fork.  Will give that try.

**Comment by luckylooke** [comment]
For Ionic 2 project there is another solution I have mentioned here https://github.com/ngx-translate/core/issues/280#issuecomment-310741710

**Comment by polfernandez** [comment]
I am having the same issue, with the new WkWebview from ionic. Any updates? Wkwebview-engine is not a solution

**Comment by carlgik4** [comment]
I google a lot and finally got the ngx-translate to work:
First, upgrade cordova and ionic cli to latest version

`xxx:Tabs u$ cordova -v
    7.1.0

xxx:Tabs u$ ionic -v
    3.16.0

xxx:Tabs u$ ionic info

cli packages: (/Users/xxx/NPM/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : ios 4.5.3
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 25.3.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v6.11.5
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Environment Variables:

    ANDROID_HOME : /Applications/Android/sdk

Misc:

    backend : pro`

create a brand new project 

    ionic start Tabs sidemenu
    cd Tabs
    npm install @ngx-translate/core @ngx-translate/http-loader --save
The new project will use wkwebview as default, and there are some error with the usage docs:
https://ionicframework.com/docs/developer-resources/ng2-translate/
we should use HttpClientModule instead of HttpModule
For the app.module.ts

    import { TranslateModule, TranslateLoader, TranslateService } from '@ngx-translate/core';
    import { TranslateHttpLoader } from '@ngx-translate/http-loader';
    import { HttpClientModule, HttpClient } from "@angular/common/http";

    export function createTranslateLoader(http: HttpClient) {
      return new TranslateHttpLoader(http, 'assets/i18n/', '.json');
    }

    @NgModule({
      declarations: [
        ...
      ],
      imports: [
        BrowserModule,
        HttpClientModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader,
            useFactory: (createTranslateLoader),
            deps: [HttpClient]
          }
        }),
        IonicModule.forRoot(MyApp),
      ],
      bootstrap: [IonicApp],
      entryComponents: [
        ...
      ],
      providers: [
        ...
        HttpClient,
        TranslateService,
        ...
      ]
    })
    export class AppModule {}

For app.component.ts

    import { TranslateService } from '@ngx-translate/core';

    export class MyApp {
      constructor(public platform: Platform, public splashScreen: SplashScreen,
        translate: TranslateService) {
        translate.setDefaultLang('en');
        let browserLang = translate.getBrowserLang();
        translate.use(browserLang.match(/en|zh/) ? browserLang : 'en');
      }
    }

After that, create i18n folder in src/assets
create en.json
    {
      "HELLO" : "hello"
    }

For page usage, you can use pipe 

    {{'HELLO' | translate}}

or manually:

    export class HomePage {
      constructor(public navCtrl: NavController,
        private translateService: TranslateService) {
          this.translateService.get('HELLO').subscribe(
            value => {
              // value is our translated string
              let alertTitle = value;
              console.log("translate alert title:" + alertTitle);
            }
          )
      }
    }

Hope you save your life with these code.

**Comment by larssn** [comment]
This plugin seemed to fix my issues: github.com/oracle/cordova-plugin-wkwebview-file-xhr

Basically it allows file:// paths in wkwebview as far as I can understand.

**Comment by yanglongji** [comment]
use remote resource instead and wait for fixes
