### ISSUE TITLE
Clarify which code belongs to which file

### ISSUE THREAD

**Issue by MartinMuzatko** [ocombe/ng2-translate#27]
Especially for newcomers, it is hard to tell if you have to put some of the snippets to a component or service.

Additionally - Is it possible to setup the service once and use it in components and subcomponents?

Please update the documentation.

Thanks in advance.

**Comment by DanielSchuech** [comment]
I´m not sure if you really have to do an enhancement here @ocombe 

I would think that is is more a problem of understanding how angular 2 works than how you have to use ng2-translate.

###### Is it possible to setup the service once and use it in components and subcomponents?
Services are singletons. They will be initialised once and every component that injects this service will get the same instance. Therefore you need to provide the service to your app. This can be done while the bootstrap process 
```js
bootstrap(AppComponent, [HeroService]);
```
more information about dependency injection [here](https://angular.io/docs/ts/latest/guide/dependency-injection.html)

The second way to provide a service is the hierarchical injector. There you can add a provider attribute to your component. Then you can inject your service in this component and lower level
```js
@Component({
  selector: 'hero-editor',
  providers: [RestoreService],
  ...
})
```

So the service exists just once. When you configure it one times then it is configured at all places were you inject the service!

###### put some of the snippets to a component or service:
The translate service needs to be configured before the usage. A service will be initialised when an component is loaded which injects the service. When you maybe inject your service on a very low level it could be too late and some of your translations will not be translated. So a service isn´t a good way to configure a TranslateService.

The service needs to be configured before the first usage of the translations(via pipe or service). So one opportunity would be to do it in your app component but you coud do it also on a lower level.

**Comment by ocombe** [comment]
That's nice @DanielSchuech, can I use this text for a quick FAQ ?

**Comment by DanielSchuech** [comment]
Yes ;)

**Comment by MartinMuzatko** [comment]
Thanks a lot for the information @DanielSchuech.

However, I think I found a bug then.
I did a setup of the `TranslateService` wirthin my app.ts
Setting up labels, etc.
I can use the labels anywhere via `TranslatePipe`, but if I want to make use of the `TranslateService` in another component, none of the settings persist.

```typescript
import {Component} from 'angular2/core';
import {SubTaskSet, SubTask} from '../../model/index';
import {Dialog} from '../../services/index';
import {AUI_NG_DIRECTIVES} from '../aui/index';
import {FORM_DIRECTIVES} from 'angular2/common';
import {TranslatePipe, TranslateService} from 'ng2-translate/ng2-translate';

@Component({
    directives: [...AUI_NG_DIRECTIVES],
    selector: 'editTaskSetDialog',
    pipes: [TranslatePipe],
    providers: [TranslateService],
    template: require('./edit-task-set-dialog.component.html')
})
export class EditTaskSetDialogComponent extends Dialog<SubTaskSet, SubTaskSet> {
    private taskSet: SubTaskSet;
    private newSubTaskSummary: string;

    constructor(private translate: TranslateService) {
        super();
        debugger;
       console.log(translate); //no properties persist.
    }

    initDialog(input: SubTaskSet) {
        console.log(this.translate.get('Untitled'));
        this.taskSet = input ? this.copyTaskSet(input) : new SubTaskSet(this.generateId(), 'Untitled');
    }
}

```

But the pipe works perfectly throughout all templates.

**Comment by DanielSchuech** [comment]
This isn´t a bug. Thats just how angular 2 works.

In your app.ts you correctly configured the translateService. Thats the reason why your pipe is gone work. But on the EditTaskSetDialogComponent your are providing a new TranslateService again. So through the fact of the hierarchical injector. You ve overwritten an the level of this component and every component with a lower level.

Just provide the Service ones. You are doing this in the app.ts. So dont do this again on a lower component. Remove **providers: [TranslateService],** and it should work

**Comment by ocombe** [comment]
yep, like @DanielSchuech every time you use the property "providers" on the component it uses `new` on the service, you create a `new TranslateService()` and that's why it isn't configured because each instance is independent.
If one of your parent component has already provided an instance for the service, then don't provide a new one and it will use the existing one.

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
