### ISSUE TITLE
Error loading ng2-translate.js in angular2 final release

### ISSUE THREAD

**Issue by MrHOY** [ocombe/ng2-translate#270]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Reproduction of the problem**
I have problem with ng2-translate lastest (3.0.1)
When I make example quickstart angular2 , then I import ng2-translate set up like README and I see error 

> **Failed to load resource: the server responded with a status of 404 (Not Found)**

I go to console log in index.html and see:
![error](https://cloud.githubusercontent.com/assets/20653706/19120219/5e1aee24-8b4c-11e6-8da2-41fe8f792984.jpg)

**Please tell us about your environment:**
- **ng2-translate version:** 3.0.1
- **Angular version:** 2.0.1 final release
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by yandreiy** [comment]
+1

**Comment by dhardtke** [comment]
Try to set config.paths in your SystemJS config to this object:
```javascript
paths:    {
    "ng2-translate/ng2-translate": "node_modules/ng2-translate/bundles/ng2-translate.js"
    }
```
See https://github.com/ocombe/ng2-translate/issues/251

**Comment by yoldar** [comment]
@dhardtke You saved my day!

**Comment by ivancalva** [comment]
I had the same error, thank you!

**Comment by MrHOY** [comment]
or you can set in SystemJS:

map: {
  'ng2-translate': 'npm:ng2-translate/bundles/ng2-translate.js'
}
packages: {
   'ng2-translate': {
        defaultExtension: 'js'
      }
}

It work for me! Thanks all!

**Comment by huyaxiong** [comment]
@dhardtke You saved my day either!

**Comment by ocombe** [comment]
You should just use `'ng2-translate': 'ng2-translate'`

**Comment by ocombe** [comment]
Or if you really need the full path, you can use `'ng2-translate': 'ng2-translate/bundles/index.js'`

**Comment by unsafePtr** [comment]
@ocombe Hi, i fixed it before five minutes:
In map:
> 'ng2-translate': 'npm:ng2-translate'
In packages:
> "ng2-translate": {
          main: "bundles/index.js",
          defaultExtension: "js"
      }

File was successfully uploaded, but error doesn't remain. Seems it was fired by another item/package.
Thanks for very fast answer 👍 Have a nice day.

**Comment by ortichon** [comment]
@unsafePtr 
Thanks, it works for me.

**Comment by unsafePtr** [comment]
@ortichon @ocombe,
Just understood now that it doesn't works for me. Traceur error continued, and it is fired by ng2-translate.
Helped to remove "catch" from System.import in index file

> System.import('appTS/main').catch(function(err){ console.error(err); });

Then i received much more helpful exception.
![error](https://cloud.githubusercontent.com/assets/22746240/19687757/69e8b9c4-9acf-11e6-928b-863d505ea94e.png)
And how to proceed now i didn't know. I already spend about 4 hours for this error and it is not resolved. Hope my experience was helpful for someone.

**Comment by ocombe** [comment]
If you get a traceur error, it's that it tries to load typescript files instead of compiled js files (and since you didn't install traceur it doesn't work).
I wonder if it's because of the type definition files in the bundles folder ? Maybe systemjs tries to load them at the same time ?

**Comment by unsafePtr** [comment]
@ocombe I have some installed package which name is ng2-ckeditor. SystemJs successfully upload its js file without any errors. The definition in my config for this package:
`'ng2-ckeditor': 'npm:ng2-ckeditor'` 
`      "ng2-ckeditor": {
          main: "lib/index.js",
          defaultExtension: "js",
      }`
The folder "lib" in ng2-ckeditor contains index.d.ts and index.js too.
May be for some reason SystemJs get confused and getting to transiple....

**Comment by unsafePtr** [comment]
Navigate [this](https://github.com/systemjs/systemjs/issues/969) for information. Just my another thought.

**Comment by unsafePtr** [comment]
Fixed it with changing import path in components from "ng2-translate/ng2-translate" to "ng2-translate".

**Comment by SamVerschueren** [comment]
Missed this thread. More information in here https://github.com/ocombe/ng2-translate/issues/219#issuecomment-256256623.

**Comment by dawud-do** [comment]
I get 

     26 10 2016 09:14:50.238:WARN [web-server]: 404: /base/node_modules/ng2-translate.js
     26 10 2016 09:14:50.286:WARN [web-server]: 404: /base/node_modules/lodash.js
     PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/ng2-translate.js
        Error loading http://localhost:9876/base/node_modules/ng2-translate.js as "ng2-translate" from http://localhost:9876/base/dist/dev/app/app.component.js'


when running karma test of an angular2 seed base. the suggestions in here haven't been working for me. for instance if I include path to bundles in my config.ts I just get a new error saying it can't find that. 
my karma baseURL is set to /base/ and my app.component.ts imports from 'ng2-translate'

any clue where I might want to look?

**Comment by ocombe** [comment]
@dawud-do please check the other issues, multiple solutions to these problems have been given.
