### ISSUE TITLE
Support single quotes for values in translate params

### ISSUE THREAD

**Issue by deepu105** [ocombe/ng2-translate#276]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
We are migrating from angular-i18n to ng2-translate
When we use `<div [innerHTML]="'HELLO' | translate:{ param: 'value'}"></div>` it throws an error from https://github.com/ocombe/ng2-translate/blob/master/src/translate.pipe.ts#L98

**Expected/desired behavior**

Since its not possible to pass double quotes from inside directives like above it would be nice if single quotes can be supported and handled similar to https://github.com/ocombe/ng2-translate/blob/master/src/translate.pipe.ts#L96
Currently the only way to do this is to use  `<div [innerHTML]="'HELLO' | translate:{ param: &quote;value&quote;}"></div>` which is not very nice for readability

**What is the motivation / use case for changing the behavior?**

Use the pipe from within directives

**Please tell us about your environment:**

* **ng2-translate version:** latest

* **Angular version:** 2.0.0 final
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by deepu105** [comment]
I can do a PR if required

**Comment by ocombe** [comment]
Hu, that's weird, I think it's more a bug than a feature.
A PR would be nice indeed :)
