### ISSUE TITLE
Did you provider an umd version, that I can load it by systemjs.

### ISSUE THREAD

**Issue by hstarorg** [ocombe/ng2-translate#284]

**Comment by ocombe** [comment]
Hello, the file `index.js` in the `bundles` directory (the only js file in it) is in umd format: https://unpkg.com/ng2-translate@3.1.3/bundles/index.js
It is referenced by the "main" property of the package.json file, so linking to ng2-translate will point directly to it

**Comment by hstarorg** [comment]
Got it, very thanks.

**Comment by hstarorg** [comment]
Also has a question.
```javascript
root["ng2-translate"] = factory(root["@angular/core"], root["@angular/http"], root["rxjs/Observable"], root["rxjs/add/observable/of"], root["rxjs/add/operator/map"], root["rxjs/add/operator/merge"], root["rxjs/add/operator/share"], root["rxjs/add/operator/toArray"]);
```
If I don not use amd and cmd loader, it is not work.
I update it to 
```javascript
root["ng2-translate"] = factory(root.ng.core, root.ng.http, root.Rx.Observable, root.Rx.Observable['of'], root.Rx.Observable.prototype.map, root.Rx.Observable.prototype.merge, root.Rx.Observable.prototype.share, root.Rx.Observable.prototype.toArray);
```
in my project.

**Comment by ocombe** [comment]
ah good point, I have to update the webpack setup then

**Comment by hstarorg** [comment]
`` factory(root.ng.core, root.ng.http, root.Rx.Observable, ...)`` need update to `` factory(root.ng.core, root.ng.http, root.Rx, ...)``
