### ISSUE TITLE
Webpack UglifyJs SyntaxError during bundle creation

### ISSUE THREAD

**Issue by kristian-b** [ocombe/ng2-translate#286]
**I'm submitting a ...** 
```
[ x ] bug report
[ ] support request
[ ] feature request
```

**Current behavior**
If ng2-translate runs in my development environment using SystemJS everything works fine (same configuration as in the Angular 2 Quickstart tutorial). If I want to build a bundle using webpack with the configuration of the Angular 2 Webpack tutorial, the following error appears:

`ERROR in vendor.bundle.js from UglifyJs
SyntaxError: Unexpected token: string (./index) [./~/ng2-translate/ng2-translate.js:1,0]`

I changed the ng2-translate imports to ng2-translate/ng2-translate and I tried to use the babel-loader with the plugin babel-plugin-transform-es2015-modules-commonjs as described in an issue, but nothing changes. 

Any ideas?

**Please tell us about your environment:** Windows 10

* **ng2-translate version:** 3.1.3

* **Angular version:** 2.1.0

* **Language:** TypeScript 2.0.3

**Comment by flycat52** [comment]
I upgraded to version 3.1.3, add below code to my webpack.dev.js
`{
                test: /\.js$/,
                include: /ng2-translate/,
                loader: 'awesome-typescript-loader'
            },`

I can run the project even with below errors:
ERROR in [default] 
File 'C:/Projects/.../node_modules/ng2-translate/ng2-translate.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
ERROR in [default] 
File 'C:/Projects/.../node_modules/ng2-translate/src/translate.parser.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
ERROR in [default] 
File 'C:/Projects/.../node_modules/ng2-translate/src/translate.pipe.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
ERROR in [default] 
File 'C:/Projects/.../node_modules/ng2-translate/src/translate.service.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

Any updates to remove such errors?

**Comment by ocombe** [comment]
Change your loader code to ` { test: /\.ts$/, include: /ng2-translate/, loader: 'awesome-typescript-loader' },`, it will load the d.ts files and the js files as if it was typescript

**Comment by flycat52** [comment]
Thanks @ocombe for the quick reply. I changed to /\.ts$/, it was built without error. However, when I run the project, it still gives me "Unexpected token import" error.
![image](https://cloud.githubusercontent.com/assets/8804311/19617678/563dc24c-9869-11e6-9b64-e41707a5996e.png)

![image](https://cloud.githubusercontent.com/assets/8804311/19617683/69fe7394-9869-11e6-87e6-9796109ae212.png)

Any other idea?
Thanks!

**Comment by rlopez4** [comment]
If you are still importing like so `from 'ng2-translate/ng2-translate';` than you can just remove the second ng2-translate and it should work.

**Comment by flycat52** [comment]
@rlopez4 It's correct!! No build error or running error. Thanks!

**Comment by ocombe** [comment]
@kristian-b do you still have an error too, or can I close this ?

**Comment by kristian-b** [comment]
Hello,

using the loader config from ocombe and changing the imports from ng2-translate/ng2-translate to ng2-translate was the solution for me too. Now I have a lot of notices but it works.

Thank you, you can close it.
