### ISSUE TITLE
bundle not available since 3.1.3

### ISSUE THREAD

**Issue by normanwenk** [ocombe/ng2-translate#287]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

source files in the bundle folder

**Expected/desired behavior**

bundle file in the bundle folder

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

in your project: configure dependency to ng2-translate 3.1.3 and run npm install
- **ng2-translate version:** 3.1.3
- **Angular version:** 2.0.0-rc.X
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by ocombe** [comment]
The bundle is now "index.js" instead of "ng2-translate.js" in the bundles folder
But I might change it back to "ng2-translate.js" because it seems to generate a few problems with aot

**Comment by jnah** [comment]
not working for ng2 2.0.0 (systemJS:

(index):27 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur(…)

**Comment by SamVerschueren** [comment]
Ready my comment [here](https://github.com/ocombe/ng2-translate/issues/219#issuecomment-256256623). That should solve the problem.

@ocombe The bundle and the AoT compilation or two different things. The bundle isn't used for AoT. It has everything to do with how the module is configured. This makes me wonder if we should've done a major release instead of a patch.

**Comment by eisverticker** [comment]
I also had some trouble upgrading ng2-translate to the newest version and i also got those systemjs and traceur errors. The only configuration which seems to work for me is the following:          
`'ng2-translate':              'npm:ng2-translate/bundles/index.js' `  
All dependencies and angular2 are up to date.
In my opinion it would be easier to have a ng2-translate/ng2-translate.js file which satisfies the needs of systemjs and the transpiler so the configuration could be as easy as: `'ng2-translate':              'npm:ng2-translate'`.

**Comment by SamVerschueren** [comment]
I tried it again in the plunkr and it seems to work with `npm:ng2-translate` as well. I also tested this on my local machine and it just works.

http://plnkr.co/edit/aDeHGUrodsbBJ1gItv7s

I'm going to close this as the original problem is resolved.
