### ISSUE TITLE
"onLangChange" subscriber in pipe does not fire

### ISSUE THREAD

**Issue by gitnik** [ocombe/ng2-translate#288]
**I'm submitting a ...**

```
[x] bug report
```

**Current behavior**
It seems that the the `onLangChange` callback inside the translate pipe is not being called. If I register the callback in my application it is being called, but inside the pipe nothing happens.

**Expected/desired behavior**
The `onLangChange` subscriber inside the pipe should fire

**Comment by gitnik** [comment]
Alrighty so the issue seems to be that my application and the translation pipe receive different instances of the `translateService`. Here's how my module loads the `TranslateModule`

```typescript
@NgModule({
    imports: [
        CommonModule,
        HttpModule,
        FormsModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, '/app/welcome/translations', '.json'),
            deps: [Http]
        })
    ],
    declarations: [
        WelcomePageComponent,  // <--- uses the translate pipe
    ],
    exports: [
        HttpModule,
        WelcomePageComponent,
        CommonModule,
        FormsModule,
        TranslateModule
    ]
})
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [LocaleService /* <--- uses the translateService */],
        };
    }
}

```

I am not able to spot anything that looks off unfortunately, so I hope you guys can help me out

**Comment by SamVerschueren** [comment]
This is a flaw in the documentation and should be updated ASAP. You should never ever call the `forRoot()` of any module in the `SharedModule`, or feature module for that matter. There is a reason it is called `forRoot`, because it should only be called once in the root module, most of the time `AppModule`.

So move that piece of code, `TranslateModule.forRoot` to your `AppModule` and change your `SharedModule` to this

```js
@NgModule({
    imports: [
        CommonModule,
        HttpModule,
        FormsModule
    ],
    declarations: [
        WelcomePageComponent,  // <--- uses the translate pipe
    ],
    exports: [
        HttpModule,
        WelcomePageComponent,
        CommonModule,
        FormsModule,
        TranslateModule
    ]
})
export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [LocaleService /* <--- uses the translateService */],
        };
    }
}
```

**Comment by ocombe** [comment]
Could you update the readme @SamVerschueren ? We need to add a section for AoT describing all of our recent findings, and the same for systemjs

**Comment by SamVerschueren** [comment]
Yes, I will take a look when I find some time. Hopefully today, not sure though.

**Comment by ocombe** [comment]
Awesome, no pressure, it's not a paid job :D

**Comment by gitnik** [comment]
Thanks a lot!
