### ISSUE TITLE
Production bundle can't find i18n JSONs

### ISSUE THREAD

**Issue by Mossar** [ocombe/ng2-translate#290]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] support request
[ ] feature request
```

**Current behavior**
I use angular-cli (which has webpack) and when I try to create production bundle with ng build -prod I can't see any messages from ng2-translate (empty fields, buttons, etc). I receive error:
`main.6cbaf8f….bundle.js:1240 EXCEPTION: Response with status: 404 Not Found for URL: http://127.0.0.1:4321/app/shared/i18n/pl.json`

So now we can see it refers to file from project structure, but this directory doesn't exist in /dist.

**Expected/desired behavior**
Probably it should be bundled somehow or directories with JSONs should be created.

**Please tell us about your environment:**

* **ng2-translate version:** 3.1.2
* **angular-cli:"** 1.0.0-beta.17
* **Angular version:** 2.0.0
 
* **Browser:** as far as I see - ALL

**Comment by SamVerschueren** [comment]
Someone had an issue with `angular-cli` as well a couple of days ago so I created a repository for that https://github.com/SamVerschueren/ng2-translate-aot-test.

The [first commit](https://github.com/SamVerschueren/ng2-translate-aot-test/commit/90472c7e8c4d3e4daaa3e88a30377ab9b941187b) covers the initial `ng new` app. So nothing exciting over there. The [second commit](https://github.com/SamVerschueren/ng2-translate-aot-test/commit/2b3feceee8e288ea6480eaa5bc9ab64906630887) adds `ng2-translate`. Works perfectly.

> Probably it should be bundled somehow or directories with JSONs should be created.

This is not up to `ng2-translate` to take care of that. If the `json` files aren't part of your build, that's the fault of the Angular cli not copying over `json` files.

**Comment by Mossar** [comment]
Okay thank you. At the beginning we've put JSONs into src/app/shared directory (our own directory for shared modules, etc.) so it wasn't added do bundle by angular-cli. Now we put JSONs in  src/assets directory and it of course works well. Sorry for confusion.

**Comment by SamVerschueren** [comment]
No problem, glad it's resolved :) :beers:
