### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export  ---> export * from './index';

### ISSUE THREAD

**Issue by Mohammed9531** [ocombe/ng2-translate#291]
I have installed and imported the translate module as per the instructions. It kept on throwing unexpected token export error. I'm using Angular 2.1.1.

**Error :** Unexpected token export

**At line:** export \* from './index';

Am I missing something?

**Comment by SamVerschueren** [comment]
How do you import? SystemJS or Webpack?

**Comment by Mohammed9531** [comment]
I'm using Webpack.

**Comment by SamVerschueren** [comment]
Make sure you import `from 'ng2-translate';` and not `from 'ng2-translate/ng2-translate';`

**Comment by tzoratto** [comment]
same problem here and solved by @SamVerschueren 's solution, thanks.

**Comment by tejashreeKate** [comment]
I am having the same problem when I am trying to run the app on server.
Can someone please post the solution?

**Comment by SamVerschueren** [comment]
Have you read my solution? Doesn't it work?

> Make sure you import from 'ng2-translate'; and not from 'ng2-translate/ng2-translate';

**Comment by Mohammed9531** [comment]
@tejashreeKate @SamVerschueren solution works like a charm.  Closing this issue as resolved.
