### ISSUE TITLE
gulp based ng2 starters

### ISSUE THREAD

**Issue by valorkin** [ocombe/ng2-translate#3]
Hey,
I tried but I am not working with gulp\systems.js as you do
can you create a simple branch for https://github.com/pkozlowski-opensource/ng2-play
with ng2-translate working?
I was thinking about branches with one commit, one branch per module
because usage of ng2-modules will produce a lot of questions :)
like this: https://github.com/valor-software/ng2-bootstrap/issues/18

**Comment by ocombe** [comment]
Ok so I had a hard time trying to figure out what was the problem, and it's just that ng2-play uses an old SystemJS version that has a bug where the defaultExtension doesn't work in subfolders: https://github.com/systemjs/systemjs/issues/805

Anyway, once I updated this and switched from system-csp-production to system.src (that can load all types of modules, not just systemjs modules), it worked easily: https://github.com/ocombe/ng2-play/tree/ng2-translate-test

**Comment by valorkin** [comment]
Awesome :+1:
