### ISSUE TITLE
ng2-translate.js?6935:1 Uncaught SyntaxError: Unexpected token export(…)

### ISSUE THREAD

**Issue by johnc1984** [ocombe/ng2-translate#306]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Doesn't load when used in the constructor of the top level app compnent.. Following the example from the plunker: http://plnkr.co/edit/btpW3l0jr5beJVjohy1Q?p=preview the result when trying to load the app is:
`ng2-translate.js?6935:1 Uncaught SyntaxError: Unexpected token export(…)`

`export * from './index';

/*****************
 ** WEBPACK FOOTER
 ** ./~/ng2-translate/ng2-translate.js
 ** module id = 426
 ** module chunks = 1
 **/`

**Expected/desired behavior**
The existing angular2 app to load

**Reproduction of the problem**
` "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "@ngrx/core": "1.2.0",
    "@ngrx/store": "2.2.1",
    "angular-pipes": "^2.0.5",
    "angular2-infinite-scroll": "^0.1.92",
    "angular2-moment": "^0.8.1",
    "angular2-template-loader": "^0.5.0",
    "ckeditor": "^4.5.8",
    "core-js": "^2.4.0",
    "moment": "^2.6.0",
    "moment-timezone": "^0.5.6",
    "ng2-bootstrap": "1.1.16",
    "ng2-ckeditor": "^1.0.3",
    "ng2-dnd": "^2.0.1",
    "ng2-file-upload": "1.0.3",
    "ng2-page-scroll": "3.2.1",
    "ng2-translate": "^4.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.26"
  },`

**Please tell us about your environment:**
Using webpack to build the typescript files

* **ng2-translate version:** 
    "ng2-translate": "^4.0.0",

* **Angular version:**
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",

 

* **Browser:** 
[all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** 
"typescript": "^2.0.6",

**Comment by ocombe** [comment]
Hello,
you didn't link the right plunkr, because it's working on this one (and I think it's the default one).

**Comment by SamVerschueren** [comment]
Also let us know what you're using. SystemJS, Webpack?

**Comment by ocombe** [comment]
there's a `WEBPACK FOOTER` in his log, I would suspect it's webpack :P

**Comment by SamVerschueren** [comment]
> Also I can almost immediately tell you that the problem is that you import from ng2-translate/ng2-translate instead of just ng2-translate

I tested this with SystemJS in the plunkr, and that should work because `ng2-translate.ts` just exports `index.ts`. Not sure why Webpack fails on this.

**Comment by johnc1984** [comment]
Ha ok thanks for the lightning fast response.

It was indeed 
`import {TranslateService} from 'ng2-translate/ng2-translate';`

Converting it to worked.
`import {TranslateService} from 'ng2-translate';`

Thanks!

**Comment by ocombe** [comment]
Just to know, where did you read the 'ng2-translate/ng2-translate'? did we forget it somewhere in the docs ?

**Comment by SamVerschueren** [comment]
Odd, I tested this on my `ng2-translate-aot-test` repository in [this](https://github.com/SamVerschueren/ng2-translate-aot-test/tree/import-ng2-translate) branch with [this](https://github.com/SamVerschueren/ng2-translate-aot-test/commit/72fb44f12d5b15fe92daf22ea10809a243cbf0ea) commit. It just works out of the box, don't have to change anything. So why is everyone experiencing problems with this?

**Comment by ocombe** [comment]
I have no idea, old versions of typescript maybe ?

**Comment by johnc1984** [comment]
Straight from the plunker you link to in your readme.md :)

http://plnkr.co/edit/btpW3l0jr5beJVjohy1Q?p=preview

`
import {Component} from '@angular/core';
import {TranslateService} from 'ng2-translate/ng2-translate';

@Component({
    selector: 'my-app',
    template: `
    <div>
      <h2>{{ 'HOME.TITLE' | translate }}</h2>
      <label>
        {{ 'HOME.SELECT' | translate }}
        <select #langSelect (change)="translate.use(langSelect.value)">
          <option *ngFor="let lang of translate.getLangs()" [value]="lang" [selected]="lang === translate.currentLang">{{ lang }}</option>
        </select>
      </label>
    </div>
  `,
})
export class AppComponent {
    constructor(private translate: TranslateService) {
        translate.addLangs(["en", "fr"]);
        translate.setDefaultLang('en');

        let browserLang = translate.getBrowserLang();
        translate.use(browserLang.match(/en|fr/) ? browserLang : 'en');
    }
}
`

**Comment by SamVerschueren** [comment]
You're right, we forgot to update those. Can you do that @ocombe.

Really makes me wonder why it fails on your system though, as you can see, the plunkr works just fine with `ng2-translate/ng2-translate`. Tested this on SystemJS and Webpack, should work both. But after all, glad it's resolved.

**Comment by ocombe** [comment]
Yes, it's updated now !

**Comment by johnc1984** [comment]
I've inherited this ang2 project and completely fresh to typescript...

My guess is the plunker is using ever so slightly different version of something. below is a complete list of the package.json from the project. The webpack in use is the webpackdev server if that helps in any way :)

The setup is gulp preps the rel. files, webpack then builds and on dev delivers with webpackdev server.
```

  "scripts": {
    "run": "concurrently --kill-others 'gulp' 'webpack-dev-server --d --display-reasons --display-modules'",
    "build": "webpack --config config/webpack.live.js --profile --bail"
  },
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "@ngrx/core": "1.2.0",
    "@ngrx/store": "2.2.1",
    "angular-pipes": "^2.0.5",
    "angular2-infinite-scroll": "^0.1.92",
    "angular2-moment": "^0.8.1",
    "angular2-template-loader": "^0.5.0",
    "ckeditor": "^4.5.8",
    "core-js": "^2.4.0",
    "moment": "^2.6.0",
    "moment-timezone": "^0.5.6",
    "ng2-bootstrap": "1.1.16",
    "ng2-ckeditor": "^1.0.3",
    "ng2-dnd": "^2.0.1",
    "ng2-file-upload": "1.0.3",
    "ng2-page-scroll": "3.2.1",
    "ng2-translate": "^4.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@angular/upgrade": "2.0.0-rc.4",
    "@ngrx/store-devtools": "3.0.2",
    "@ngrx/store-log-monitor": "3.0.2",
    "babelify": "^6.1",
    "bootstrap": "4.0.0-alpha.3",
    "browser-sync": "^2.13.0",
    "browserify": "^13.0",
    "concurrently": "^2.2.0",
    "connect-history-api-fallback": "^1.2.0",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-jsonminify": "1.0.0",
    "gulp-nunjucks-render": "^2.0.0",
    "gulp-rename": "^1.2",
    "gulp-sass": "^2.3.2",
    "gulp-typescript": "^3.1.2",
    "gulp-uncss": "^1.0.5",
    "json-loader": "^0.5.4",
    "merge-stream": "^1.0.0",
    "nunjucks": "^2.4.2",
    "raw-loader": "^0.5.1",
    "ts": "0.0.0",
    "ts-loader": "^0.8.2",
    "typescript": "^2.0.6",
    "typings": "^1.5.0",
    "vinyl-source-stream": "^1.1",
    "webpack": "^1.13.2",
    "webpack-merge": "^0.14.1"
  }

```

**Comment by johnc1984** [comment]
I've inherited this ang2 project and completely fresh to typescript...

My guess is the plunker is using ever so slightly different version of something. below is a complete list of the package.json from the project. The webpack in use is the webpackdev server if that helps in any way :)

The setup is gulp preps the rel. files, webpack then builds and on dev delivers with webpackdev server.
```

  "scripts": {
    "run": "concurrently --kill-others 'gulp' 'webpack-dev-server --d --display-reasons --display-modules'",
    "build": "webpack --config config/webpack.live.js --profile --bail"
  },
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "@ngrx/core": "1.2.0",
    "@ngrx/store": "2.2.1",
    "angular-pipes": "^2.0.5",
    "angular2-infinite-scroll": "^0.1.92",
    "angular2-moment": "^0.8.1",
    "angular2-template-loader": "^0.5.0",
    "ckeditor": "^4.5.8",
    "core-js": "^2.4.0",
    "moment": "^2.6.0",
    "moment-timezone": "^0.5.6",
    "ng2-bootstrap": "1.1.16",
    "ng2-ckeditor": "^1.0.3",
    "ng2-dnd": "^2.0.1",
    "ng2-file-upload": "1.0.3",
    "ng2-page-scroll": "3.2.1",
    "ng2-translate": "^4.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@angular/upgrade": "2.0.0-rc.4",
    "@ngrx/store-devtools": "3.0.2",
    "@ngrx/store-log-monitor": "3.0.2",
    "babelify": "^6.1",
    "bootstrap": "4.0.0-alpha.3",
    "browser-sync": "^2.13.0",
    "browserify": "^13.0",
    "concurrently": "^2.2.0",
    "connect-history-api-fallback": "^1.2.0",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-jsonminify": "1.0.0",
    "gulp-nunjucks-render": "^2.0.0",
    "gulp-rename": "^1.2",
    "gulp-sass": "^2.3.2",
    "gulp-typescript": "^3.1.2",
    "gulp-uncss": "^1.0.5",
    "json-loader": "^0.5.4",
    "merge-stream": "^1.0.0",
    "nunjucks": "^2.4.2",
    "raw-loader": "^0.5.1",
    "ts": "0.0.0",
    "ts-loader": "^0.8.2",
    "typescript": "^2.0.6",
    "typings": "^1.5.0",
    "vinyl-source-stream": "^1.1",
    "webpack": "^1.13.2",
    "webpack-merge": "^0.14.1"
  }

```

**Comment by sstorie** [comment]
FWIW I ran into this error message when I was exporting the TranslateModule from a shared module, but forgot to import it into that shared module.
