### ISSUE TITLE
getLangs() returns only one language when "../ i18n/.." contains more than one file.

### ISSUE THREAD

**Issue by nyluje** [ocombe/ng2-translate#307]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[x?] feature request
```

**Current behavior**
I use Ionic 2. The function this.translateService.getLangs() is define as a function that:  "Returns an array of currently available langs". By that I understand that it should return a scan of the languages available in the folder "[my project]\www\assets\i18n". If I have files: "fr.json", "en.json", "nl.json" it should return an array with `["fr","en","nl"]`. It happens that when I use it (with those 3 language files I listed above) it returns: `["fr"]` so "en" and "nl" are missing according to me.

**Expected/desired behavior**
Cf. Current behavior

**Reproduction of the problem**
None

**What is the expected behavior?**
Cf. Current behavior

**What is the motivation / use case for changing the behavior?**
If it does not work as I understood it, I think a function that does that should be included on the road map. Figuring out the languages available in the Ionic 2 project could help to match with languages available on the browser . 

**Please tell us about your environment:**
Windows 10

* **ng2-translate version:** 3.1.3

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [ Chrome 54.0.2840.71  ] 
 
* **Language:** [ TypeScript 2.0 ]

**Comment by ocombe** [comment]
No, it only returns the list of loaded langs (either by using .use, or added via `addLangs(langs: Array<string>)`.
Your application runs in a browser, it has no idea what is available on the server, and there is no way to know that.
If you setup your project, you could pass this list of langs during the build using webpack or something else, but this is on your side, not something I could do in the lib, sorry.
