### ISSUE TITLE
translate.get with array of keys returns keys and not translation

### ISSUE THREAD

**Issue by ryanki1** [ocombe/ng2-translate#310]
With following:

  prepareCaptions() {
    this._translate.get([
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.LEAD',
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.LEAD_DOUBLE_TRACTION',
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.LEAD_MULTIPLE_TRACTION',
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.ADDITIONAL',
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.ADDITIONAL_DOUBLE_TRACTION',
      'APP.PAGES.LOCOMOTIVE.PLACEHOLDER.TYPE.ADDITIONAL_MULTIPLE_TRACTION'
    ])
        .subscribe((translations: string[]) => {
          this._applicationRepository.helper.tfzCaptions = translations;
        })
  }

where _translate is injected TranslateService in Ionic2 I just get the keys being bounced back :-(

**Comment by SamVerschueren** [comment]
Does it work with only loading 1 key? Seems like it can't find the translations at all.

**Comment by ryanki1** [comment]
Hi Sam,

yes translate.get('ERE.BE.A.TRNSLATION_KEY') works fine :-)

Best regards,
Kieran

________________________________

**Comment by SamVerschueren** [comment]
It seems to work perfectly fine in the plunker.

http://plnkr.co/edit/WoIeZeC9h0OVHQsrww6U

The result of the observable isn't an array though, it's an object. If you inspect that plunker you will notice that this call

```js
translate.get(['HOME.TITLE', 'HOME.SELECT']).subscribe(res => {
  console.log(res);
});
```

results in this object

```json
{
  "HOME.TITLE": "Hello Angular 2 with ng2-translate!",
  "HOME.SELECT": "Change language"
}
```

**Comment by SamVerschueren** [comment]
Closing this as I believe it's just a type issue `string[]` Vs. `{[key: string]: string}`. Feel free to post new information if you believe my answer did not solve the problem.

**Comment by mehrad-rafigh** [comment]
Hi I am having the same Issues here and tried everything @SamVerschueren suggested. But I still get the keys and not the translations
