### ISSUE TITLE
Support for different language per component

### ISSUE THREAD

**Issue by frankspin89** [ocombe/ng2-translate#313]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] support request
[X ] feature request
```

**Current behavior**
At the moment it's possible to translate the global user interface of the app.

**Expected/desired behavior**
I would like to have the option to set a different language per component. So for example I set my global app language to English and for my invoice component I want to set the language to German. So when I share the invoice with my German client he can read it in his own language.

**Comment by SamVerschueren** [comment]
What do you mean with "share the invoice with my client"? Is that like a URL you share or more like a printed PDF from your component?

If it's a URL, I could suggest two things.
1. Add a `lang` query param that changes the language of your app/invoice to the one you want
2. Use the `getBrowserLang()` [API method](https://github.com/ocombe/ng2-translate#methods) to retrieve the users browser lang which will auto detect the language of your clients browser. I assume that if the browsers language is english, the invoice could be english as well.

**Comment by frankspin89** [comment]
Hello Sam,

Thanks for your response. I think I need both options you propose. What do you suggest to print a invoice to a pdf from my component?

**Comment by SamVerschueren** [comment]
Hi @frankspin89. Although I believe this belongs more at StackOverflow, let me try to give you a direction on how I would implement it. First of all, please note that I don't know the exact requirements and I assume quite a lot of things here :).

Changing the language of your invoice is quite easy. Like I said before, you could get the browser language with the `getBrowserLang()` API method by default or override it with a query parameter like `?lang=de` to hardcode the language. Should be quite easy to do.

To render it to a pdf, I would just suggest to use the print method of your browser. If you want to hide or show stuff on the printed page, use the `print` media query to do that. You could easily add a button to your page calling `window.print()` which will show a print dialog.

Hope this helps you a little in the right direction.

--------------
Closing this as it has not much to do with `ng2-translate`. If you end up creating a StackOverflow question to get more in depth, don't hesitate to link it here.
