### ISSUE TITLE
500 Internal Server Error: Error loading http://localhost:3000/ng2-translate as "ng2-translate" 

### ISSUE THREAD

**Issue by tommydeaks** [ocombe/ng2-translate#316]
**I'm submitting a ...**  (check one with "x")
```
[X] support request => check the FAQ and search github for a similar issue before submitting
```

**Current behavior**
I am trying to utilise ng2-translate in my new application. 

The error I am getting is this : 

> Error: Error: XHR error (500 Internal Server Error) loading http://localhost:3000/ng2-translate
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3000/assets/js/vendor/zone.min.js:1:625)
	    at e.invokeTask (http://localhost:3000/assets/js/vendor/zone.min.js:1:16542)
	    at n.runTask (http://localhost:3000/assets/js/vendor/zone.min.js:1:13902)
	    at XMLHttpRequest.invoke (http://localhost:3000/assets/js/vendor/zone.min.js:1:17655)
	Error loading http://localhost:3000/ng2-translate as "ng2-translate" from http://localhost:3000/client/app.module.js

Here's my app.module:

``` javascript
import {NgModule, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {HttpModule} from "@angular/http";

import {AppComponent}  from './app.component';
import {routing} from "./routes";

import {FormsModule} from "@angular/forms";
import {MaterializeDirective} from "angular2-materialize";
import {TranslateModule, TranslateLoader, TranslateStaticLoader} from 'ng2-translate';

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        FormsModule,
        routing,
        TranslateModule.forRoot()
    ],
    providers: [],
    declarations: [AppComponent],
    bootstrap: [AppComponent],
    schemas: [
        CUSTOM_ELEMENTS_SCHEMA
    ]
})
export class AppModule {
} 
```
I'm also, I think, configuring my systemJS file correctly:

``` javascript
var isPublic = typeof window != "undefined";

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': (isPublic) ? '/' : 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'client',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs': 'npm:rxjs',
      'js-base64': 'npm:js-base64/base64.js',
      'buffer': '@empty',
      'socket.io-client': 'npm:socket.io-client',
      'angular2-jwt': 'npm:angular2-jwt/angular2-jwt.js',
      'materialize-css': 'npm:materialize-css',
      'angular2-materialize': 'npm:angular2-materialize',
      'ng2-translate': 'npm:ng2-translate'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      'app': {
        'main': './main.js',
        'defaultExtension': 'js'
      },
      'rxjs': {
        'defaultExtension': 'js'
      },
      'materialize-css': {
        "format": "global",
        "main": "dist/js/materialize",
        "defaultExtension": "js"
      },
      'angular2-materialize': {
        "main": "dist/index",
        "defaultExtension": "js"
      },
      'socket.io-client':{
        "format": 'cjs',
        "main": "socket.io.js",
        "defaultExtension": "js"
      },
      'ng2-translate': {
        'defaultExtension': 'js'
      }
    }
  });
})(this);
```

I've tried following the Plnkr example you give but I must have missed something. I've not tried to use the module yet - only trying to import it!

I removed all imports and references to ng2-translate in app.module.js and tried to run the application with the translate service imported into app.component.js, as follows:

```javascript
import {Component} from "@angular/core";
import {Subscription} from "rxjs";
import {TranslateService} from "ng2-translate";

declare var __moduleName: any;

@Component({
    moduleId: __moduleName,
    selector: "app",
    templateUrl: `app.component.html`,
    styleUrls: ['app.component.css']
})

/* Main application component and entry point */
export class AppComponent  {

    loggedIn: boolean;
    locationSet: boolean;
    disconnected : boolean;

    authSubscription: Subscription;
    locSubscription: Subscription;
    connSubscription: Subscription;

    constructor(private translateService: TranslateService) {

        // this language will be used as a fallback when a translation isn't found in the current language
        translateService.setDefaultLang('en');

        // the lang to use, if the lang isn't available, it will use the current loader to get them
        translateService.use('en');
    }
}
```
and I get this same error: 

> Error: Error: XHR error (500 Internal Server Error) loading http://localhost:3000/ng2-translate
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3000/assets/js/vendor/zone.min.js:1:625)
	    at e.invokeTask (http://localhost:3000/assets/js/vendor/zone.min.js:1:16542)
	    at n.runTask (http://localhost:3000/assets/js/vendor/zone.min.js:1:13902)
	    at XMLHttpRequest.invoke (http://localhost:3000/assets/js/vendor/zone.min.js:1:17655)
	Error loading http://localhost:3000/ng2-translate as "ng2-translate" from http://localhost:3000/client/app.component.js

Forgive me if I haven't included enough information - I'll gladly provide more if needs be!

**Comment by SamVerschueren** [comment]
Try adding `main: 'index.js'` to the `ng2-translate` package in the SystemJs config.

**Comment by tommydeaks** [comment]
Hi Sam, 

I've tried that - I get this:

>Error loading http://localhost:3000/ng2-translate/index.js "ng2-translate" from http://localhost:3000/client/app.module.js

I've tried changing the main to ng2-translate.js too, with the same error.

Sorry, but I'm at a bit of a loss as I really can't see what it is I am doing wrong.  

Thanks a lot for replying!

**Comment by tommydeaks** [comment]
Hi @SamVerschueren 

I've figured what was wrong. 

In your Plnkr example you have: 
```
  paths: {
    'npm:': 'https://unpkg.com/'
  }
```

But in my setup I have:
```
    paths: {
      // paths serve as alias
      'npm:': (isPublic) ? '/' : 'node_modules/'
    }
```

So what I need to do is this: 

```
      'ng2-translate': {
        'defaultExtension': 'js',
        'main': 'bundles/index'
      }
```

Cheers!

**Comment by abdouSamak** [comment]
bonjour je rencontre au niveau de mon serveur quand je fais un appel sur ma base de données . Je voudrais getter un element par un id mais la requette trouve l'id il ajoute à chaque au début un %20 qui je ne sais pas d'où ca vient.

![image](https://user-images.githubusercontent.com/67417303/102513650-c5513f00-408b-11eb-9c3a-593dfb41176a.png)

Est ce que quelqu'un peut m'aider. Merci :)
