### ISSUE TITLE
translate.get observable

### ISSUE THREAD

**Issue by barocsi** [ocombe/ng2-translate#320]
Just being curious here, why translate.get returns an observable while by the time we use .get method it should have already been loaded the translate json in memory?

I mean I want to popup an alert with localised texts like
```
        translate.get('CANCEL', {value: 'cancel'}).subscribe((res: string) => {
            this.canceltext = res;
        });

and then somewhere later
alert(this.canceltext) 
```

Why cannot we just simply use a sync method for translate.get ?

Thanks

**Comment by ocombe** [comment]
For two reasons:
- we don't know if the loader has loaded json files and if the lib is fully initialized at the beginning, using an observable ensures that we only return when it's available
- users can make custom loaders, and using an observable allows more complex scenarii

If you want a sync method, there is one and it's `translate.instant`, but sometimes it can only returns the key (if the translations are not yet available)

**Comment by barocsi** [comment]
Thanks, that would work!
Making translation available should be dealt with during initialization of the app by the developer.

**Comment by ocombe** [comment]
Agreed, but I'd rather offer more possibilities than limit them
