### ISSUE TITLE
Exception if translation is explicitly null

### ISSUE THREAD

**Issue by chpasha** [ocombe/ng2-translate#322]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I stumbled upon a bug which is difficult to debug since the error message has mostly nothing to do with ng2-translate and usually looks like "Expression has changed after it was checked", but if you got lucky (or switched to production mode) you get smth. like subscribe is not found on undefined in TranslationService.get when using translate-pipe. The real problem was that one of my translation entries looked like "KEY": null in json.  I know it is in certain way my fault - it is easy to avoid when you know what's going on, but you might agree that it is very hard to find such an error and it would have never been a problem if you could check the value corresponding to the KEY for the null-ness. 
It happens when using the translate pipe - didn't try what happens if using get directly, I suppose nothing bad, since null is just returned as translation (which is somehow also not quite right according to the contract)

**Expected/desired behavior**
Default translation or the key itself should be returned if translation key is present, but it's value is explicitly null.
**Reproduction of the problem**
create translation with some key and value null e.g.
{
  "mytranslation": null
}
and use it in template
{{ mytranslation | translate }}
**What is the expected behavior?**
default translation  or mytranslation key itself should be returned

**What is the motivation / use case for changing the behavior?**
better quality

**Please tell us about your environment:**
ubuntu 14.04

* **ng2-translate version:** x.x.x
4.0.0

* **Angular version:** 2.0.0-rc.X
2.2.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
typescript es6

**Comment by ocombe** [comment]
Ah good catch thanks!

**Comment by ocombe** [comment]
This has been fixed, the parser now checks that the value isn't null or undefined.
