### ISSUE TITLE
Re-evaluation of translate pipes if ChangeDetectionStrategy.OnPush is set

### ISSUE THREAD

**Issue by hpop** [ocombe/ng2-translate#33]
Hi,

I am currently try to use `ChangeDetectionStrategy.OnPush` in all my components. That means, that all bindings are not checked if the state of my application stays the same. Thats great but it means that all translate pipes are not getting re-evaluated if I change the current language. 

I think It may possible to wrap the pipe into an own directive that listens to the `onLangChange` event and invalidates itself.

Do you have any Ideas?

**Comment by ocombe** [comment]
I'm not expert enough in Angular 2 to know the right thing to do here. Do you have an article somewhere explaining the different change detection strategies ?
And an example app that uses OnPush ?

**Comment by hpop** [comment]
I am just starting to figure it out as well and the documentation is not very good at this point of time.

I guess the best articles to start are:
[http://victorsavkin.com/post/110170125256/change-detection-in-angular-2](url)
[http://victorsavkin.com/post/137821436516/managing-state-in-angular-2-applications](url)

Give me some time and I will prepare a example for the case.

**Comment by ocombe** [comment]
Thanks, I'll look at them this week end

**Comment by hpop** [comment]
I have a hard time to get this running for an example. Do you have a working jsfiddle or plunker with ng2-translate?

In the meantime I tested #31 and it perfectly fixes my issue. If I use directives instead of pipes in my application, everything gets updated perfectly even if OnPush is used.

**Comment by sclausen** [comment]
@hpop but be aware, that you should be careful with html injection, since no sanitization will be performed.
I did a little bit of research because of @ocombes concerns in #31, but I didn't found any lightweight solution for this problem.

**Comment by ocombe** [comment]
It look like we might need to write a sanitization library for ng2

**Comment by ocombe** [comment]
Hey @PascalPrecht any idea on how to make the pipe work with OnPush ?

**Comment by PascalPrecht** [comment]
I don't know if there's any event system implemented in ng2-translate yet, but if there's something like a translate service, it could expose an observable which fires when the languages changes. Then the pipe could subscribe to that service and it could use the changedetector ref to mark the path til root to be checked.

**Comment by ocombe** [comment]
Thanks @PascalPrecht, it turns out that you can inject a `ChangeDetectorRef` in a pipe (I found out by reading the `AsyncPipe` source code). It should work now !

**Comment by baio** [comment]
Honestly xtranslate doesn't play well with OnPush change detection, for every component which uses xtranslate pipe you has to write a lot of same boilerplate code, so think twice before use this lib if you want use it alongside with OnPush .
