### ISSUE TITLE
Translations not loading on Component's constructor

### ISSUE THREAD

**Issue by chrisbenseler** [ocombe/ng2-translate#331]
In an Ionic 2 app, I have a Translation service set, the pipes (in the .html) work fine.
But the translations does not work inside the constructor:

```
export class CheckAccess {
	constructor(public translate: TranslateService) {
		console.log(this.translate.instant("tos.title")) //output tos.title
	}
}
```

but if I wrap it inside an setTimeOut

```
export class CheckAccess {
	constructor(public translate: TranslateService) {
                setTimeout( () => {
		   console.log(this.translate.instant("tos.title")) //output the value com the tos.title key in my json file
                })	
        }
}
```

Using 4.0.1 version.

**Comment by ocombe** [comment]
Yes, because "instant" takes the current value available or the key if the value is undefined.
In the constructor your translations probably haven't been loaded yet.

Either use `get` which uses an observable or use `instant` later (like you did with the set timeout)

**Comment by chrisbenseler** [comment]
@ocombe thanks, I didn't know there is an _get_ method. Changed my code, works perfect!

**Comment by RedaZZ** [comment]
Would you please write your answer?  how to use get method instead of instant? i have the same issue
Thanks
