### ISSUE TITLE
ng2-translate translate.get doesn't return the value

### ISSUE THREAD

**Issue by imenhb** [ocombe/ng2-translate#337]
**Current behavior**
In my Component i need to translate a string so i used "get" and i set the app to english as default lang

```
this.translate.get("waitmsg").subscribe(res => {
console.log("HELLO:" + res);
});
```
it should return "Please Wait" but it returns the key "waitmsg" 
`HELLO:waitmsg`
**Expected/desired behavior**
I want it to return the value not the key

**Please tell us about your environment:**

* **ng2-translate version:** ^2.2.2

* **Angular version:** 2.0.0-rc.3
 
* **Language:** "typescript": "2.0.6"

**Comment by SamVerschueren** [comment]
Have you set the english locale before using the `get` method?

```js
this.translate.use('en');
this.translate.get("waitmsg").subscribe(res => {
     console.log("HELLO:" + res);
});
```

**Comment by imenhb** [comment]
Hi,
Yes, i already did it.
But i resolved the problem it was because i put this lines in ngOnInit() method i move it to the constructor and now it works fine.

**Comment by SamVerschueren** [comment]
It should work in `ngOnInit` though. It's generally not a good idea to move those things to the constructor as the constructor has to be kept as light as possible.
