### ISSUE TITLE
Tool to extract translateable strings from app

### ISSUE THREAD

**Issue by biesbjerg** [ocombe/ng2-translate#338]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
You have to manually extract strings you want translated

**Expected/desired behavior**
A tool that automatically extracts strings using `translate` pipe in templates or the `get` method in components.

Maybe I missed something and this is already possible, but I haven't seen it mentioned anywhere and have been unable to find anything related using Google.

**Comment by ocombe** [comment]
Hi ! I've actually started working on it just yesterday :-)
Don't expect any quick result though, because it's a lot of work. I initially wanted to use the official cli tool (ng-xi18n) for that, but it's not extensible at all, and I don't think I will be able to do what I want with it, so I'll have to work on my own thing, which means that it will be able to do much more, but also that it will take more time.

**Comment by SamVerschueren** [comment]
@ocombe It would be cool if yours was extensible :).

**Comment by biesbjerg** [comment]
Cool!

This could probably be hacked to get something working pretty quickly: https://github.com/bcabanes/gulp-angular-translate-extract/blob/master/modules/extractTranslations.js

Might give it a shot myself:-)

**Comment by ocombe** [comment]
Oh nice, thanks for the link !

**Comment by Tekorius** [comment]
On a kinda related note, I've written a PHP Symfony command to convert json translation files to one big Excel file and then back again to multiple json translation files. It supports deep objects, comment columns and rows for better context explanation to translators.

People just love to use Excel for translations for some reason.

I could give you the source if you'll find any use of it.

**Comment by ocombe** [comment]
I'll be working on different formats once this tool is working, the first one will be xliff to be compatible with most translation solutions (and with the official ng-xi18n tool that generates xliff files), I could add csv to the list.

**Comment by biesbjerg** [comment]
Do you have any work in a public repo? I'm curious too have you're planning to do it. Using gulp? Custom scripts? Something else?

**Comment by ocombe** [comment]
Nothing public yet. I will be a nodejs lib that you can call as a cli, or include as a library if you prefer. You'll give it a glob of files to parse (ex: `["src/*.ts", "src/*.html"]`) and it will use regexps to find matches.
The tricky part is the find the correct matches and transform them into keys :)

**Comment by biesbjerg** [comment]
I've started working on something as well. 

At this time it extracts strings from templates that are using `TranslatePipe` and from Typescript files when methods `get` and `instant` are used.

https://github.com/biesbjerg/ng2-translate-extract

**Comment by ocombe** [comment]
Awesome, mine extracts strings from directives, which means that if I merge your work with mine we'll have most of the use cases covert !

**Comment by biesbjerg** [comment]
This is just an initial attempt and I'll probably keep working on it, but go ahead!

**Comment by biesbjerg** [comment]
I've added a commandline script and published an NPM package, if anyone is interested in trying it out:
https://www.npmjs.com/package/@biesbjerg/ng2-translate-extract

**Comment by ocombe** [comment]
Closing this issue now, use @biesbjerg's extractor if you need it ! It works well :)
