### ISSUE TITLE
Support multiline from JSON

### ISSUE THREAD

**Issue by Dyljyn** [ocombe/ng2-translate#339]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
```json
{
  "multiline": [
     "Some long string that ",
     "would be prefered to be written over ",
     "multiple lines in JSON"
  ]
}
```

Shows up on screen with the commas `,` of the array in between.
```
Some long string that ,would be prefered to be written over ,multiple lines in JSON
```

**Expected/desired behavior**

String without commas from array.

**What is the motivation / use case for changing the behavior?**
To be able to use multiple lines in case of maximum line-width for readability purposes.

**Please tell us about your environment:**

* **ng2-translate version:** 3.1.3

* **Angular version:** 2.1.1
 
* **Browser:** Chrome 54
 
* **Language:** TypeScript 2.0.6

**Comment by SamVerschueren** [comment]
Just add `<br>` tags in your one line string?

**Comment by Dyljyn** [comment]
@SamVerschueren I think the example text caught you of track (i've edited that to not mislead anyone else). 
I just meant to be able to write multiple lines in JSON for the same key, which could be done by having an array of strings. Just the result of doing this, at the moment, is that the **commas** of the array also come with it in the result on the screen. I don't want them to be on multiple lines in the result.

**Comment by SamVerschueren** [comment]
Oh ok, I also thought that you wanted it to resemble in the UI.

I just don't get why you want to write that in multiple lines. If you softwrap your editor to let's say 80 characters, it will be also be wrapped to multiple lines. In my opinion, you're just making things harder to translate because now it's not a simple key-value anymore. You can't easily copy paste the entire translation you have because you first have to remove the quotes and comma's first.

It's up to @ocombe to decide if he wants to support this. But in my opinion, it's not a very good idea to do that.

**Comment by Dyljyn** [comment]
Well my case is that I have an information block in the UI, which is just a whole block of text which can be in any format as the client requires it to be (including h1, p, ul, etc.). So I thought of writing it in the translation itself and have the multiline to keep it a bit structured but I perfectly get your point that this is not part of translations.

**Comment by ocombe** [comment]
I get what you want, but I don't think it would be really useful for other people.
If more were to ask for this feature I would reconsider it, but not until then.

I'm gonna add new formats soon, and I'm considering adding [json5](http://json5.org/) (in a specific *optional* loader).
Json5 has nice features like comments, multiline strings and more :)

For example:
```js
{
    foo: 'bar',
    while: true,

    this: 'is a \
multi-line string',

    // this is an inline comment
    here: 'is another', // inline comment

    /* this is a block comment
       that continues on another line */

    hex: 0xDEADbeef,
    half: .5,
    delta: +10,
    to: Infinity,   // and beyond!

    finally: 'a trailing comma',
    oh: [
        "we shouldn't forget",
        'arrays can have',
        'trailing commas too',
    ],
}
```

Writing a loader to support that would be really easy if you want to do it yourself.

**Comment by SamVerschueren** [comment]
Jup, writing your own custom loader was also what I was going to suggest.

@ocombe Wow, that would be nice! Are you going to put this in a separate package?

**Comment by ocombe** [comment]
yes, once I've chosen the new name / namespace, it will be easy to release new loaders like that :)

**Comment by Dyljyn** [comment]
Ok I will decide what to do. Thanks for the information

**Comment by NBAMj** [comment]
What is the status on this issue?
Have you added **json5** support?

**Comment by supertorpe** [comment]
An easy workaround: implement a pipe that inherits from TranslatePipe and takes into account the arrays:

`import { PipeTransform, Pipe, Injectable } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

@Injectable()
@Pipe({ name: 'translatext', pure: false })
export class TranslatextPipe extends TranslatePipe implements PipeTransform {
    transform(query: string, ...args: any[]): any {
        const result = super.transform(query, args);
        if (result instanceof Array) {
            return result.join('\n');
        } else {
            return result;
        }
    }
}
`
...then in the template:   {{ 'mykey' | translatext }}

**Comment by Iv3li0s** [comment]
Base on supertorpe comment. But no need to create another pipe ( which not include query translate params )
You can directly override TranslateParse. 

```
export function createTranslateParser() {
  return new TranslateAppParser();
}

@NgModule({
  declarations: [
   ...
  ],
  imports: [
  ...
    // Translate
    HttpClientModule,
    TranslateModule.forRoot({
      parser: { provide: TranslateParser, useFactory: (createTranslateParser)}
    }),
...
```
```
import {Injectable} from '@angular/core';
import {TranslateDefaultParser} from '@ngx-translate/core';

@Injectable()
export class TranslateAppParser extends TranslateDefaultParser {

  getValue(target: any, key: string): any {
    target = super.getValue(target, key);
    if (target instanceof Array) {
      target = target.join(' ');
    }
    return target;
  }
}
```
