### ISSUE TITLE
this.onLangChange.emit is not a function

### ISSUE THREAD

**Issue by vulcaryn** [ocombe/ng2-translate#34]
Hi,

Using ng2-translate 1.7.0 i have the followinf error when I set language : 
"this.onLangChange.emit is not a function"

The bug doesn't stop angular executing or translater job.

Thanks

**Comment by ocombe** [comment]
Thanks, probably a change with beta 6 that wasn't caught by my tests. I'll check this.

**Comment by ocombe** [comment]
I cannot reproduce this error, could you make me a plunkr ?

**Comment by ocombe** [comment]
Closing this by lack of response, if someone has more info and the same bug, let me know !
