### ISSUE TITLE
How to use the TranslatePipe using rc-7

### ISSUE THREAD

**Issue by RaduMirsk** [ocombe/ng2-translate#341]
1) Is it possible to chain pipes after the translate pipe? I need to translate and split a date but the html seems to ignore the second pipe. The code looks like this:
`<p class="something">{randomData.nextDate | translate | split }}</p> `
 where split is a custom pipe

2) Besides this I tried to the TranslatePipe with a param but the html is ignoring it as well.
`<p class="something">{{'something' | translate:{value: randomData.nextDate} }}</p> `

**Comment by SamVerschueren** [comment]
It should work, although not sure what `randomData.nextDate` actually returns? A plunkr showing the issue would be nice. You could start from [this](http://plnkr.co/edit/btpW3l0jr5beJVjohy1Q?p=preview) one if you want.

**Comment by onedotover** [comment]
Params don't appear to be working. I used the Plunker you referenced above as a quick example. Or am I using the incorrect format?

http://plnkr.co/edit/zD9bVaslAJfP3PVb2xNu?p=preview

**Comment by ocombe** [comment]
Good catch @onedotover, fixing this immediately

**Comment by cbeldacap** [comment]
@onedotover that Plunker you referenced is not working. Could you finally run it properly?

thnx in advance

**Comment by onedotover** [comment]
Yes thanks! I pulled down your update right after you fixed it and it works great!

**Comment by ocombe** [comment]
Good, closing this then
