### ISSUE TITLE
JSON Language File Regex Does Not Match Properly

### ISSUE THREAD

**Issue by bulletinmybeard** [ocombe/ng2-translate#342]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x ] support request => check the FAQ and search github for a similar issue before submitting
[x ] feature request
```

**Current behavior**
The current regex replace for the key and the value doesn't work properly 

**Expected/desired behavior**
I would like to use single or double quotes or no quotes for the key

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

**What is the expected behavior?**
Using single or double quotes and leave the quotes for the key

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ng2-translate version:** 4.0.1

* **Angular version:** 2.3.0-rc.0
 
* **Browser:** [all] 
 
* **Language:** [all] 

Here are two new expressions to match single and double quotes  and trim the content from the JSON value:

```var validArgs = args[0]
                    .replace(/(\'|\")?([\w]+)(\'|\")?(\s)?\s{0,}:/g, '"$2":')
                    .replace(/:(\s){0,}?(\'|\")\s*(.*?)\s*(\'|\")/g, ':"$3"');
```

**Comment by SamVerschueren** [comment]
I might not entirely understand what you want. Could you give an example of what you want? Do you mean that in the translation file, you want to be able to use single quotes or no quotes at all? If that is what you mean, then no. Because that's not valid json. Have a try at http://jsonlint.com/. But if you really want that you could easily create your own [custom loader](https://github.com/ocombe/ng2-translate#write--use-your-own-loader).

If you mean something else, please eloborate :).

**Comment by bulletinmybeard** [comment]
That's exactly what I meant. Thanks for the tip with the custom loader. I will try it with that.

cheers

**Comment by ocombe** [comment]
Closing this now, let me know if I should reopen it.

**Comment by bulletinmybeard** [comment]
Thanks @ocombe, it's okay for now. My solution is to use a helper function as middleware to reformat the JSON I grab from a service provider before I pass it through ng2-translate to make sure it's valid.
