### ISSUE TITLE
Add TranslatePoLoader

### ISSUE THREAD

**Issue by biesbjerg** [ocombe/ng2-translate#343]
I read in an Ionic blog comment that you'd include loaders in the docs, if anyone wrote some, so thought I'd share.

The loader is for Gettext po files: https://www.npmjs.com/package/ng2-translate-po-loader

**Comment by ocombe** [comment]
Awesome thanks ! I'll add it !

**Comment by biesbjerg** [comment]
Thanks!

I decided to publish under a name namespace instead, can you update the README?

The new package location is https://www.npmjs.com/package/@biesbjerg/ng2-translate-po-loader

Sorry for the trouble!

**Comment by ocombe** [comment]
Okay, next time do a PR that's easier to merge :)
