### ISSUE TITLE
Generate random text for testing purpose

### ISSUE THREAD

**Issue by n00dl3** [ocombe/ng2-translate#349]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ x ] feature request
```

**Current behavior**
It is difficult to know if a text is passed through the `TranslatePipe`. We can see there is no translation for `{{"my Text"|translate}}` but nor for `{{"my Text"}}`.

**Expected/desired behavior**
if by passing a parameter like `TranslateModule.forRoot({useRandomText:true})` we could generate some random text from every text piped by `translatePipe` or `TranslateService` we could easily see that some text is not translated at all.

eg : `<span>{{"my text"|translate}}<span>` would produce -for example, the sha1 hash of the text- : `<span>c3599c11e47719df18a2448690840c5dfcce3c80</span>`. And `<span>{{"my text"}}</span>` would just produce `<span>my text</span>`

**What is the motivation / use case for changing the behavior?**
Finding non-piped text is very hard... :cry:

**Comment by n00dl3** [comment]
hmm... I realize that could be done removing every translations and using the `MissingTranslationHandler`....

**Comment by ocombe** [comment]
It's cool that you found a solution :)
