### ISSUE TITLE
Systemjs + typescript import

### ISSUE THREAD

**Issue by jingignoli** [ocombe/ng2-translate#35]
Hi,

Thanks for your works on this library.
I try to load it from Systemjs/jspm without using gulp or other build tools just the plugin-typescript https://github.com/frankwallis/plugin-typescript

I add this package instruction to my config.js
``
"ng2-translate": {
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
``

I import with:
 
``
import {TranslateService} from 'ng2-translate/ng2-translate'
``

But i have got this exception:

``
Uncaught SyntaxError: Unexpected token =
translate.service.ts:179 Uncaught SyntaxError: Unexpected token =
@ system.src.js:4892(anonymous function) 
@ system.src.js:4892(anonymous function) 
@ system.src.js:4892(anonymous function) @ system.src.js:4892
Uncaught SyntaxError: Unexpected token =
	Evaluating http://localhost:3000/dist/bundle.js
	Error loading http://localhost:3000/dist/bundle.js
	Error loading http://localhost:3000/app/app.ts
``

Any idea ? 

Julie.

**Comment by ocombe** [comment]
You shouldn't use defaultExtension `ts` since I don't push the `ts` source files to npm. It should be `js`.

**Comment by jingignoli** [comment]
Wooo this was my problem, i have install via github instead of npm !
Thank you for your support.

Julie.

**Comment by ocombe** [comment]
ahah ok, yeah that couldn't end well :)
npm only is the default for Angular 2 !
