### ISSUE TITLE
Version 4.2.0 introduces a breaking change: shouldn't it be a major version increase?

### ISSUE THREAD

**Issue by Gustorn** [ocombe/ng2-translate#352]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
The introduction of the `TranslateParser` led to a dependency injection error where Angular 2 could not find a provider for said type. Adding the following line to the AppModule providers fixes the problem:
```
 { provide: TranslateParser, useClass: DefaultTranslateParser },
```

Apart from the the real-world breakage, the public-facing API change would warrant a major version increase in and of itself (based on semver versioning rules).

**Expected/desired behavior**
Using the semver compliant `^4.0.0` version number in `package.json` shouldn't break existing builds.

**Please tell us about your environment:**

* **ng2-translate version:** 4.0.1 -> 4.2.0

* **Angular version:** 2.2.4
 
* **Browser:** all
 
* **Language:** all

**Comment by ocombe** [comment]
Hmm I'm using this version and it did not generate a dependency injection error in my project, and I haven't changed my imports.
If it does then it's bug, but I don't consider adding the TranslateParser a breaking change because it does the same as before (you can just replace it with your own now) and the defaults  should make it backwards compatible. That's a minor update in semver (new feature but backwards compatible).

Can you show me how you import the TranslateModule into your project ?

**Comment by Gustorn** [comment]
You're right: I didn't import `TranslateModule` into my project directly. I've been wrapping `ng2-translate` in our own internal representation and the library remained functional after Angular 2's module change, so I never added it. This markes the DI question solved.

That being said, this is still a breaking change if someone was setting up their `TranslateService` manually:
Imagine the following lines in AppModule's providers:

```ts
{ provide: TranslateLoader, useFactory: (http: Http) => new LocalizationLoader(http), deps: [Http] },
{ provide: MissingTranslationHandler, useClass: MyTranslationHandler },
{
    provide: TranslateService,
    useFactory: (loader: TranslateLoader, handler: MissingTranslationHandler) => new TranslateService(loader, handler),
    deps: [TranslateLoader, MissingTranslationHandler]
}
```

This would fail to compile since  `TranslateService` would expect a `TranslateParser` as its second argument, but I admit that this is a fairly niche use-case.

**Comment by ocombe** [comment]
That's true, but like you said it's not really likely, if you don't use the service you don't use the lib (in my opinion), this is where all the value of the lib is :)
And you should expect that it could break and not use `^` in your package.json ;)

**Comment by Gustorn** [comment]
Fair enough
