### ISSUE TITLE
Webpack loading, not finding files.

### ISSUE THREAD

**Issue by Spittal** [ocombe/ng2-translate#36]
Hey, I'm using webpack to load my TS files and it spits out some errors when I load this package.
![screen shot 2016-02-16 at 2 46 25 pm](https://cloud.githubusercontent.com/assets/1229177/13093812/13df459a-d4bc-11e5-9e7b-33b0fcc53322.png)

I'm including the file like this
```js
import {TranslateService} from 'ng2-translate';
```

and my webpack TS-loader configuration looks a little something like this
```js
{ test: /\.ts$/, loader: 'ts-loader', exclude: [ /\.(spec|e2e|async)\.ts$/ ] },
```

I'm relatively new to typescript, and I imagine this has something to do with typings? Do I need to do anything special typings wise for this package?

**Comment by ocombe** [comment]
Hmm what version of ng2 translate & angular 2 are you using?

**Comment by Spittal** [comment]
"angular2": "2.0.0-beta.3"
"ng2-translate": "^1.7.0"

**Comment by ocombe** [comment]
Can you make me a repo with the problem ? I tried with my webpack starter and it worked without any warning.

**Comment by Spittal** [comment]
Take a look here

https://github.com/Spittal/ng2-translate-test

**Comment by ocombe** [comment]
Stupid me, I changed the sourcemaps to inline for forgot to include the source code...
Anyway, try 1.7.2, it should fix the problem for you :)

**Comment by Spittal** [comment]
Thanks!
