### ISSUE TITLE
How do i use multiple pipes in traslation?

### ISSUE THREAD

**Issue by tsm91** [ocombe/ng2-translate#361]
Lets say i have a pipe for conditionally formatting various values (time, numbers) based on locale / whatever else. The point is you have to do smth like `value | pipe`. After its done, you need to pass it as translate pipe param. So `'KEY' | translate:({v: value | pipe})`. I usually wrap any param that goes to translate with `<b>{{v}}</b>` so it should also work as an `innerHTML` binding.

How do you do this?

**Comment by tsm91** [comment]
Sorry, this was a stupid question. I can always inject the pipe and do it programatically.

`<div *ngIf="state.hasError('invalidTime')" class="form-control-feedback" [innerHTML]="'FORM.ERR_TIME' | translate:({v: dateFormatP.transform(state.getError('invalidTime').reqMinHour, state.getError('invalidTime').is24Hrs ? 'HH:mm' : 'hh:mmA'), v2: dateFormatP.transform(state.getError('invalidTime').reqMaxHour, state.getError('invalidTime').is24Hrs ? 'HH:mm' : 'hh:mmA')})"></div>`

**Comment by marcalj** [comment]
With angular-translate (AngularJS) you could write translation strings with pipes, like: ```hello {{ value | number }}``` it isn't possible right now?
