### ISSUE TITLE
Universal - Response with status: 200 Ok for URL: null

### ISSUE THREAD

**Issue by dottodot** [ocombe/ng2-translate#362]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When navigating my app it works fine but if I refresh the page the server side throw on error of 

```
EXCEPTION: Response with status: 200 Ok for URL: null


/Users/marcuswilliams/Hosts/bailey-uni/node_modules/zone.js/dist/zone-node.js:158
                        throw error;
                        ^
Response with status: 200 Ok for URL: null
```

I've put `UniversalModule` as the last import as suggested by other posts 

**Expected/desired behavior**
Not to throw error

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

This is my Node Module setup

```
export function createTranslateLoader(http: Http) {
  return new TranslateStaticLoader(http, './assets/i18n', '.json');
}

@NgModule({
  bootstrap: [AppComponent],
  imports: [
    HttpModule,
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    FormsModule,
    RouterModule.forRoot([], { useHash: false }),
    SharedModule,
    AppModule,
    UniversalModule
  ],
  providers: [

  ]
})
```

**Please tell us about your environment:**

* **ng2-translate version:** x.x.x
4.2.0
* **Angular version:** 2.0.0-rc.X
 2.1.2
* **Browser:** [all ] 
 
* **Language:** [TypeScript]

**Comment by ocombe** [comment]
Hello,
Make sure that you load UniversalModule before TranslateModule, so that it replaces Http by its own

**Comment by ocombe** [comment]
Another solution is to use this loader (that uses "fs" instead of Http) on the server side: https://gist.github.com/ocombe/593d21598d988bf6a8609ba5fc00b67e

And the static loader on the client side

**Comment by Perezmarc** [comment]
when using the universalLoader, it cant find throws me 'no such file or directory, open 'assets/i18n/en.json'' in the server... but in client is working.

**Comment by JohnGalt1717** [comment]
I'm still having this with the .NET JavaScriptServices. All HTTP calls come back with: Response with status: 200 Ok for URL: null 

It doesn't look like a solution here really. How does one get this working?

**Comment by ocombe** [comment]
Did you use a different loader (that doesn't use http) for universal like suggested above?

**Comment by JohnGalt1717** [comment]
Well that's great in theory. But it isn't clear if it comes before or after Universal in the module etc.

**Comment by ocombe** [comment]
Here are my server files for a project that I did with universal: https://gist.github.com/ocombe/8af9d555ab2da45cd1042ef2ccb0ef6b
It's a bit old, but it should help you

**Comment by JohnGalt1717** [comment]
Thanks! Anyone know if angular 4 solves this properly?

**Comment by Shifs** [comment]
@ocombe : I am not using UniversalModule, still it is giving me the same error

**Comment by Shifs** [comment]
@ocombe My code is
 imports: [
        NativeScriptModule,
        //RadioButtonModule,
       
        NativeScriptUIListViewModule,
        NativeScriptFormsModule,
        NativeScriptUISideDrawerModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forRoot(routes),
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [Http]
            }
        }),
         NativeScriptHttpModule,
    ],

and I have a function
export function createTranslateLoader(http: Http) {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
but I am getting the same error . 

    "@ngx-translate/core": "^7.1.0",
    "@ngx-translate/http-loader": "^0.1.0",

**Comment by ocombe** [comment]
You should probably load `NativeScriptHttpModule` before the `TranslateModule`, but other than that, I'm not sure how the `NativeScriptHttpModule` works

**Comment by Shifs** [comment]
Now I get the below error
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'get' of undefined
JS: TypeError: Cannot read property 'get' of undefined
JS:     at TranslateHttpLoader.module.exports.TranslateHttpLoader.getTranslation (file:///data/data/org.nativescript.sai/files/app/bundle.js:48300:25)
JS:     at TranslateService.module.exports.TranslateService.getTranslation (file:///data/data/org.nativescript.sai/files/app/bundle.js:305:55)
JS:     at TranslateService.module.exports.TranslateService.retrieveTranslations (file:///data/data/org.nativescript.sai/files/app/bundle.js:292:87)
JS:     at TranslateService.module.exports.TranslateService.use (file:///data/data/org.nativescript.sai/files/app/bundle.js:266:28)
JS:     at new LoginComponent (file:///data/data/org.nativescript.sai/files/app/bundle.js:14038:24)
JS:     at createClass (file:///data/data/org.nativescript.sai/files/app/vendor.js:11328:26)
JS:     at createDirectiveInstance (file:///data/data/org.nativescript.sai/files/app/vendor.js:11152:37)
JS:     at createViewNodes (file:///data/data/org.nativescript.sai/files/app/vendor.js:12501:49)
JS:     at createRootView (file:///data/data/org.nativescript.sai/files/app/vendor.js:12406:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.sai/files/app/vendor.js:13537:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.sai/files/app/vendor.js:12998:12)
JS:     at ComponentFactory_.module.exports.ComponentFactory_.create (file:///data/data/org.nativescript.sai/files/app/vendor.js:10343:46)
JS:     at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.sai/files/app/vendor.js:3924:29)
JS:     at ViewContainerRef_.module.exports.ViewContainerRef_.createComponent (file:///data/data/org.nativescript.sai/files/app/vendor.js:10543:62)
JS:     at PageRouterOutlet.module.exports.PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.sai/files/app/vendor.js:30208:55)
```
