### ISSUE TITLE
translate Pipe not working  with [innerHTML]

### ISSUE THREAD

**Issue by xcuben** [ocombe/ng2-translate#365]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Hi, 
while testing the code above:
```
<h2>{{ 'HOME.TITLE' | translate }}</h2>
<h2 [innerHTML]=" 'HELLO.TITLE' | translate "></h2>
```
I encountered the following Problem:
* the first line is doing the expected translation without any problems .
* the second line is returning a "HELLO.TITLE" in the HTML template

am I using that in the right way ? and if no what for solution(s) could you recommend to use second-line alternative.

Thanks.

* **ng2-translate version:** 4.2.0

* **Angular version:** 2.3.0
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0.3]

**Comment by SamVerschueren** [comment]
Works perfectly fine. Here's a plunkr that shows what you want http://plnkr.co/edit/84KPA1l7cPCyWo3kEGVp?p=preview.

So if you could create a plunkr with a minimalistic example that fails, that would be nice.

**Comment by xcuben** [comment]
@SamVerschueren : thanks a lot , it s now working fine for me too.

I think I Just had some wrong configuration in my AppModule
