### ISSUE TITLE
how to retain original innerText while missing translator?

### ISSUE THREAD

**Issue by fishen** [ocombe/ng2-translate#369]
The key name is impertinent, I implemented MissingTranslationHandler and got default value from interpolateParams:

```
export class MyMissingTranslationHandler implements MissingTranslationHandler {
    handle(params: MissingTranslationHandlerParams) {
        let defaultValue = params.interpolateParams ? params.interpolateParams['default'] : null;
        defaultValue = defaultValue || params.key;
        return defaultValue;
    }
}
```
`<h1 [translate]="'login'" [translateParams]="{default:'登录'}">登录</h1>`

It works, but too complicated.Is there a simpler way to implement it? like following code:

`<h1 [translate]="'login'">登录</h1>`

**Comment by ocombe** [comment]
If you want to keep the original text with the directive when the translation is missing, don't set the key (or set the key to the content value that you want).

For example:
```html
<h1 translate>登录</h1>
```

This will use the content as a key (in this case `登录`), and when the translated value is missing, it will keep the original content until it is available.

**Comment by fishen** [comment]
Thanks! @ocombe. The drective 'translate' solved this problem, but it requires that the key and the text are equal. I think an alias might be more generic while getting the translator from api.
