### ISSUE TITLE
Peer Dependency

### ISSUE THREAD

**Issue by DanielSchuech** [ocombe/ng2-translate#38]
Its a bit similar to #37.

I want to update to angular 2 beta 7. They ve updated RXjs to beta 2. They depend on version two and you peer dependency depend on beta 0. So i cant resolve this on my own. I would recommend to set peer dependency to ~beta.0. Then you can support different versions of angular 2 and the developer needs to resolve the peer dependency by his own.

Greetings,
Daniel

**Comment by ocombe** [comment]
Yes I'm gonna do that as soon as I'm back from Amsterdam (for ng nl) later
today :-)

Le dim. 21 févr. 2016 14:01, DanielSchuech <notifications@github.com> a
écrit :
