### ISSUE TITLE
Can't find translate pipe in unit test

### ISSUE THREAD

**Issue by mbakker96** [ocombe/ng2-translate#381]
```
[ ] bug report => check the FAQ and search GitHub for a similar issue or PR before submitting
[ x ] support request => check the FAQ and search GitHub for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I get an HTML error when I'm trying to test an Angular/Ionic component. This is because he can't find the translate pipe because it is not injected. 

I'm using ng2-translate 5.0.0, the latest Ionic 2 RC and the latest Angular 2 Final. I'm running my unit tests with Karma and Jasmine. 

I found on the internet something like `PLATFORM_PIPES` but I think that is deprecated. 

Does someone know how I can import the translate pipe?

**Comment by ocombe** [comment]
Just import the module into your testbed and it should work

**Comment by mbakker96** [comment]
O that was simple ;) Thanks!
