### ISSUE TITLE
getBrowserLang() return wrong language

### ISSUE THREAD

**Issue by Robouste** [ocombe/ng2-translate#384]
**I'm submitting a ...** 
```
[x] bug report 
[ ] support request
[ ] feature request
```

**Current behavior**

```
constructor(translate: TranslateService) {
	let browserLang = translate.getBrowserLang();
	console.log("browser lang : " + browserLang); //returns fr with chrome change to english
}
```

**Expected/desired behavior**

getBrowserLang should return the actual browser language.

**Reproduction of the problem**

Chrome was in french. I changed this to english and getBrowserLang keep returning fr

**What is the expected behavior?**

getBrowserLang should return the actual browser language.

**What is the motivation / use case for changing the behavior?**

Provide the initial app state in the user language

**Please tell us about your environment:**

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.4.0
 
* **Browser:** Chrome Version 55.0.2883.87 m (64-bit)
 
* **Language:** TypeScript 2.0

**Comment by SamVerschueren** [comment]
It uses [window.navigator.languages](https://github.com/ocombe/ng2-translate/blob/master/src/translate.service.ts#L470) to detect the user language. My chrome is in english, but it returns `nl` as main language. So apparently those two are not 1:1 coupled.

**Comment by Robouste** [comment]
Ok, from what I learn, their is no way to precisely define the browser language using only javascript. This need to be done serverside since it's in the HTTP request header.

Thank you

**Comment by ocombe** [comment]
yes, javascript is not 100% reliable for this, it's usually a good approximation but if you really want to know the language you should detect is server side

**Comment by azzimuth** [comment]
I've noticed that it takes the first language in the list in Chome:
`var browserLang = window.navigator.languages ? window.navigator.languages[0] : null;`

For example, Chrome is on Norwegian but it's English on top of the list, so `getBrowserLang` returns English.
