### ISSUE TITLE
Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by denu5** [ocombe/ng2-translate#387]
I had a problem setting a custom Factory in TranslateModule.forRoot() using angular CLI, I think this problem is related to the following topic: https://github.com/angular/angular-cli/issues/3707
 
This issue can be reproduced when you use the latest angular-cli and try to "ng serve"

> 
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 28:19 in the original .ts file), resolving symbol AppModule

**Comment by Fatslug** [comment]
amen. 
here here.

**Comment by mmathys** [comment]
can confirm. 👍  same error

**Comment by SamVerschueren** [comment]
Do you use a function instead of a fat-arrow? See [documentation](https://github.com/ocombe/ng2-translate#aot).

**Comment by acivan** [comment]
@SamVerschueren  👍

**Comment by denu5** [comment]
@SamVerschueren 

yes this worked. thanks. i have taken the solution from your example here:

[https://github.com/SamVerschueren/ng2-translate-aot-test/blob/2b3feceee8e288ea6480eaa5bc9ab64906630887/src/app/app.module.ts](https://github.com/SamVerschueren/ng2-translate-aot-test/blob/2b3feceee8e288ea6480eaa5bc9ab64906630887/src/app/app.module.tsl)

**Comment by SamVerschueren** [comment]
Cool. Glad it's resolved now!
