### ISSUE TITLE
Support Request - Is there a way to include html in translate string?

### ISSUE THREAD

**Issue by SamFarrington** [ocombe/ng2-translate#395]
**I'm submitting a ...**  (check one with "x")
```
[X] support request => check the FAQ and search github for a similar issue before submitting
[X] feature request
```

**Expected/desired behavior**

I was wondering if there was a way to include html in a translate string?

The reason I would like this functionality is that I want to apply some styling to certain parts of a string to be translated:

```json
  "DELETE_USER": {
    "TITLE": "Delete user <span class="headerEmphasis">{{username}}</span>",
    "INTRO": "Please confirm that you wish to delete user <span class="headerEmphasis">{{username}}</span>",
    "DELETE_USER_BUTTON": "Delete User",
    "CANCEL_BUTTON": "Cancel"
  },
```

**Comment by SamVerschueren** [comment]
[See the docs](https://github.com/ocombe/ng2-translate#5-use-html-tags)
