### ISSUE TITLE
[HELP] Translate urls

### ISSUE THREAD

**Issue by apavillet** [ocombe/ng2-translate#40]
Hi and thanks for the plugin, works great in template

Is it possible and could you show an exemple of how you would translate urls ?

Say we have a route defined this way :

`{ path: '/login', component: LoginFormCmp, as: 'Login' }`

Since translate.get returns an observable i cannot figure a way to do it

Thanks

**Comment by ocombe** [comment]
The route definitions are in a decorator, and not in the component itself, so I don't think that you can access the provider in the decorator.
You could probably create an instance of the TranslateService yourself (without using angular's DI), but then the observable would get in your way. You would have to wait for the new 'instant' translate method that I will add soon.

And even then, I'm not sure if it would work correctly.

**Comment by apavillet** [comment]
It should work if it returns it as a value, not using the decorator but routeConfig in the constructor.

Do you have a estimate release date for this feature?

Thank you

**Comment by ocombe** [comment]
No idea, maybe tonight or tomorrow.
You can test something similar using this: https://github.com/ocombe/ng2-translate/issues/20#issuecomment-187062951

**Comment by DanielSchuech** [comment]
Are you sure that routeConfig is available in the constructor. The documentation tells that routeConfig is an decorator. So my tsc displays an error if i try that.

When you are loading the translation via the staticfileloader it isn't possible to get the translation without an observable. The request is async. So you need to wait for the response.

**Comment by ocombe** [comment]
> The route definitions are in a decorator, and not in the component itself, so I don't think that you can access the provider in the decorator.

**Comment by apavillet** [comment]
I "think" ( please note it's untested ) we could configure routes in controller

https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L139

`router.config([
   *   { 'path': '/', 'component': IndexComp },
   *   { 'path': '/user/:id', 'component': UserComp },
   * ]);`

**Comment by DanielSchuech** [comment]
Yeah interesting ;) So if that works then it shouldn´t matter if the translatedKey is an observable or not. Or am I wrong?

The behavior of the site could may crazy. In the default routeConfig the current route given by the url does not exists. So the router would navigate to the default route. Then the observable would be executed. The new routes will be apllied and a renavigate will be done. So your now on the correct view. Maybe a little flash ;)

Are you going to use the staticfilesloader? Because then i am really interesting if the instant translate would work. I can´t believe that at the moment ;)

**Comment by apavillet** [comment]
What I planned to do was configuring my routes in the constructor like this (might not be the right syntax):

`router.config([
{'path': _translateService.get('/login'), component:IndexCmp}
])`

With the observable I cannot figure a way to return the value, and it fails. 
Maybe I'm doing it wrong and would be happy to be corrected but I thought that returning it directly would solve half the problem ;)

**Comment by DanielSchuech** [comment]
With Observables you would need collect at first all your translation and call then the route config
```js
let login: Observable<string> = translateService.get('/login');
let logout: Observable<string> = translateService.get('/logout');

login.combineLatest(logout).subscribe((translations: string[]): => {
  router.config([ 
    {'path': translations[0], component:IndexCmp},
    {'path': translations[1], component:IndexCmp2}
  ])
});
```

**Comment by apavillet** [comment]
Maybe using ngInit to collect them would help then, I cannot figure out when the constructors is called in that lifecycle

https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

**Comment by DanielSchuech** [comment]
I doen´t think that the time when route.config is the problem. The constructor needs to be called before any other method otherwise there are missing dependencies and it wouldn´t be a constructor ^^.

The more interesting points is to get the translation in time. A file request via the staticfilesloader needs some time and you need to wait for the response. The other option is to collect the translations directly in the ts(js) file and set them via translateService.setTranslation. But this is not maintainable.

**Comment by apavillet** [comment]
@ocombe 

I'm trying the instant feature and I'm getting an error while doing : this._translateService.instant('LOGIN')

<code>EXCEPTION: TypeError: Cannot convert undefined or null to object in [null]</code>

The error is happening here :

<code> TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at step (http://localhost:5555/node_modules/ng2-translate/src/translate.parser.js:37:20)
    at Parser.flattenObject (http://localhost:5555/node_modules/ng2-translate/src/translate.parser.js:48:9)
    at TranslateService.getParsedResult (http://localhost:5555/node_modules/ng2-translate/src/translate.service.js:199:46)
    at TranslateService.instant (http://localhost:5555/node_modules/ng2-translate/src/translate.service.js:248:21)
    at AppCmp.ngOnInit (http://localhost:5555/app/components/app.js:44:44)</code>

**Comment by DanielSchuech** [comment]
@apavillet I think the translation file hasn´t finished loading. 
Please check the following: Set a breakpoint to translate.service.js line 199 and have a look to this.translations. Is it  `{}`?

You are requesting a key before the translation file finished loading and that will probably not work.

**Comment by apavillet** [comment]
Yet it is, the translations file are loaded async too I guess ?

**Comment by DanielSchuech** [comment]
Correct. Http request are always async. Otherwise would the duration for loading a website increase.

Have you tried you tried my idea with setting the route config after the translation observable has resolved?

**Comment by apavillet** [comment]
Ok so for anyone interested I made it work.
This is not beautiful and I would love improvements but it does work for now :

`// Subscribe to observable, @all : can it be done somewhere else, or anyway else ?
    this._translateService.use(userLang).subscribe(
      data => this.configRoute()
    );`

Use your function and do something like this :
` { path: '/:lang/'+this._translateService.instant('LOGIN_URL'), component: LoginFormCmp, as: 'Login' },`

**Comment by ocombe** [comment]
Oh nice, I didn't think it was possible that easily :-)

**Comment by apavillet** [comment]
It's working fine for now, only problem I had was with the first child route, I had to define the first one in the decorator, without translations ( which is ok since the path is / )
`@RouteConfig([
  { path: '/', component: HomeCmp, as: 'Home', useAsDefault: true }
])`

The problem is RouterLink in template do not seem to recognize it otherwise, but it might be something I'm doing wrong :)

**Comment by apavillet** [comment]
For anyone trying this you might have a problem with your html trying to find routes before they are initiliazed.
I had to add an *ngIf with a boolean parameter waiting for routes to be loaded.

@ocombe You can close this if you need or keep it as a tutorial :)
