### ISSUE TITLE
Encoding difficulties

### ISSUE THREAD

**Issue by alienlike** [ocombe/ng2-translate#406]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

My translated text has encoding issues, evidenced by the HTML character code 65533 that appears. Embedding the text without translation works fine.

This code yields the result shown below:
```
<span [innerHTML]="'low_vision_users'|translate"></span> <!-- innerHTML w/ pipe -->
                        {{'low_vision_users'|translate}} <!-- pipe -->
                        Los usuarios de baja visión <!-- no translation -->
```
![image](https://cloud.githubusercontent.com/assets/1070664/22381634/5f5408e6-e490-11e6-88ff-e32619518134.png)

My Angular template has a `<meta charset="utf-8">` tag, and my `es.json` is UTF-8 encoded.

**Expected/desired behavior**

I don't expect to see HTML character code 65533 for accented characters.

Current workaround is to use `innerHTML` in conjunction with HTML-encoded text in my `es.json`, but this is more effort than should be necessary.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:btpW3l0jr5beJVjohy1Q).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.4.4

* **Browser:** Chrome 55
 
* **Language:** TypeScript 2.0

**Comment by SamVerschueren** [comment]
Just put `Los usuarios de baja visión` that as translation value of that key and use a normal translate, not an `innerHTML` translate. No?

**Comment by ocombe** [comment]
The problem is either that you serve json files badly encoded from your server, or that your index.html file has no charset defined. But I can assure you that it has nothing to do with the lib :)

**Comment by alienlike** [comment]
I have no doubts about the library! My index.html does have charset defined, so I took a closer look at the JSON file encoding. Even thought it was set to UTF-8, I tried changing the encoding from UTF-8 to UTF-8 BOM, and then back again to UTF-8. This resolved the problem, whatever it was.
