### ISSUE TITLE
Using an extended Http class with header options to deal with the controllers instead of using a Json file

### ISSUE THREAD

**Issue by CHOUAIAR** [ocombe/ng2-translate#407]
Hello All,
I have a question about a change I made, I get my labels using a controller not a Json file, so I needed to initialize option in the header of each http request, so I create a new class extending the Http, to use the new Class in the I create a new Loader implementing the TranslateLoader and it uses the the extended Http Class instead of the basic. Does my solution is correct or there is an easier way to do so?

Thanks in advance.

**Comment by ocombe** [comment]
Hello, yes it is the way to do it :-)

**Comment by CHOUAIAR** [comment]
Thank you @ocombe  :)
