### ISSUE TITLE
Error when changing pathroute

### ISSUE THREAD

**Issue by thigrand** [ocombe/ng2-translate#408]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ x ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
When i use TranslateModule imports to change pathroute:
```   
TranslateModule.forRoot({
  provide: TranslateLoader,
  useFactory: (http: Http) => new TranslateStaticLoader(http, './translation/i18n', '.json'),
  deps: [Http]
})
```
i get an error:
> ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 44:19 in the original .ts file), resolving symbol AppModule in (...)/src/app/app.module.ts

**Expected/desired behavior**
i want to resolve the error

**Please tell us about your environment:**

* **ng2-translate version:** 
"^5.0.0",

* **Angular version:** 2.0.0-rc.X
 "^2.4.5"
* **Browser:** [all | Chrome XX  ] 
 Chrome 55
* **Language:** [ TypeScript X.X] 
"~2.1.5"

**Comment by SamVerschueren** [comment]
It looks like you are using AoT. Check out the [AoT section](https://github.com/ocombe/ng2-translate#aot). You have to use a function instead of a fat-arrow (lambda) function.

**Comment by thigrand** [comment]
It works, thanks. I tried it before, but apparently i made some mistakes.
