### ISSUE TITLE
Exception if translation key is missing 

### ISSUE THREAD

**Issue by hpop** [ocombe/ng2-translate#46]
If a translation key is missing in a language, that is not set as `defaultLang` I get following exception:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at step (http://localhost:5555/node_modules/ng2-translate/src/translate.parser.js:37:20)
    at Parser.flattenObject (http://localhost:5555/node_modules/ng2-translate/src/translate.parser.js:48:9)
    at TranslateService.getParsedResult (http://localhost:5555/node_modules/ng2-translate/src/translate.service.js:199:46)
    at TranslateService.get (http://localhost:5555/node_modules/ng2-translate/src/translate.service.js:229:52)
```

It seems that the code is trying to access the key of the default language as a fallback, without loading the language file. 

I am not sure how to handle it. Maybe it is a good idea to remove the fallback and add the ability to return a string in the `MissingTranslationHandler`.

**Comment by ocombe** [comment]
Ah yes, this looks like a corner case that I need to fix, thanks

**Comment by ribizli** [comment]
This issue is eliminated if my PR #49 will be accepted.

**Comment by DanielSchuech** [comment]
We should maybe discuss about this behaviour. What should happen if a key doesn´t exist in the currentlang but in the default lang?
* show translation from default language
* call Missing Translation Handler


I would prefer the second option. And then maybe extend the Missing Translation Handler and give the current language as second parameter to the handle function

**Comment by ocombe** [comment]
Yes, I think the behavior should be:
missing value for this key? --> missing translation handler (which should be able to be sync OR async, I need to improve it) --> still missing ? fallback lang --> still missing ? return the key instead

**Comment by ribizli** [comment]
The current implementation (state after PR) is: `current lang -> default lang -> missing handler + key` (the `MissingTranslationHandler` is called only after the default language fails).

Wouldn't be a useful feature to let the `MissingTranslationHandler` return a fallback value, too?

**Comment by DanielSchuech** [comment]
Yes thats what ocombe suggested

**Comment by hpop** [comment]
I would just call the `MissingTranslationHandler` as well. If we are able to set the value there, we still can set the translation from the default language.

**Comment by ribizli** [comment]
I prefer (if it matters ;) ) the first fallback to be the default language, and only after it fails the `MissingTranslationHandler` kicks in, e.g. wrapping the key with ?key?, or similar.

**Comment by ocombe** [comment]
Why is that ?
If you don't have a missing translation handler defined it will still just use the fallback language, but if you define a handler it's better to have it first because you might want to do something special before anything else.

**Comment by ribizli** [comment]
There might be some default strings, which are the same in all languages. So first fall back to the default (the only one where it is defined) language for it.

**Comment by DanielSchuech** [comment]
This could be modelled with an empty missing translation handler which allways returns undefined.

With your idea the case that the translation is only missing in a non default language cannot be handled by the developer.

**Comment by ribizli** [comment]
But with the 'empty' `MissingTranslationHandler` how can you handle missing default language keys? We both have arguments ;)

**Comment by DanielSchuech** [comment]
Yes you are right ;)

**Comment by ocombe** [comment]
In the MissingTranslationHandler you can check the keys in any language that you want

**Comment by ribizli** [comment]
You need to get access to `TranslateService` for that, don't you? Anyway the handler in the current form has not to many feature. Providing reference to translations would be a good point.

**Comment by ocombe** [comment]
Closed in 1.9 ! Thanks @ribizli

**Comment by architruc** [comment]
Hi, I am having an issue which seems to be the same:

- A key is missing in the current language
- It tries to fallback to the default language
- For that, it tries to read the key in the default language translations **but** the default language translations are **not** loaded (only the current language).

It results in an exception like `TypeError: Cannot read property '...' of undefined` where `...` is the key of the translation I am trying to load.

**Version**: 2.1.0

**Workaround**: manually load the default language translations.

```ts
initializeTranslateServiceConfig() {
	this.translate.setDefaultLang(Conf.defaultLang);
	this.translate.use(Conf.lang);
	this.translate.getTranslation(Conf.defaultLang).subscribe();
}
```

But I don't think it is expected, and may fail for early translations (while the app is loading). Any idea about that? Did I miss something in the library recommended usage?

Thanks!

**Comment by Svoig** [comment]
Are there any plans to support the 'key is missing -> missingTranslationHandler -> defaultLanguage' flow? Or alternatively, to allow the use of a custom `TranslatePipe` in the `TranslateModule` configuration? That would allow for the same flexibility.
