### ISSUE TITLE
parser.flattenObject is called too often

### ISSUE THREAD

**Issue by ribizli** [ocombe/ng2-translate#47]
As the language definition JSON object can get complex, it is a performance penalty to always flatten this JSON, any time a ```translate.get``` (or ```translate.instant```) is called.

I'd recommend the other way: parsing the key (split by dot) and try to address the JSON field recursively.

E.g. (just a dummy demonstration): 
```
let key = 'keyA.keyB.keyC';
let keys = key.split('.');
let value;
try {
  value = obj;
  for (let i = 0; i < keys.length; i++) {
    value = value[key[i]];
  }
} catch (e) {
  value = '!!!not found';
}
```

**Comment by ocombe** [comment]
Hmm interesting yes, I'll take a look at this. If you want to do a PR you can :)

**Comment by ribizli** [comment]
During the PR I recognized that the `bundles/ng2-translate.js` is also checked in. I think it is unneeded, since `prepublish` creates this file for `npm`, right?

**Comment by ocombe** [comment]
Well it's nice to have it on github if people need it for plunkr (or something like that).

**Comment by ribizli** [comment]
For that there is: https://npmcdn.com/ng2-translate/bundles/ng2-translate.js

**Comment by ocombe** [comment]
Ahh nice, I didn't know that one.
When I have the time I'll add a plunkr that people can fork for issues, I'll use that, thanks.
