### ISSUE TITLE
Use without system.js

### ISSUE THREAD

**Issue by doczoidberg** [ocombe/ng2-translate#54]
Can you give a short example of using ng2-translate without system.js?

**Comment by ocombe** [comment]
It depends on your build tool, what do you use ? Webpack ?

**Comment by doczoidberg** [comment]
I use angular-cli which is based on ember-cli

**Comment by ocombe** [comment]
Well then you should do: `ng install ng2-translate` and then you might have to fix the bootstrap of your application because I think that the cli doesn't really work for that (check the docs on this part).

**Comment by doczoidberg** [comment]
I think `ng install ` isn't supported yet

**Comment by ocombe** [comment]
You're right, I just tested `ng install` and it doesn't work yet.
Just so you know, ng cli uses systemjs, if you need to change the systemjs config do to src/index.html.

In your case here are the steps:
- `npm install -S ng2-translate`
- open the src/index.html and change the systemjs config to something like that:
```ts
System.config({
        defaultJSExtensions: true,
        packages: {
            app: {
                format: 'register'
            },
            map: {
                'ng2-translate': 'node_modules/ng2-translate',
                'rxjs': 'node_modules/rxjs'
            }
        }
    });
```
- open src/app.ts and add ng2-translate:
```ts
import {bootstrap} from 'angular2/platform/browser';
import {Ng2ProjectApp} from './app/ng2-project';
import {ROUTER_PROVIDERS} from 'angular2/router';
import {TRANSLATE_PROVIDERS} from 'ng2-translate';

bootstrap(Ng2ProjectApp, [
  ROUTER_PROVIDERS,
  TRANSLATE_PROVIDERS
]);
```

- and then you can use it, for example in src/app/ng2-project.ts:
```ts
import {Component} from 'angular2/core';
import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
import {TranslateService} from "ng2-translate/ng2-translate";


@Component({
  selector: 'ng2-project-app',
  providers: [],
  templateUrl: 'app/ng2-project.html',
  directives: [ROUTER_DIRECTIVES],
  pipes: []
})
@RouteConfig([

])
export class Ng2ProjectApp {
  defaultMeaning: number = 42;
  
  constructor(translate: TranslateService) {
    translate.use('en');
  }
  
  meaningOfLife(meaning?: number) {
    return `The meaning of life is ${meaning || this.defaultMeaning}`;
  }
}
```

**Comment by doczoidberg** [comment]
thanks very much, I copied the ts-files into my project and added `TRANSLATE_PROVIDERS` to my bootstrap. Seems to work for now
