### ISSUE TITLE
can I use this library with the UpgradeAdapter

### ISSUE THREAD

**Issue by iwhp** [ocombe/ng2-translate#60]
I tried to use this library with the angular2 UpgradeAdapter. But I get the following error when I try to add it: `TypeError: Cannot read property 'toString' of undefined`

I tried the following
`upgradeAdapter.addProvider(TRANSLATE_PROVIDERS);`

Could someone provide a working sample. Thankx!

**Comment by ocombe** [comment]
I've never used the upgradeAdapter, but I think that you should upgrade `TranslateService` not `TRANSLATE_PROVIDERS` (which is an array of parameters)

**Comment by iwhp** [comment]
thankx ocombe! I have tried with `TranslateService`, unfortunately, same behavior.

I had a look at `ng2-translate.js` and saw that the following statement is used `System.registerDynamic`. Components form angular2 use `System.register` (e.g. http.js). I changed this in `ng2-translate.js`, but did not solve the issue. I am not sure if this could point somewhere...

**Comment by ocombe** [comment]
Ah you shouldn't use the bundle for that, use the js files from the npm repository (probably src/translate.service.js in your case).

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
