### ISSUE TITLE
Property 'useStaticFilesLoader' does not exist on type 'TranslateService'.

### ISSUE THREAD

**Issue by be-codified** [ocombe/ng2-translate#64]
Hi,

I am getting this error in my terminal window.

    initializeTranslateServiceConfig() {
        let prefix = './i18n/';
        let suffix = '.json';
        this.translate.useStaticFilesLoader(prefix, suffix);

I am using `"ng2-translate": "^1.8.0"`, what could be wrong?

**Comment by ocombe** [comment]
Hello, the api has changed in 1.10, see the release notes: https://github.com/ocombe/ng2-translate/releases/tag/v1.10.0

**Comment by be-codified** [comment]
Thank you for the information. I am trying to include it like this:

    import { TranslateService, TranslateLoader, TranslateStaticLoader } from 'ng2-translate/ng2-translate';

    @App({
      templateUrl: 'build/app.html',
      providers: [
        HTTP_PROVIDERS,
        provide(AuthHttp, {
          useFactory: (http) => {
            let config = new AuthConfig;
            config.tokenName = 'accessToken';
            return new AuthHttp(config, http);
          }
        }),
        provide(TranslateLoader, {
          useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
          deps: [Http]
        }),
        TranslateService, JwtHelper, AuthService, NoticeService, ConversationsService, MessagesService]
    })

But getting error `Cannot resolve all parameters for 'function (http) {
'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'function (http) {
' is decorated with Injectable.`

I have changed code only in app.ts (using Ionic2), what modifications should I do on pages? Thank you in advance.

**Comment by ocombe** [comment]
I think the error comes from:
```ts
provide(AuthHttp, {
      useFactory: (http) => {
        let config = new AuthConfig;
        config.tokenName = 'accessToken';
        return new AuthHttp(config, http);
      }
    }),
```

that should be
```ts
provide(AuthHttp, {
      useFactory: (http) => {
        let config = new AuthConfig;
        config.tokenName = 'accessToken';
        return new AuthHttp(config, http);
      },
      deps: [Http]
    }),
```

**Comment by be-codified** [comment]
Thank you.
