### ISSUE TITLE
Angular2 Beta 10 peer dependencies

### ISSUE THREAD

**Issue by spock123** [ocombe/ng2-translate#67]
I'm trying to install Angular2 Beta 10 and latest ng2-translate (1.10.1)

Seems like ng2 wants zone.js ^0.6.4 while ng2-translate wants zone.js ^0.5.10

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.12
npm ERR! npm  v2.14.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package zone.js@0.6.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.10 wants zone.js@^0.6.4
npm ERR! peerinvalid Peer ng2-translate@1.10.1 wants zone.js@^0.5.10

**Comment by ocombe** [comment]
I'll update the lib tonight or tomorrow. PeerDependencies should be satisfied since ^0.6.4 is technically part of ^0.5.10, but the ways of npm are not the ways of men :D

**Comment by ocombe** [comment]
I updated the lib and it should be ok for you now.

**Comment by spock123** [comment]
@ocombe  thank you so much - and 110% agree about npm.. sorry about these inconveniences..... and thank you again - your library is super awesome!
