### ISSUE TITLE
 No provider for TranslateLoader!

### ISSUE THREAD

**Issue by OmarHassan25** [ocombe/ng2-translate#68]
I am using ng2-translate to localize my ionic 2 app, But i am getting this runtime exception
`1     175606   group    EXCEPTION: No provider for TranslateLoader! (MyApp -> TranslateService -> TranslateLoader)
2     175607   error    EXCEPTION: No provider for TranslateLoader! (MyApp -> TranslateService -> TranslateLoader)
3     175607   error    STACKTRACE:
4     175607   error    Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:8101/build/js/app.bundle.js:7706:24)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:8101/build/js/app.bundle.js:8402:17)
    at new NoProviderError (http://localhost:8101/build/js/app.bundle.js:8438:17)
    at Injector._throwOrNull (http://localhost:8101/build/js/app.bundle.js:6745:20)
    at Injector._getByKeyDefault (http://localhost:8101/build/js/app.bundle.js:6796:22)
    at Injector._getByKey (http://localhost:8101/build/js/app.bundle.js:6736:26)
    at Injector._getByDependency (http://localhost:8101/build/js/app.bundle.js:6722:26)
    at Injector._instantiate (http://localhost:8101/build/js/app.bundle.js:6613:37)
    at Injector._instantiateProvider (http://localhost:8101/build/js/app.bundle.js:6603:26)
    at Injector._new (http://localhost:8101/build/js/app.bundle.js:6592:22)`

Here is how i am using it:
`import {App, Platform} from 'ionic-angular';
import {TabsPage} from './pages/tabs/tabs';
import {TranslateService, TranslatePipe} from 'ng2-translate/ng2-translate';

// https://angular.io/docs/ts/latest/api/core/Type-interface.html
import {Type} from 'angular2/core';

@App({
    template: '<ion-nav [root]="rootPage"></ion-nav>',
    config: {},
    providers: [TranslateService],
    pipes: [TranslatePipe]
})
export class MyApp {
    rootPage: Type = TabsPage;
    translate;

    constructor(platform: Platform, translate: TranslateService) {
        this.translate = translate;

        platform.ready().then(() => {
            console.log(navigator.language.split('-')[0]);
              this.initializeTranslateServiceConfig();
        });
    }

    initializeTranslateServiceConfig() {
        var prefix = 'assets/i18n/';
        var suffix = '.json';
        this.translate.useStaticFilesLoader(prefix, suffix);
        var userLang = navigator.language.split('-')[0];
        userLang = /(de|en|hr)/gi.test(userLang) ? userLang : 'en';
        this.translate.setDefaultLang('en');
        this.translate.use(userLang);
    }
}
`
Please help in finding why i have this error,

**Comment by ocombe** [comment]
Hello, you're using the old configuration. It has changed in 1.10.

For Ionic 2 here is a complete bootstrap with configuration:
```ts
import {provide} from 'angular2/core';
import {TranslateService, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';

@App({
  templateUrl: '....',
  config: {},
  providers: [
    provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [Http]
    }),
    TranslateService
  ]
});
```

**Comment by jjrchrds** [comment]
@ocombe does this go in app.ts/js?

Thank you

**Comment by rklumanlan** [comment]
how can i convert this to javascript? i am just new to ionic2 and angular 2.. i am not using typescript.

>
provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [Http]
    }),

**Comment by Mage111** [comment]
I have same issue when I upgrade ng2-translate to latest version (5.0.0)
I have already use the new configuration:

`import {
    TranslateModule,
    TranslateService,
    TranslateLoader,
    TranslateStaticLoader
} from 'ng2-translate/ng2-translate';`

` function translateLoader(http: Http) {
            return new TranslateStaticLoader(http, 'assets/i18n', '.json');
        }

  providers: [TranslateService,
                {
                    provide: TranslateLoader,
                    useFactory: translateLoader,
                    deps: [Http]
                }
            ]`

It's work fine in previews version. (I need to upgrade for getting metadata file for Aot compilation)

Thanks.

**Comment by beenotung** [comment]
re: @ocombe commented on Mar 20
`@App`, `@angular/core.provide` are no longer available, what should I do on the current version? (ionic 2.1.18)

**Comment by ocombe** [comment]
@beenotung check the super starter from ionic: https://github.com/driftyco/ionic-starter-super
it includes ng2 translate :)

**Comment by Mage111** [comment]
The app you have refereed to, use ng2 trranslate version: 4.0.0
This version worked for me also. they use it in the same way as me.
version 5.0.0 still occurred the above error.
