### ISSUE TITLE
custom interpolators

### ISSUE THREAD

**Issue by david-gang** [ocombe/ng2-translate#69]
Hi,

It is possible to use custom interpolators like in angular translate?

https://angular-translate.github.io/docs/#/guide/15_custom-interpolators

Thanks,
David

**Comment by ocombe** [comment]
Hello, it's not possible yet, but it shouldn't be too difficult, we just need to add a config param to the parser.

**Comment by c1rus** [comment]
what about making parser injectable?

**Comment by ocombe** [comment]
Hello, the parser is now injectable and you can create your own custom parser if you need, closing this :)
