### ISSUE TITLE
Update to angular2.0.0-alpha.53

### ISSUE THREAD

**Issue by qina83** [ocombe/ng2-translate#7]
I need a version compatible with angular2.0.0-alpha.53.
Now you have fix on package.json  "angular2": "2.0.0-alpha.52", as dependency

**Comment by ocombe** [comment]
Hello,
Angular alpha 53 has been released yesterday, I will update the lib tonight or tomorrow (more likely), but feel free to make a pull request if you need it before that.
And thanks for using my lib ! :)

**Comment by ocombe** [comment]
This is now available thanks to a PR from @r-park :)
