### ISSUE TITLE
es6-shim has to be 0.35.0 for angular 2 update

### ISSUE THREAD

**Issue by mbakker96** [ocombe/ng2-translate#72]
I updated angular 2 to version beta 12 and they updated the es6-shim to version 0.35.0.

But the ng2-translate want to have version 0.33.3

```bash 
npm ERR! peerinvalid The package es6-shim@0.33.13 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.12 wants es6-shim@^0.35.0
npm ERR! peerinvalid Peer ng2-translate@1.10.3 wants es6-shim@>= 0.33.3
```

**Comment by ocombe** [comment]
What version of node / npm do you use? They fixed the peer dependencies in npm 3 (it was too rigid in npm 2).
I'm asking for ">= 0.33.3" which should be ok.

**Comment by mbakker96** [comment]
@ocombe oops..... npm version: 2.14.12

**Comment by ocombe** [comment]
Try again with npm 3 then, it should fix your problem :)
