### ISSUE TITLE
how to make use of bundles?

### ISSUE THREAD

**Issue by allenhwkim** [ocombe/ng2-translate#73]
I would appreciate any example of how to make use of bunldles/*.

I looked at [this](https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#bundle-extension), and I don't have an idea to relate to bundles/ng2-translate.js. If I see some examples of using bunldles file in your README.me, it would be greatly appreciated.

**Comment by ocombe** [comment]
It should work the exact same way as for angular 2, you include a script tag with the ng2-translate bundle after the script tag for angular 2 and before your systemjs start

**Comment by allenhwkim** [comment]
Closing this, and opeing https://github.com/ocombe/ng2-translate/issues/77 to continue the question.
