### ISSUE TITLE
Unable to get property 'KEY' of undefined or null reference

### ISSUE THREAD

**Issue by shmu80** [ocombe/ng2-translate#74]
I am implement ng2-translate into Ionic 2 project. At first, I am having build error. After I modify some variable declare to the code below, it has no issue during project build.
```
@App({
  templateUrl: 'build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    provide(TranslateLoader, {
      useFactory: (http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [[Http]]
    }),
    TranslateService
  ],
  pipes: [TranslatePipe]
})
```
Anyway, I am having property undefined issue now.

> EXCEPTION: TypeError: Unable to get property 'title' of undefined or null reference in [ {{ "title" | translate }} in AccessPage@7:13

Below is my access page code
```
    <ion-navbar *navbar>
      <ion-title> {{ "title" | translate }} </ion-title>
    </ion-navbar>
```

and my code in en.json.
```
    {
    "title" : "Testing",
    }
```
so I am wondering the problem is because it couldn't find the en.json (located at www/assets/i18n folder) or some other issue.

**Comment by ocombe** [comment]
Do you get a 404 while trying to load the en.json file in your network panel? Or does it work?

**Comment by shmu80** [comment]
While I build the ionic 2 project, the console log just prompt me <Unable to get property 'title' of undefined or null reference...> error message. it doesn't have 404 related error message in the console.

Actually my question is how can I know the system able to load/find en.json?

Warmest Regards,

BYLIM

http://matchboxstation.blogspot.com/


Date: Mon, 28 Mar 2016 00:50:26 -0700

**Comment by ocombe** [comment]
Well you open your dev tools, and go to the network panel and see if there is a 404 or if it loads en.json fine :)

**Comment by shmu80** [comment]
I will check for it.
Between, do you know why if I code as suggested below, I failed to deploy, but some other developer has no issue for this code

```
import {TranslateService, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';
import {provide} from 'angular2/core';

@App({
  templateUrl: 'build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    provide(TranslateLoader, {
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: [Http]
    }),
    TranslateService
  ]
})
```
Refer the error code Row 15, Column 23 is belong to (http: Http)

> ERROR in ./app/app.js
> Module build failed: SyntaxError: C:/Projects/apps/myapp/app/app.js: Unexpected token (15:23)
>   providers: [
>     provide(TranslateLoader, {
>       useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
>       deps: [Http]
>     }),
>     TranslateService

When I change my code to below, it has no build error.
```
@App({
  templateUrl: 'build/app.html',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [
    provide(TranslateLoader, {
      useFactory: (**_http_**) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
      deps: **_[[Http]]_**
    }),
    TranslateService
  ],
  pipes: [TranslatePipe]
})
```

**Comment by ocombe** [comment]
I don't see an import for Http: `import {Http} from "angular2/http";`

**Comment by shmu80** [comment]
Yes. the code also include, `import {Http} from "angular2/http";`,  I miss copy to this comment.

**Comment by ocombe** [comment]
Well no idea then, maybe it's the version of angular 2 ?

**Comment by shmu80** [comment]
This is my angular2 version, `"angular2": "2.0.0-beta.6",`. Should I upgrade to latest version, beta 11?

**Comment by ocombe** [comment]
The latest is beta 12 actually :)
And you should upgrade for sure, but I don't know if that would fix this problem.

**Comment by shmu80** [comment]
the issue fixed after I update the angular2 version to beta 12.
Thanks.

**Comment by ocombe** [comment]
Good to know thanks, I will update the required dependency
