### ISSUE TITLE
Get multiple localized string values

### ISSUE THREAD

**Issue by OmarHassan25** [ocombe/ng2-translate#75]
How i can get localized values for a set of string in one step? 

I use this
 `  this.translate.get('forgetPassword').subscribe(translatedValue => {
          alert(translatedValue);
      });` to get single value, but i want to get multiple values at once,

Regards

**Comment by ocombe** [comment]
You can use an array of keys instead of just a string. You will get an
object of keys/values as a result.

Le lun. 28 mars 2016 13:01, OmarHassan25 <notifications@github.com> a
écrit :

**Comment by OmarHassan25** [comment]
Well Done,
