### ISSUE TITLE
Error: XHR error (404 Not Found) loading .. /ng2-translate/ng2-translate

### ISSUE THREAD

**Issue by allenhwkim** [ocombe/ng2-translate#77]
I think I followed the direction in README.md, but I got this error.
It could be very tiny mistake that I made, but I could not figure it out.

![image](https://cloud.githubusercontent.com/assets/1437734/14163122/34fe42fa-f6c0-11e5-83a7-7abad9b9c2cc.png)

http://plnkr.co/edit/ntq01S?p=preview

Any help would be appreciated with the example given

**Comment by allenhwkim** [comment]
FYI, This is the bundle script that I used
```
    <script src="https://rawgit.com/ocombe/ng2-translate/master/bundles/ng2-translate.js"></script>
```

**Comment by Grmiade** [comment]
I have the same error :/

**Comment by kvgros** [comment]
Same issue here.  Renders the library useless as it crashes immediately on this.   Any one else seeing this?

**Comment by ksontini** [comment]
Hi,
Localy when you use npm instead of CDN you still got the same error?
Via npm I can't reproduce this. Can you reproduce this with Angular2 >= beta15?

**Comment by gc392** [comment]
I am using beta 15 and I have the same problem:

In app.ts, TS compiles,
import {TRANSLATE_PROVIDERS, TranslateService, TranslatePipe, TranslateLoader,
   TranslateStaticLoader} from 'ng2-translate/ng2-translate';

index.html

<script src="lib/ng2-translate.js"></script>

then in browser I get
http://localhost:4200/ng2-translate/ng2-translate.js 404 (Not Found)
angular2-polyfills.js:390 Error: Error: XHR error (404 Not Found) loading http://localhost:4200/ng2-translate/ng2-translate.js

**Comment by VsMaX** [comment]
I have had the same problem. You are missing mapping ng2-translate to node_modules/ng2-translate in the map section of your config. 

Here is my systemjs.config.js

https://gist.github.com/VsMaX/214688cee7ff58989fab72948fe80b00

**Comment by gc392** [comment]
I could finally make it work. I am using angular cli and had to edit system-config.ts and add
const map: any = {
  'ng2-translate': 'vendor/ng2-translate'
};

/** User packages configuration. */
const packages: any = {
  'ng2-translate': {
    defaultExtension: 'js'
  }
}

and in angular-cli-build.js I added the file in vendorNpmFiles, so it is copied in dist
      'ng2-translate/**/*.js'

**Comment by rgajam** [comment]
After updating system-config.ts as @gc392 mentioned,

In angular-cli-build.js I added the file in vendorNpmFiles:
`'ng2-translate/**/*.js'`

**Comment by bulentozdil** [comment]
system-config.ts
const map: any = {
  'ng2-translate': 'vendor/ng2-translate'
};

/** User packages configuration. */
const packages: any = {
  'ng2-translate': { defaultExtension: 'js' }
};

in angular-cli-build.js remove 'ng2-translate/**/*.js'

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
