### ISSUE TITLE
Translation doesn't work in Ionic2 Modal

### ISSUE THREAD

**Issue by vukasin0** [ocombe/ng2-translate#78]
I'm creating modal regularly by following Ionic2 documentation:
http://ionicframework.com/docs/v2/api/components/modal/Modal/

TranslationService works OK in base page but not in overlays.

Anyone has/had this issue ?

Should I pass somehow translation reference to Modal ?

I'm bit confused as I'm not receiving any error / warning in console.

**Comment by vukasin0** [comment]
Ah - it was issue on my side produced by `include` hell.

I had some dead include which nor `tsc` nor `intelij` didn't report :(

Sorry for producing buzz.

**Comment by ocombe** [comment]
No prob :)
