### ISSUE TITLE
Fail to get translate value in app.js

### ISSUE THREAD

**Issue by shmu80** [ocombe/ng2-translate#80]
Hi, 
I am using ionic 2 and import the ng2-translate, but I failed to retrieve the translate value in app.js file. The value has no issue to display in HTML.
Can you please advise?

en.json
`"title" : "Test Title",`

app.js

  ```
  this.translate.get("title").subscribe(this.translatedValue);
    console.log("translates : " + this.translatedValue);
```

Console log
`log translates : undefined`

**Comment by ocombe** [comment]
Hmm I think that this should work better:
```ts
 this.translate.get("title").subscribe(res => {
    this.translatedValue = res;
    console.log("translates : " + res);
});
```

**Comment by shmu80** [comment]
Thanks for the advice.
Yes, the res = "Test Title
But I code as below, the this.translatedValue is empty

```
 this.translate.get("title").subscribe(res => {
    this.translatedValue = res;
    console.log("translates : " + res);
});
console.log("translatedValue: " +  this.translatedValue);
```

Can you please advise?

**Comment by ocombe** [comment]
Of course it is empty, you are calling the value before the observable returns.
Observables are asynchronous (like promises).

**Comment by shmu80** [comment]
Can you advise how to use the instant method to get the immediate result?
I try the code below, but failed to get the value too.

`console.log(this.translate.instant("title"))`

**Comment by ocombe** [comment]
The instant method will only work if you already have the translations available, which might not be the case if you use an async loader (such as the default loader).
If you load the translations async, use async code.

**Comment by shmu80** [comment]
Thanks for the advice.
