### ISSUE TITLE
"Invalid module name in augmentation" errors with VS2015

### ISSUE THREAD

**Issue by DustinByfuglien** [ocombe/ng2-translate#81]
Good day!

When trying to link ng2-translate to my TypeScript-application an errors rises in Microsoft VisualStudio2015:

TS2664	Invalid module name in augmentation, module '../../Observable' cannot be found.	\node_modules\rxjs\add\observable\of.d.ts	2

TS2664	Invalid module name in augmentation, module '../../Observable' cannot be found.	\node_modules\rxjs\add\observable\map.d.ts	2

TS2664	Invalid module name in augmentation, module '../../Observable' cannot be found.	\node_modules\rxjs\add\observable\merge.d.ts	2

TS2664	Invalid module name in augmentation, module '../../Observable' cannot be found.	\node_modules\rxjs\add\observable\share.d.ts	2

TS2664	Invalid module name in augmentation, module '../../Observable' cannot be found.	\node_modules\rxjs\add\observable\toArray.d.ts	2

I use Typescript 1.8, ng2-translate 1.11.0, angular 2.0.0-beta.13

Help please!

**Comment by ocombe** [comment]
Hello, check the version of RxJS that you use, they updated it in beta 12

**Comment by DustinByfuglien** [comment]
I use rxjs 5.0.0-beta.4

**Comment by ocombe** [comment]
Ok, that's the problem, Angular 2 has a dependency for beta 2, fix the version to that and it should be ok.

**Comment by DustinByfuglien** [comment]
It works well with beta2.

Thank you very much!

**Comment by ocombe** [comment]
No problem :)

**Comment by Phatsuo** [comment]
This has popped back up. I noticed beta 17 asking for rxjs@5.0.0-beta.6.

**Comment by ocombe** [comment]
Well I removed the peer dependency to RxJS from ng2-translate (I required angular 2 which require RxJS), so this problem is not on this lib.

**Comment by ppparihar** [comment]
I am facing the same issue after upgrading angular to 2.0.0-rc.1 and Rxjs version is 5.0.0-beta.6.

**Comment by IsaacBorrero** [comment]
@Phatsuo Did you solve this problem.  I am having the same.  It is not related to ng2-translate.

**Comment by VahidN** [comment]
[The real solution for this problem.](https://github.com/Microsoft/TypeScript/issues/8518#issuecomment-217960231)
