### ISSUE TITLE
onLangChange not working

### ISSUE THREAD

**Issue by koodikindral** [ocombe/ng2-translate#84]
Hi,

Is there more detailed documentation on onLangChange event, i.e. how to use it in different components?

**Comment by ocombe** [comment]
It's an observable, so you can use it just like any observable.
I use it in the TranslatePipe if you want to see an implementation: https://github.com/ocombe/ng2-translate/blob/master/src/translate.pipe.ts#L115-L117

**Comment by koodikindral** [comment]
thanks! got it working!
