### ISSUE TITLE
Translate html code

### ISSUE THREAD

**Issue by hakalb** [ocombe/ng2-translate#86]
I have html code inside my json file

`{
  "contactEMailDescription": "Contact <a href='mailto:{{value}}@foo.bar'>{{value}}</a> for more information"
}
`

My html template
`<div class="panel-footer"><small>{{ 'contactEMailDescription' | translate:{value:'info'} }}</small></div>`

The outcome is not treated as html syntax, just as plain text.

`Contact <a href='mailto:info@foo.bar'>fibi</a> for more information`

when I would like it to look like:
Contact <a href='mailto:info@foo.bar'>fibi</a> for more information

Is it not possible to add html code inside the translate json file?

**Comment by ocombe** [comment]
It is, but you're outputing the translation as text. If you want html you should do that:

```html
<div class="panel-footer"><small [innerHTML]="'contactEMailDescription' | translate:{value:'info'}"></small></div>
```

**Comment by hakalb** [comment]
I love the angular2 magic. Thanks :+1:

**Comment by 0917** [comment]
Hi @ocombe, 
I propose to add information from this thread to documentation page.
IMHO it's quite common use case and more people (including also me) may have such problem.
Anyway, great thanks for help! :)
