### ISSUE TITLE
Support empty string for pipe parameters

### ISSUE THREAD

**Issue by Tiuser4567** [ocombe/ng2-translate#88]
Hi,
Given
"title" : "Welcome {{name}}!"
{{'title' | translate:{name:""} }}

This is shown as "Welcome {{name}}!"
Please advise if possible to support empty strings for the Translate pipe parameter values "" as there may be cases that the parameter value can be set to an empty string.

Thanks

**Comment by ocombe** [comment]
Good point, the current code checks the length to determine if it's defined, it should just check if it is defined at all.

**Comment by hakalb** [comment]
It is the same with `0`. That is worse since my app sometimes have zero numbers to display.
When do you think this will be fixed?

**Comment by hakalb** [comment]
I found a work around for `0`. Convert number to string using `.toString()` - then the text has length 1.

**Comment by cristi-badila** [comment]
I think this was fixed in https://github.com/ocombe/ng2-translate/commit/3fb23352

**Comment by ocombe** [comment]
Yes :)
