### ISSUE TITLE
ng-translate select defaultlangue instead of standard language in first loading [only in firefox]

### ISSUE THREAD

**Issue by ksontini** [ocombe/ng2-translate#90]
Hi,

Steps to reproduce the issue:

1.  .setDefaultLang ('en') and .use('en') to load it. 
2.  .use('fr') as a standard lang.
3.  Enable dev mode in angular.
4.  Load the app in firefox 45.

=> I'm getting translations in 'en' instead of 'fr'. This behavior is only in Firefox 45 in the first load.
 I can't reproduce in Firefox developer edition or Chrome.

I'm missing something?

**Comment by ocombe** [comment]
Damn, yes I can reproduce this, thanks for the report

**Comment by ksontini** [comment]
This is litle bit random. 
If I'm right, it's the case when the subscribe inside the getTranslation if fired in inverse ordre. 

I explain:
In the first load: 
1. Use default lang => getTranslation('en') => subscribe (line 120)
2. Use 'fr => getTranslation('fr') => subscribe. 
3. The callback of the 'fr' is fired
4. The callback of 'en' then.
5. Get 'en' as translated lang

But I don't know why it's only in Firefox

**Comment by ocombe** [comment]
I was able to reproduce the bug yesterday, but today I don't. The only thing that I changed is that I updated to beta 15, can you update as well and try if you still have the problem ?

**Comment by ksontini** [comment]
As I said it's random.
After updating, I tried and got the same error. It was not from the first load but after serval refresh. [Firefox 45.0.2]
