### ISSUE TITLE
dynamic translations

### ISSUE THREAD

**Issue by andykais** [ocombe/ng2-translate#97]
I have been building a translation pipe for a few days now, thats how I came across yours. I see that *For now, only the static loader is available*. My employer wanted the translations to be dynamic (no page refresh on language change). I found a solution on [stack](http://stackoverflow.com/a/36625011/3795137) for triggering pipes even when strings are being passed to it. It basically equates to passing a param to all the translation pipes which determines the language. When that param changes, the pipe is triggered
```
{ "hello world" | translate:chosenLanguage }
```
`chosenLanguage` needs to be available to all component views and could be propagated through the app in [various ways](http://stackoverflow.com/questions/34700438/global-events-in-angular-2)

**Comment by ocombe** [comment]
The files loader which is available currently is able to load a new lang without reloading the page.

Anyway, what is your question?

**Comment by andykais** [comment]
woops, I just played with the example, I can see this not what you meant. Apologies! You can just close this issue

**Comment by ocombe** [comment]
Ok :-)
